package flow.subflow.DynamicFlow;

import java.util.Collection;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.avaya.sce.runtime.Goto;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2026-FEB-12  12:04:24 PM
 */
public class DynamicNextNode extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-12  12:04:24 PM
	 */
	public DynamicNextNode() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Experienve Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2026-FEB-12  12:04:24 PM
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {

		// TODO: Add your code here!

	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("DynamicFlow-End", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
	@Override
	public void updateBranches(Collection branches, SCESession mySession) {

	    Goto aGoto = null;

	    try {
	    	String nextNode = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
	    	 boolean has_banking = mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_HAS_BANKING).getBooleanValue();
	 	    boolean has_credit  = mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_HAS_CREDIT).getBooleanValue();
	 	    boolean API_Staus = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_API__STATUS).getBooleanValue();
	 	    
	 	   TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"THE NEXT NODE NAME : "+nextNode+" API FLAG : "+API_Staus, mySession);
	 	   
	 	  if(API_Staus) {
	 		 TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"************API FAIL TRANSFER**********", mySession);
	 		   aGoto = new Goto("DynamicFlow-ApiFail", 0);
	            branches.clear();
		        branches.add(aGoto);
		        super.updateBranches(branches, mySession);
		        return;
	    } 
	    	
	    	if("ROUTING_LOGIC".equalsIgnoreCase(nextNode)) {
	    		int  MainMenu = mySession.getVariableField(IProjectVariables.DYNAMIC,IProjectVariables.DYNAMIC_FIELD_VALUE).getIntValue();
	    		
	    		
	    		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"MAIN_MENU CUSTMER INPUT : "+MainMenu, mySession);
	    		if(has_credit && has_banking) {
	    			if(MainMenu == 1) {
	    				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"************BankingServices1**********", mySession);
		    			aGoto = new Goto("BankingServices1", 0);
			            branches.clear();
				        branches.add(aGoto);
	    			}else if (MainMenu == 2) {
	    				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"************CreditCard1**********", mySession);
		    			aGoto = new Goto("CreditCard1", 0);
			            branches.clear();
				        branches.add(aGoto);
	    			}else if(MainMenu == 3) {
	    				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"************TPIN1**********", mySession);
		    			aGoto = new Goto("TPIN1", 0);
			            branches.clear();
				        branches.add(aGoto);
	    			}
	    				
	    		}else if(has_credit) {
	    			if(MainMenu == 1) {
	    				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"************BankingServices1**********", mySession);
		    			aGoto = new Goto("CreditCard1", 0);
			            branches.clear();
				        branches.add(aGoto);
	    			}else if (MainMenu == 2) {
	    				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"************CreditCard1**********", mySession);
		    			aGoto = new Goto("TPIN1", 0);
			            branches.clear();
				        branches.add(aGoto);
	    			}
	    		}else if(has_banking) {
	    			if(MainMenu == 1) {
	    				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"************TPIN1**********", mySession);
		    			aGoto = new Goto("BankingServices1", 0);
			            branches.clear();
				        branches.add(aGoto);
	    			}else if (MainMenu == 2) {
	    				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"************CreditCard1**********", mySession);
		    			aGoto = new Goto("TPIN1", 0);
			            branches.clear();
				        branches.add(aGoto);
	    			}
	    		}
	    		super.updateBranches(branches, mySession);
	    		return;
	    	}else if ("ROUTING_LOGIC2".equalsIgnoreCase(nextNode)){
	    		int  RepeatMenu = mySession.getVariableField(IProjectVariables.DYNAMIC,IProjectVariables.DYNAMIC_FIELD_VALUE).getIntValue();
	    		
	    		if(RepeatMenu == 1) {
	    			processNode(nextNode, 0, mySession);
	    			String ANY_NODE = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
	    			processNode(ANY_NODE, 0, mySession);
	    			
	    		}else if(RepeatMenu == 2) {
	    			processNode(nextNode, 1, mySession);
	    		}	    		
	    	}else {
			    processNode(nextNode, 0, mySession);
	    	}
	    
			    
			
	    	String Description = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DESCRIPTION).getStringValue();
	    	
		    
	    	String preferredLanguage = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_PREFERRED_LANGUAGE).getStringValue();
	    	
	        String nodeType = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_ID).getStringValue();
	        
	        
	        boolean Emg_Flag = mySession.getVariableField(IProjectVariables.VARIABELS,IProjectVariables.VARIABELS_FIELD_EMG_FLAG).getBooleanValue();
	        
	        boolean RMN_Flag =mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_RMNFLAG).getBooleanValue();

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"ROUTING | NODE_TYPE : " + nodeType + " NODE_NAME : " + Description+" NEXT_NODE : "+nextNode+"PREFERRED LANG :"+preferredLanguage,mySession);

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NODE NAME : "+nextNode+" RMN_FLAG : "+RMN_Flag+" API FLAG : "+API_Staus, mySession);
	        /* =========================
	         * ANNOUNCEMENT
	         * ========================= */
	       
		    
    	

    	// 2️⃣ Get existing menu description
    	String existingDesc = mySession.getVariableField(
    	        IProjectVariables.CALL_HISTORY,
    	        IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).getStringValue();

    	if(existingDesc == null){
    	    existingDesc = "";
    	}

    	// 3️⃣ Append to MENU_DESCRIPTION only if valid
    	if(Description != null) {

    	    // Remove unwanted pipes and spaces
    	    Description = Description.replace("|", "").trim();

    	    if(!Description.isEmpty()) {

    	        if(existingDesc.endsWith("|")) {
    	            existingDesc = existingDesc + Description + "|";
    	        } else if(existingDesc.isEmpty()) {
    	            existingDesc = Description + "|";
    	        } else {
    	            existingDesc = existingDesc + "|" + Description + "|";
    	        }

    	        mySession.getVariableField(
    	                IProjectVariables.CALL_HISTORY,
    	                IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION)
    	                .setValue(existingDesc);
    	    }
    	}

    	// 4️⃣ Set EXIT_LOCATION to the last node — overwrite every time
    	String exitNode = mySession.getVariableField(
    	        IProjectVariables.NODE_DETAILS,
    	        IProjectVariables.NODE_DETAILS_FIELD_ID).getStringValue();

    	// Directly overwrite, no append
    	if(exitNode != null && !exitNode.trim().isEmpty()) {
    	    mySession.getVariableField(
    	            IProjectVariables.CALL_HISTORY,
    	            IProjectVariables.CALL_HISTORY_FIELD_EXIT_LOCATION)
    	            .setValue(nextNode);
    	}


	        
	        if("GENERAL_MSG".equalsIgnoreCase(Description)) {
	        	aGoto = new Goto("DynamicFlow-End", 0);
	        	processNode(nextNode, 0, mySession);
	            branches.clear();
		        branches.add(aGoto);
	        }
	        if("PREFERRED_LANG_MENU".equalsIgnoreCase(nextNode) && !RMN_Flag) {
	        	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"************CUSTOMER NOT FOUND SKIP PREFERRED LANG**********", mySession);
	        	processNode(nextNode, 0, mySession);
		        aGoto = new Goto("GENERAL_MSG", 0);
		        branches.clear();
		        branches.add(aGoto);
	        }else if("LANGUAGE_MENU".equalsIgnoreCase(nextNode) && preferredLanguage != null && !preferredLanguage.trim().isEmpty()) {
	        	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"************CUSTOMER HAS PREFERRED LANGUAGE**********", mySession);
	        	processNode(nextNode, 0, mySession);
		        aGoto = new Goto("GENERAL_MSG", 0);
		        branches.clear();
		        branches.add(aGoto);
	        }else if ("GENERAL_MSG".equalsIgnoreCase(nextNode)) {	
		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"************GOTO GENERAL MSG**********", mySession);
	            aGoto = new Goto("GENERAL_MSG", 0);
	            branches.clear();
		        branches.add(aGoto);	
	        }else if (nodeType.startsWith("ANN") ) {
	            aGoto = new Goto("DynamicFlow-ANN", 0);
	            branches.clear();
		        branches.add(aGoto);
	        }else if (nodeType.startsWith("MEN")) {
	            aGoto = new Goto("DynamicFlow-MEN", 0);
	            branches.clear();
		        branches.add(aGoto);
	        }else if ("AUTHENTICATION".equalsIgnoreCase(nextNode)) {
	        	aGoto = new Goto(nextNode, 0);
	        	processNode(nextNode, 0, mySession);
	            branches.clear();
		        branches.add(aGoto);
	        } 
	    } catch (Exception e) {
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                "updateBranches Error: " + e.getMessage(), mySession);
	        aGoto = new Goto("SetTechDiffPrompt", 0);
	        branches.clear();
	        branches.add(aGoto);
	    }

	    super.updateBranches(branches, mySession);
	}
	private void processNode(String nodeDescription,int NextNode, SCESession mySession) throws Exception {

	    // ================================
	    // FETCH NODE JSON
	    // ================================
	    JSONObject nodeDetails = IVRFlow.getNodeByDescription(nodeDescription);

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NODE JSON DETAILS : " + nodeDetails.toString(), mySession);
	    
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= NODE DETAILS START =============",mySession);

	    // ================================
	    // NODE NAME (DESCRIPTION)
	    // ================================
	    String nodeName = nodeDetails.getString("Description");
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NODE NAME : " + nodeName, mySession);
	    mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DESCRIPTION).setValue(nodeName);

	    // ================================
	    // NODE ID
	    // ================================
	    String nodeId = nodeDetails.getString("ID");

	    mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_ID).setValue(nodeId);

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NODE TYPE : " + nodeId,mySession);

	    // ================================
	    // MENU PROMPTS
	    // ================================
	    JSONArray menuPrompts = nodeDetails.getJSONArray("menuPrompts");
	    int promptCount = menuPrompts.length();

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"MENU PROMPT COUNT : " + promptCount,mySession);

	    mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_PROMPT_COUNT).setValue(promptCount);

	    for (int i = 0; i < promptCount; i++) {

	        String prompt = menuPrompts.getString(i);
	        String promptKey = "Prompt_" + (i + 1);

	        mySession.getVariableField(IProjectVariables.PROMPT_URL,promptKey).setValue(prompt);
	        mySession.getVariableField(IProjectVariables.PROMPT_HIN_URL,promptKey).setValue(prompt);

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,promptKey + " : " + prompt,mySession);
	    }

	    // ================================
	    // MENU DTMF (ONLY FOR MENU NODES)
	    // ================================
	    if (nodeId.toUpperCase().startsWith("MEN")) {

	        JSONArray menuDTMFArray = nodeDetails.getJSONArray("menuDTMF");
	        int maxDTMF = 0;

	        for (int i = 0; i < menuDTMFArray.length(); i++) {
	            int value = Integer.parseInt(menuDTMFArray.getString(i));
	            maxDTMF = Math.max(maxDTMF, value);
	        }

	        mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DTMF).setValue(maxDTMF);

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"MENU DTMF : " + maxDTMF,mySession);
	    }
	    

	 // ================================
	 // NEXT NODE HANDLING
	 // ================================
		 JSONArray nextNodeArray = nodeDetails.optJSONArray("nextNode");
		 String nextNodeToUse = null;

		 if (nextNodeArray != null && nextNodeArray.length() > 0) {

		     if (NextNode >= 0 && NextNode < nextNodeArray.length()) {

		         nextNodeToUse = nextNodeArray.getString(NextNode);

		     } else {

		         TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
		                 "Invalid NextNode index: " + NextNode +
		                 " Array Size: " + nextNodeArray.length(),
		                 mySession);

		         // fallback to first element
		         nextNodeToUse = nextNodeArray.getString(0);
		     }

		 } else if (nodeDetails.has("nextNode")) {

		     nextNodeToUse = nodeDetails.getString("nextNode");
		 }
		 TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NEXT NODE TO USE : " + nextNodeToUse,mySession);
		 mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).setValue(nextNodeToUse);
	}

}
