package flow.subflow.DynamicFlow;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.HostJar.API.api;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import DTO.SetPreferredLanguageResponse;
import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-12  12:04:24 PM
 */
public class ExitMenu extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-12  12:04:24 PM
	 */
	public ExitMenu() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("DynamicFlow-DynamicNextNode", "Default");
		next.setDebugId(47);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);
		
		int Input = mySession.getVariableField(IProjectVariables.DYNAMIC,IProjectVariables.DYNAMIC_FIELD_VALUE).getIntValue();
		String NextNodeDescription = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
		
		if (NextNodeDescription.equalsIgnoreCase("PREFERRED_LANG_MENU") && Input == 1) {
			mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_LANGUAGE).setValue("EN");
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"****SET PREFERRED LANGUAGE AS EN****",mySession);
		}else if (NextNodeDescription.equalsIgnoreCase("PREFERRED_LANG_MENU") && Input == 2){
			mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_LANGUAGE).setValue("HI");
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"****SET PREFERRED LANGUAGE AS HI****",mySession);
		}
		
		if(NextNodeDescription.equalsIgnoreCase("GENERAL_MSG")) {
			try {	
         String Token = mySession.getVariableField(IProjectVariables.OAUTH,IProjectVariables.OAUTH_FIELD_TOKEN).getStringValue();
         
        String RelationShipID =  mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_RELATION_SHIP_ID).getStringValue();
		    
        String Lang = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_LANGUAGE).getStringValue();
        
        String PreferredLanguage = null;
        
        if (Lang.equalsIgnoreCase("EN")) {
        	 PreferredLanguage = "EN";
        }else if(Lang.equalsIgnoreCase("HI")) {
             PreferredLanguage = "HI";
        }

        LocalDateTime currentTime = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

        String requesttime = currentTime.format(formatter);
        String UCID = mySession.getVariableField(IProjectVariables.SESSION,IProjectVariables.SESSION_FIELD_UCID).getStringValue();
        
			SetPreferredLanguageResponse Response;
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"UCID : " + UCID,mySession);
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"RELATION SHIP : " + RelationShipID,mySession);
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"PREFERRED LANGUAGE : " + PreferredLanguage,mySession);
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"REQ TIME : " + requesttime,mySession);
	
				Response = api.SetPreferredLanguageAPI(UCID, RelationShipID, PreferredLanguage, requesttime);
				
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SetPreferredLanguage API Response : " + Response,mySession);
				
			} catch (Exception e) {
				e.printStackTrace();
				mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_API__STATUS).setValue(true);
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"ERROR : " + e.getMessage(),mySession);				
			}

			
		}
	}
		
}
