package flow.subflow.NINM_FLOW;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;


import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-03  01:57:06 PM
 */
public class fetch extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-03  01:57:06 PM
	 */
	public fetch() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-15  07:45:24 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-15  07:45:24 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-15  07:45:24 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
		// TODO Auto-generated method stub
		super.requestBegin(mySession);
		
		String NextNodeDescription = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
		JSONObject menuDetails = IVRFlow.getNodeByDescription(NextNodeDescription);
		
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
		        "FETCH_NEXTNODE VALUE -> " + NextNodeDescription,
		        mySession);
		

		JSONArray menuPrompts = menuDetails.getJSONArray("menuPrompts");
		 
		for (int i = 0; i < menuPrompts.length(); i++) {
		    String prompt = menuPrompts.getString(i);

		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		            "Prompt : " + prompt,
		            mySession);
			mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_PROMPT_FULL_URL).setValue(prompt);
		}
		
		// ✅ Fetch NoINPUT Prompt
				String noInputPrompt = menuDetails.optString("noInputPrompt", "");
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
				        "NoINPUT Prompt Fetch from Json : " + noInputPrompt,
				        mySession);

				mySession.getVariableField(IProjectVariables.RETRY,IProjectVariables.RETRY_FIELD_NOINPUT).setValue(noInputPrompt);
				String NOINPUT = mySession.getVariableField(IProjectVariables.RETRY,IProjectVariables.RETRY_FIELD_NOINPUT).getStringValue();
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
				        "NOINPUT PROMPT SET : " + NOINPUT,
				        mySession);
		
		
		String noMatchPrompt = menuDetails.optString("noMatchPrompt", "");
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		        "NoMatch Prompt Fetch from Json : " + noMatchPrompt,
		        mySession);

		mySession.getVariableField(IProjectVariables.RETRY,IProjectVariables.RETRY_FIELD_NOMATCH).setValue(noMatchPrompt);
		String NOMATCH = mySession.getVariableField(IProjectVariables.RETRY,IProjectVariables.RETRY_FIELD_NOMATCH).getStringValue();
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		        "NOMATCH PROMPT SET : " + NOMATCH,
		        mySession);
		
		// ✅ Fetch MaxTries Prompt
		String maxTriesPrompt = menuDetails.optString("maxTriesPrompt", "");
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		        "MaxTries Prompt : " + maxTriesPrompt,
		        mySession);

		mySession.getVariableField(IProjectVariables.RETRY,IProjectVariables.RETRY_FIELD_MAX).setValue(maxTriesPrompt);
		String MAX = mySession.getVariableField(IProjectVariables.RETRY,IProjectVariables.RETRY_FIELD_MAX).getStringValue();
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		        "NOMATCH PROMPT SET : " + MAX,
		        mySession);
	}
	
}
