package flow;

import java.util.ArrayList;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-07  06:24:05 PM
 */
public class BankingServivesLogic extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-07  06:24:05 PM
	 */
	public BankingServivesLogic() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("DynamicNextNode", "Default");
		next.setDebugId(48);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
	    super.requestBegin(mySession);

	    try {
	        
	        int savingsCount = mySession.getVariableField(IProjectVariables.ACC_COUNT,IProjectVariables.ACC_COUNT_FIELD_SAV).getIntValue();
	        int currentCount = mySession.getVariableField(IProjectVariables.ACC_COUNT,IProjectVariables.ACC_COUNT_FIELD_CUR).getIntValue();
	        int dtmf = mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_SAV_NCUR_MENU_DTMF).getIntValue();
			String NodeName = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
	    	
		    

	        int totalAccounts = savingsCount + currentCount;

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO," SAV : " + savingsCount +" CUR : " + currentCount +" DTMF : " + dtmf,mySession);
	        
	        String firstNextNode = "NA";
	        

	        /* =====================================================
	         * BANKING_SERVICES
	         * ===================================================== */
        	String NextNode = "";
			if ("BANKING_SERVICES".equalsIgnoreCase(NodeName)) {
	        	JSONObject nodeDetails = IVRFlow.getNodeByDescription(NodeName);
	        	JSONArray parentNextNodes = nodeDetails.getJSONArray("nextNode");
	        	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= BANKING_SERVICES =============",mySession);
	        	// Next Node
	        	if (parentNextNodes != null && parentNextNodes.length() > 0) {
	        	    for (int i = 0; i < parentNextNodes.length(); i++) {
	        	    	
	        	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Next Node [" + i + "] : " + parentNextNodes.getString(i),mySession);
	        	    }
	        	} else {
	        	    TraceInfo.trace(
	        	        ITraceInfo.TRACE_LEVEL_INFO,"Next Node : NA",mySession
	        	    );
	        	}
	        	
	            if (totalAccounts == 0) {
	            	NextNode = parentNextNodes.getString(1);
	            	 processNode(NextNode, 1 ,mySession);
	            	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= NO_ACCOUNT_FOUND =============",mySession);
		
	            	
	            } else if (totalAccounts == 1) {
	            	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= HAS_ONE_ACCOUNT_ONLY =============",mySession);
	            	NextNode = parentNextNodes.getString(2);
	            	String ANY_NODE = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
	            	if (savingsCount ==1 ) {
	            		processNode(NextNode,0, mySession);
	            	}else if (currentCount == 1) {
	            		processNode(NextNode,1, mySession);
	            	}
	        	} else {
	            	
	            	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= CHECK_CUR_OR_SAV =============",mySession);
	            	NextNode = parentNextNodes.getString(0);
	            	if(savingsCount > 1 && currentCount == 0) {
	            		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= HAS_ONLY_SAV =============",mySession);
	            		mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_SAV_NCUR_MENU_DTMF).setValue(1);
	            		processNode(NextNode,0, mySession);
	            	}else if(savingsCount == 0 && currentCount > 1) {
	            		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= HAS_ONLY_CUR =============",mySession);
	            		mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_SAV_NCUR_MENU_DTMF).setValue(2);
	            		processNode(NextNode,0, mySession);
	            	}else if(savingsCount > 0 && currentCount > 0) {
	            		processNode(NextNode,1, mySession);
	            	}		            	
	            }
			}
	            String ANY_NODE = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NODE NAME : "+ ANY_NODE,mySession);
	            
	            
	            
	            if(ANY_NODE.equalsIgnoreCase("HAS_ONLY_SAV")) {
	            	processNode(ANY_NODE,0, mySession);
	            }else if(ANY_NODE.equalsIgnoreCase("HAS_ONLY_CUR")) {
	            	processNode(ANY_NODE,0, mySession);
	            }else if(ANY_NODE.equalsIgnoreCase("SAV_OR_CUR_MENU")) {
	            	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= SAV_OR_CUR_MENU - EXECUTED  =============",mySession);
	            	processNode(ANY_NODE,0, mySession);
	            }else if (ANY_NODE.equalsIgnoreCase("CHK_SINGLE_OR_MULTI_ACC")){
	            	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= CHK_SINGLE_OR_MULTI_ACC - EXECUTED  =============",mySession);
	            	if(dtmf == 1) {
	            		if(savingsCount == 1) {
	            			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= AFTER_MENU_HAS_1_SAV =============",mySession);
	            			processNode(ANY_NODE,1, mySession);
	            			String NEXT_NODE = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
	            			processNode(NEXT_NODE,0, mySession);
	            		}else {
	            			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= AFTER_MENU_HAS_MULTI_CUR_OR_SAV =============",mySession);
	            			processNode(ANY_NODE,0, mySession);
	            			String NEXT_NODE = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
	            			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NEXT NODE : *"+NEXT_NODE,mySession);
	            			processNode(NEXT_NODE,0, mySession);
	            		}
	            	}else if(dtmf == 2) {
	            		if(currentCount == 1) {
	            			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= AFTER_MENU_HAS_1_CUR =============",mySession);
	            			processNode(ANY_NODE,1, mySession);
	            			String NEXT_NODE = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
	            			processNode(NEXT_NODE,0, mySession);
	            		}else {
	            			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= AFTER_MENU_HAS_MULTI_CUR_OR_SAV =============",mySession);
	            			processNode(ANY_NODE,0, mySession);
	            			String NEXT_NODE = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
	            			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NEXT NODE : *"+NEXT_NODE,mySession);
	            			processNode(NEXT_NODE,0, mySession);	            		}
	            	}
	            }else {
	            	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= ELSE - EXECUTED  =============",mySession);
	            	processNode(ANY_NODE,0, mySession);
	            }
	            
	    }
	            
      catch (Exception e) {
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                "requestBegin Error: " + e.getMessage(), mySession);
            }
	}
	private void processNode(String nodeDescription,int NextNode, SCESession mySession) throws Exception {

	    // ================================
	    // FETCH NODE JSON
	    // ================================
	    JSONObject nodeDetails = IVRFlow.getNodeByDescription(nodeDescription);

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NODE JSON DETAILS : " + nodeDetails.toString(), mySession);
	    
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= NODE DETAILS START =============",mySession);

	    // ================================
	    // NODE NAME (DESCRIPTION)
	    // ================================
	    String nodeName = nodeDetails.getString("Description");
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NODE NAME : " + nodeName, mySession);
	    mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DESCRIPTION).setValue(nodeName);

	    // ================================
	    // NODE ID
	    // ================================
	    String nodeId = nodeDetails.getString("ID");

	    mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_ID).setValue(nodeId);

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NODE TYPE : " + nodeId,mySession);

	    // ================================
	    // MENU PROMPTS
	    // ================================
	    JSONArray menuPrompts = nodeDetails.getJSONArray("menuPrompts");
	    int promptCount = menuPrompts.length();

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"MENU PROMPT COUNT : " + promptCount,mySession);

	    mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_PROMPT_COUNT).setValue(promptCount);

	    for (int i = 0; i < promptCount; i++) {

	        String prompt = menuPrompts.getString(i);
	        String promptKey = "Prompt_" + (i + 1);

	        mySession.getVariableField(IProjectVariables.PROMPT_URL,promptKey).setValue(prompt);

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,promptKey + " : " + prompt,mySession);
	    }

	    // ================================
	    // MENU DTMF (ONLY FOR MENU NODES)
	    // ================================
	    if (nodeId.toUpperCase().startsWith("MEN")) {

	        JSONArray menuDTMFArray = nodeDetails.getJSONArray("menuDTMF");
	        int maxDTMF = 0;

	        for (int i = 0; i < menuDTMFArray.length(); i++) {
	            int value = Integer.parseInt(menuDTMFArray.getString(i));
	            maxDTMF = Math.max(maxDTMF, value);
	        }

	        mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DTMF).setValue(maxDTMF);

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"MENU DTMF : " + maxDTMF,mySession);
	    }
	    

	 // ================================
	 // NEXT NODE HANDLING
	 // ================================
		 JSONArray nextNodeArray = nodeDetails.optJSONArray("nextNode");
		 String nextNodeToUse = null;

		 if (nextNodeArray != null && nextNodeArray.length() > 0) {

		     if (NextNode >= 0 && NextNode < nextNodeArray.length()) {

		         nextNodeToUse = nextNodeArray.getString(NextNode);

		     } else {

		         TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
		                 "Invalid NextNode index: " + NextNode +
		                 " Array Size: " + nextNodeArray.length(),
		                 mySession);

		         // fallback to first element
		         nextNodeToUse = nextNodeArray.getString(0);
		     }

		 } else if (nodeDetails.has("nextNode")) {

		     nextNodeToUse = nodeDetails.getString("nextNode");
		 }
		 TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NEXT NODE TO USE : " + nextNodeToUse,mySession);
		 mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).setValue(nextNodeToUse);
	}
}
