package flow;

import java.util.Collection;

import com.avaya.sce.runtime.Goto;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2026-FEB-07  06:24:05 PM
 */
public class DynamicNextNode extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-07  06:24:05 PM
	 */
	public DynamicNextNode() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Experienve Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2026-FEB-07  06:24:05 PM
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {

		// TODO: Add your code here!

	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("End", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
	@Override
	public void updateBranches(Collection branches, SCESession mySession) {

	    Goto aGoto = null;

	    try {
	        String nodeType = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_ID).getStringValue();
	        
	        String Description = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DESCRIPTION).getStringValue();

	        String nextNode = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
	        
	        boolean anPlayed = mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_AN_PLAYED).getBooleanValue();

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"ROUTING | NODE_TYPE : " + nodeType + " NEXT_NODE : " + nextNode+" NODE DESCRIPTION : "+Description,mySession);

	        
	        
	    	// 2️⃣ Get existing menu description
	    	String existingDesc = mySession.getVariableField(
	    	        IProjectVariables.CALL_HISTORY,
	    	        IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).getStringValue();

	    	if(existingDesc == null){
	    	    existingDesc = "";
	    	}

	    	// 3️⃣ Append to MENU_DESCRIPTION only if valid
	    	if(Description != null) {

	    	    // Remove unwanted pipes and spaces
	    	    Description = Description.replace("|", "").trim();

	    	    if(!Description.isEmpty()) {

	    	        if(existingDesc.endsWith("|")) {
	    	            existingDesc = existingDesc + Description + "|";
	    	        } else if(existingDesc.isEmpty()) {
	    	            existingDesc = Description + "|";
	    	        } else {
	    	            existingDesc = existingDesc + "|" + Description + "|";
	    	        }

	    	        mySession.getVariableField(
	    	                IProjectVariables.CALL_HISTORY,
	    	                IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION)
	    	                .setValue(existingDesc);
	    	    }
	    	}

	    	// 4️⃣ Set EXIT_LOCATION to the last node — overwrite every time
	    	String exitNode = mySession.getVariableField(
	    	        IProjectVariables.NODE_DETAILS,
	    	        IProjectVariables.NODE_DETAILS_FIELD_ID).getStringValue();

	    	// Directly overwrite, no append
	    	if(exitNode != null && !exitNode.trim().isEmpty()) {
	    	    mySession.getVariableField(
	    	            IProjectVariables.CALL_HISTORY,
	    	            IProjectVariables.CALL_HISTORY_FIELD_EXIT_LOCATION)
	    	            .setValue(Description);
	    	}
	    	
	    	
	    	String dis =  mySession.getVariableField(
	    	            IProjectVariables.CALL_HISTORY,
	    	            IProjectVariables.CALL_HISTORY_FIELD_DISPOSITION_TYPE)
	    	            .getStringValue();
	    	
	    	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
                    "MENUDESCRIPTION " + existingDesc, mySession);
	    	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
                    "Dispostion type " + dis, mySession);
	    	
	    	
	        /* =========================
	         * ANNOUNCEMENT
	         * ========================= */
	        if("REPEAT_MENU".equalsIgnoreCase(Description)) {
	        	mySession.setProperty("JSON","REPEAT_MENU");
	        	aGoto = new Goto("DISCONNECT", 0);
	            branches.clear();
		        branches.add(aGoto);
		        super.updateBranches(branches, mySession);
	            return;
	        }
	        if("DISCONNECT".equalsIgnoreCase(nextNode) && !anPlayed) {
	            aGoto = new Goto("ANN", 0);
	            mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_AN_PLAYED).setValue(true);
	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"AN PLAYED SET AS TRUE", mySession);
	        }
	        else if (nodeType.startsWith("ANN") && !anPlayed) {
	            aGoto = new Goto("ANN", 0);
	        }
	        else {
	            aGoto = new Goto("End", 0);  // exit once announcement is played
	        }

	        /* =========================
	         * MENU
	         * ========================= */
	         if (nodeType.startsWith("MEN")) {
	            aGoto = new Goto("MEN", 0);
	        }

	        /* =========================
	         * DYNAMIC MENU (ACC LIST)
	         * ========================= */
	        else if (nodeType.startsWith("DY")) {
	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                    "Routing to Dynamic Account List Menu", mySession);

	            mySession.getVariableField(
	                    IProjectVariables.FLAG,
	                    IProjectVariables.FLAG_FIELD_ACCOUNT_MENU_FLAG
	            ).setValue(true);

	            aGoto = new Goto("DYMEN", 0);
	        }

	        if (aGoto != null) {
	            branches.clear();
	            branches.add(aGoto);
	            super.updateBranches(branches, mySession);
	            return;
	        }

	    } catch (Exception e) {
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                "updateBranches Error: " + e.getMessage(), mySession);

	        aGoto = new Goto("SetTechDiffPrompt", 0);
	        branches.clear();
	        branches.add(aGoto);
	    }

	    super.updateBranches(branches, mySession);
	}

}
