package flow;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.avaya.sce.runtime.Choice;
import com.avaya.sce.runtime.Format;
import com.avaya.sce.runtime.PhraseVariableElement;
import com.avaya.sce.runtime.Prompt;
import com.avaya.sce.runtime.PromptElement;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

/**
 * Class that represents a menu.  A menu can contain prompts, choices and links
 * as well as handlers for various events that may occur while the menu is executing
 * Last generated by Orchestration Designer at: 2026-FEB-09  08:38:47 PM
 */
public class DynamicMenu extends com.avaya.sce.runtime.Menu {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-09  08:38:47 PM
	 */
	public DynamicMenu() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the links for the node, override:
	 *     void updateLinks(Collection links, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 * @return a collection of links
	 */
	public java.util.Collection getLinks(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Link link;
		java.util.List list;
		java.util.Collection grammarInfo = null;
		java.util.Collection<com.avaya.sce.runtime.CaptureExpression> captureExpr = null;
		// This item does not have any defined links
		list = new java.util.ArrayList();
		String ___tempGrammarName = null;

		return(list);
	}
	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the properties for the node, override:
	 *     void updateProperties(Collection properties, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 * @return a collection of properties
	 */
	public java.util.Collection getProperties(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Property property;
		java.util.List list;
		// This item does not have any defined properties
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the event handlers for the node, override:
	 *    void updateEvents(Collection events, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 * @return a collection of Events
	 */
	public java.util.Collection getEvents(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list;
		com.avaya.sce.runtime.Event event;
		list = new java.util.ArrayList(2);
		java.util.List eventPromptNames = null;
		String ___tempPromptName = null;

		// Item has no prompts associated
		eventPromptNames = new java.util.ArrayList();

		event = new com.avaya.sce.runtime.Event(com.avaya.sce.runtimecommon.SCERT.EVENT_NOINPUT, (com.avaya.sce.runtime.PromptRefInfo[])eventPromptNames.toArray(new com.avaya.sce.runtime.PromptRefInfo[0]), new com.avaya.sce.runtime.Goto("DynamicMenuRetry", 0, true, ""));
		list.add(event);

		// Item has no prompts associated
		eventPromptNames = new java.util.ArrayList();

		event = new com.avaya.sce.runtime.Event(com.avaya.sce.runtimecommon.SCERT.EVENT_NOMATCH, (com.avaya.sce.runtime.PromptRefInfo[])eventPromptNames.toArray(new com.avaya.sce.runtime.PromptRefInfo[0]), new com.avaya.sce.runtime.Goto("DynamicMenuRetry", 0, true, ""));
		list.add(event);
		return(list);
	}
	/**
	 * Builds the list of choices for the menu.  This list is built
	 * automatically by the code generator and should not be edited
	 * manually.  Future code generation may overwrite any changes
	 * to this method.<br>
	 * To modify the list of choices, override:<br>
	 *    updateChoices(Collection choices, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public java.util.Collection getChoices(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Choice choice = null;
		java.util.Collection grammarInfo = null;
		list = new java.util.ArrayList(1);
		String ___tempGrammarName = null;

		// build the list of grammar information objects for the choice
		grammarInfo = new java.util.ArrayList();


		choice = new com.avaya.sce.runtime.Choice("", "#90*", true, "exact", "ExitAccListMenu", grammarInfo, true);
		list.add(choice);

		return(list);
	}
	/**
	 * Builds the list of prompts that are used by this flow item<br>
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of prompts for the flow item, override:
	 *     updatePrompts(Collection prompts, SCESession mySession)
	 * @return list of prompts for the menu
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public java.util.Collection getPrompts(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		String ___tempPromptName = null;
		// Item has no prompts associated
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * Builds the list of tracking items that are generated by this flow item<br>
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 * @return list of tracking items for the item
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public java.util.Collection getTrackingActions(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;

		// Item has no tracking items.
		list = new java.util.ArrayList();
		return(list);
	}
	@Override
	public void requestBegin(SCESession mySession) {
	    super.requestBegin(mySession);

	    String DTMF = mySession.getVariableField(
	            IProjectVariables.DYNAMIC_MENU,
	            IProjectVariables.DYNAMIC_MENU_FIELD_VALUE
	    ).getStringValue();

	    if (DTMF == null) {
	        DTMF = "";
	    }

	    DTMF = DTMF.trim();

	    // 🔥 IGNORE FIRST ENTRY (NO INPUT YET)
	    if (DTMF.isEmpty()) {
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "First entry into menu. No DTMF yet.",
	                mySession);
	        return;
	    }

	    // 🔥 CLEAR DTMF AFTER PROCESSING
	    mySession.getVariableField(
	            IProjectVariables.DYNAMIC_MENU,
	            IProjectVariables.DYNAMIC_MENU_FIELD_VALUE
	    ).setValue("");

	    int pageIndex = 0;

	    String pageStr = mySession.getVariableField(
	            IProjectVariables.PAGE,
	            IProjectVariables.PAGE_FIELD_PAGE_INDEX
	    ).getStringValue();

	    if (pageStr != null && !pageStr.isEmpty()) {
	        pageIndex = Integer.parseInt(pageStr);
	    }

	    List<Map<String, Object>> accountList =
	            (List<Map<String, Object>>) mySession.getProperty("SAV_ACCOUNT_LIST");

	    int pageSize = mySession.getVariableField(
	            IProjectVariables.PAGE,
	            IProjectVariables.PAGE_FIELD_PAGE_SIZE
	    ).getIntValue();

	    int totalPages = (int) Math.ceil((double) accountList.size() / pageSize);

	    switch (DTMF) {

	        case "9": // NEXT
	            if (pageIndex < totalPages - 1) {
	                pageIndex++;
	            }
	            break;

	        case "7": // PREVIOUS
	            if (pageIndex > 0) {
	                pageIndex--;
	            }
	            break;

	        case "8": // REPEAT
	            break;

	        default:
	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                    "Invalid input. Staying on page: " + pageIndex,
	                    mySession);
	            break;
	    }

	    pageIndex = Math.max(0, pageIndex);
	    pageIndex = Math.min(pageIndex, totalPages - 1);

	    mySession.getVariableField(
	            IProjectVariables.PAGE,
	            IProjectVariables.PAGE_FIELD_PAGE_INDEX
	    ).setValue(pageIndex);
	}

	@Override
	public void updatePrompts(Collection prompts, SCESession mySession) {
		super.updatePrompts(prompts, mySession);
		
		Prompt p = new Prompt() {	
			@Override
			public void buildPrompt() {
				
			}
		};
		p.setSession(mySession);
		p.setOrder(Prompt.STANDARD);
		p.setTimeout(1, 8000);
		p.setBargin(1, true);
		int DTMF_Menu = mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_SAV_NCUR_MENU_DTMF).getIntValue();
		
		// Determine which account list to fetch
		List<Map<String, Object>> accountList = null;
		
		if (DTMF_Menu == 1) {
			 accountList = (List<Map<String, Object>>) mySession.getProperty("SAV_ACCOUNT_LIST");
		}else if(DTMF_Menu == 2) {
			 accountList = (List<Map<String, Object>>) mySession.getProperty("CUR_ACCOUNT_LIST");
		}
		
		int pageIndex = 0;

		String pageStr = mySession.getVariableField(
		        IProjectVariables.PAGE,
		        IProjectVariables.PAGE_FIELD_PAGE_INDEX).getStringValue();

		if (pageStr != null && !pageStr.trim().isEmpty()) {
		    try {
		        pageIndex = Integer.parseInt(pageStr);
		    } catch (Exception e) {
		        pageIndex = 0;
		    }
		}

    	int pageSize = mySession.getVariableField(IProjectVariables.PAGE, IProjectVariables.PAGE_FIELD_PAGE_SIZE).getIntValue();
    	
		int start = pageIndex * pageSize;
		int end = Math.min(start + pageSize, accountList.size());
		
			
		com.avaya.sce.runtime.Format format = new com.avaya.sce.runtime.Format();
	      format.add("format", "character");
	      format.add("inflection", "Cn");
	         
			JSONObject nodeDetails = IVRFlow.getNodeByDescription("ACC_LIST_MENU");
			JSONArray Noprompts = nodeDetails.optJSONArray("menuPrompts");

			int totalPrompts = (Noprompts != null) ? Noprompts.length() : 0;
			
			String Audio_Path = mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_BASE_URL).getStringValue();
	        int count = 1;
	        
	        for (int i = 0; i < totalPrompts; i++) {

	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"For Loop Count : " + i, mySession);

	            String prompt = Noprompts.getString(i);

	            if ("NEXT_OPTIONS.wav".equalsIgnoreCase(prompt)) {

	                mySession.getVariableField(
	                    IProjectVariables.MENU_OPTIONS,
	                    IProjectVariables.MENU_OPTIONS_FIELD_NEXT_OPTION
	                ).setValue(Audio_Path + prompt);
	                TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Next Node has been completed"+ Audio_Path + prompt, mySession);

	            } else if ("REPEAT_OPTION.wav".equalsIgnoreCase(prompt)) {

	                mySession.getVariableField(
	                    IProjectVariables.MENU_OPTIONS,
	                    IProjectVariables.MENU_OPTIONS_FIELD_REPEAT_OPTION
	                ).setValue(Audio_Path + prompt);

	            } else if ("PREVIOUS_OPTIONS.wav".equalsIgnoreCase(prompt)) {

	                mySession.getVariableField(
	                    IProjectVariables.MENU_OPTIONS,
	                    IProjectVariables.MENU_OPTIONS_FIELD_PREVIOUS_OPTION
	                ).setValue(Audio_Path + prompt);

	            } else {
	                // ACC_ENDING_WITH.wav, PRESS.wav
	                String setPrompt = "Prompt_" + (i + 1);

	                mySession.getVariableField(
	                    IProjectVariables.PROMPT_URL,
	                    setPrompt
	                ).setValue(Audio_Path + prompt);
	            }
	        }
		
	        String AccountNumber ="";
	        String balance = "";
		
		for (int i = start; i < end; i++) {
			 
            Map<String, Object> acc = accountList.get(i);
			
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,". Last 4 Acc: " + acc.get("last4Acc") + " | Balance: " + acc.get("balance"),mySession);
				int pressCount = i - start + 1;
			
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "Press Count "+pressCount, mySession);

			AccountNumber = (String) acc.get("last4Acc");
			balance = (String) acc.get("balance");
			
		   
		    mySession.getVariableField(IProjectVariables.ACCOUNT_LIST, "AccountNumber_" + pressCount).setValue(AccountNumber);
		    mySession.getVariableField(IProjectVariables.ACCOUNT_LIST, "presscount_" + pressCount).setValue(pressCount);
		    
			    
			 p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("PromptURL:Prompt_1", com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL));
			 p.add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"AccountList:" + "AccountNumber_" + pressCount, format,false));
			 p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("PromptURL:Prompt_2", com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL));
			 p.add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"AccountList:" + "presscount_" + pressCount, format,false));
		 
		}
		
		if (pageIndex > 0) {
			String PreviousPrompt= mySession.getVariableField(IProjectVariables.MENU_OPTIONS,IProjectVariables.MENU_OPTIONS_FIELD_PREVIOUS_OPTION).getStringValue();
			 mySession.getVariableField(IProjectVariables.MENU_OPTIONS,IProjectVariables.MENU_OPTIONS_FIELD_PREVIOUS_OPTION).setValue(PreviousPrompt);
			 p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("MenuOptions:PreviousOption", com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL));
		}
		
		
		String RepeatPrompt= mySession.getVariableField(IProjectVariables.MENU_OPTIONS,IProjectVariables.MENU_OPTIONS_FIELD_REPEAT_OPTION).getStringValue();
		mySession.getVariableField(IProjectVariables.MENU_OPTIONS,IProjectVariables.MENU_OPTIONS_FIELD_REPEAT_OPTION).setValue(RepeatPrompt);
		 p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("MenuOptions:RepeatOption", com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL));
		
		int totalPages = (int) Math.ceil((double) accountList.size() / pageSize);
		boolean hasNextPage = (pageIndex + 1) * pageSize < accountList.size();
		
		if (hasNextPage) {
			 TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Check :"+start+"<"+accountList.size(), mySession);
			 
			 p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("MenuOptions:NextOption", com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL));
		}	 
		 prompts.add(p);
	}
	@Override
	public void updateChoices(Collection choices, SCESession mySession) {
	    super.updateChoices(choices, mySession);

	    Collection grammarInfo = new ArrayList();

	    int DTMF_Menu = mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_SAV_NCUR_MENU_DTMF).getIntValue();

	    // Determine which account list to fetch
	    List<Map<String, Object>> accountList = null;

	    if (DTMF_Menu == 1) {
	        accountList = (List<Map<String, Object>>) mySession.getProperty("SAV_ACCOUNT_LIST");
	    } else if (DTMF_Menu == 2) {
	        accountList = (List<Map<String, Object>>) mySession.getProperty("CUR_ACCOUNT_LIST");
	    }

	    // Safety check
	    if (accountList == null || accountList.isEmpty()) {
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                "Account list is NULL or EMPTY", mySession);
	        return;
	    }

	    int pageIndex = mySession
	            .getVariableField(
	                IProjectVariables.PAGE,
	                IProjectVariables.PAGE_FIELD_PAGE_INDEX
	            ).getIntValue();

	    int pageSize = mySession
	            .getVariableField(
	                IProjectVariables.PAGE,
	                IProjectVariables.PAGE_FIELD_PAGE_SIZE
	            ).getIntValue();

	    int start = pageIndex * pageSize;
	    int end = Math.min(start + pageSize, accountList.size());

	    // ===== Account choices (1..N) =====
	    for (int i = start, dtmf = 1; i < end; i++, dtmf++) {
	        Choice accChoice = new Choice(
	                "DynamicMenu",
	                String.valueOf(dtmf),
	                true,
	                "exact",
	                "ExitAccListMenu",
	                grammarInfo,
	                true
	        );
	        choices.add(accChoice);
	    }

	    // ===== Previous page (7) =====
	    if (pageIndex > 0) {
	        choices.add(new Choice(
	                "PrevoiusOption",
	                "6",
	                true,
	                "exact",
	                "DynamicMenu",
	                grammarInfo,
	                true
	        ));
	    }

	    // ===== Repeat (8) =====
	    choices.add(new Choice(
	            "RepeatOption",
	            "*",
	            true,
	            "exact",
	            "DynamicMenu",
	            grammarInfo,
	            true
	    ));

	    // ===== Next page (9) =====
	    boolean hasNextPage = (pageIndex + 1) * pageSize < accountList.size();
	    if (hasNextPage) {
	        choices.add(new Choice(
	                "NextOption",
	                "5",
	                true,
	                "exact",
	                "DynamicMenu",
	                grammarInfo,
	                true
	        ));
	    }
	}



}
