package flow;

import java.util.List;
import java.util.Map;

import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-09  03:25:56 PM
 */
public class ExitAccListMenu extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-09  03:25:56 PM
	 */
	public ExitAccListMenu() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("BankingServivesLogic", "Default");
		next.setDebugId(127);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
	    super.requestBegin(mySession);

	    String dtmf = mySession.getVariableField(
	            IProjectVariables.DYNAMIC_MENU,
	            IProjectVariables.DYNAMIC_MENU_FIELD_VALUE
	    ).getStringValue();

	    int pageIndex = mySession.getVariableField(
	            IProjectVariables.PAGE,
	            IProjectVariables.PAGE_FIELD_PAGE_INDEX
	    ).getIntValue();

	    int pageSize = mySession.getVariableField(
	            IProjectVariables.PAGE,
	            IProjectVariables.PAGE_FIELD_PAGE_SIZE
	    ).getIntValue();

	    int pressCount = Integer.parseInt(dtmf);   // 1..4

	    // Convert page-relative selection → absolute index
	    int selectedIndex = (pageIndex * pageSize) + (pressCount - 1);

	    int menuType = mySession.getVariableField(
	            IProjectVariables.FLAG,
	            IProjectVariables.FLAG_FIELD_SAV_NCUR_MENU_DTMF
	    ).getIntValue();

	    List<Map<String, Object>> accountList;

	    if (menuType == 1) {
	        accountList = (List<Map<String, Object>>) mySession.getProperty("SAV_ACCOUNT_LIST");
	    } else {
	        accountList = (List<Map<String, Object>>) mySession.getProperty("CUR_ACCOUNT_LIST");
	    }

	    Map<String, Object> selectedAcc = accountList.get(selectedIndex);

	    String last4 = (String) selectedAcc.get("last4Acc");
	    String balance = String.valueOf(selectedAcc.get("balance"));

	    // Store for next nodes
	    mySession.setProperty("SELECTED_LAST4_ACC", last4);
	    mySession.setProperty("SELECTED_BALANCE", balance);

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "SELECTED ACCOUNT → Last4: " + last4 + " Balance: " + balance, mySession);
    	mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,IProjectVariables.ACCOUNT_DETAILS_FIELD_ACCOUNT_NUMBER).setValue(last4);
    	 mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,IProjectVariables.ACCOUNT_DETAILS_FIELD_BALANCE).setValue(balance);
	    
	}

}
