package flow;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.servlet.ServletContext;

import com.HostJar.API.api;
import com.HostJar.Flow.IVRFlow;
import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import DTO.AccountListResponse;
import DTO.AccountListResponse.Account;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-07  03:24:30 PM
 */
public class GetAccountList extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-07  03:24:30 PM
	 */
	public GetAccountList() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("BankingServivesLogic", "Default");
		next.setDebugId(8);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
	    super.requestBegin(mySession);   
	    try {

	        ServletContext context = mySession.getServlet().getServletContext();

	        // Fetch the context-param value
	        String propertyFilePath = context.getInitParameter("PropertyFile");

	        // Log it
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "Property File Path: " + propertyFilePath, mySession);
	        Load.getInstance().loadConfig(propertyFilePath);
	    	
	        String baseURL = (String) mySession.getProperty("BASE_URL");  
	        mySession.getVariableField(IProjectVariables.PROMPT_URL,
	                IProjectVariables.PROMPT_URL_FIELD_BASE_URL)
	                .setValue(baseURL);

	        List<Map<String, Object>> savAccounts = new ArrayList<>();
	        List<Map<String, Object>> curAccounts = new ArrayList<>();

	        String savAccNo = null;
	        String savBalance = null;

	        String curAccNo = null;
	        String curBalance = null;

	        LocalDateTime currentTime = LocalDateTime.now();
	        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
	        String requesttime = currentTime.format(formatter);

	        String UCID = mySession.getVariableField(
	                IProjectVariables.SESSION,
	                IProjectVariables.SESSION_FIELD_UCID).getStringValue();
	        
	        String  Rel_ID=  (String) mySession.getProperty("RelationshipID");
	        
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "REL_ID : " + Rel_ID, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "AUDIO URL : " + baseURL, mySession);

	        AccountListResponse Response = api.AccountList(UCID,Rel_ID, requesttime);

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "ACCOUNT API Response : " + Response, mySession);

	        String responseCode = Response.getResponseCode();

	        if ("0000".equalsIgnoreCase(responseCode)) {

	            List<Account> accountsArray =
	                    Response.getData() != null ? Response.getData().getAccounts() : null;

	            String pcSav = Load.getInstance().getProperty("PC_SAV");
	            String pcCur = Load.getInstance().getProperty("PC_CUR");

	            Set<String> savingsProductCodes = new HashSet<>();
	            Set<String> currentProductCodes = new HashSet<>();

	            for (String s : pcSav.split(",")) {
	                savingsProductCodes.add(s.trim().toUpperCase());
	                TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                        "CONFIG PC_SAV : " + s.trim().toUpperCase(), mySession);
	            }

	            for (String s : pcCur.split(",")) {
	                currentProductCodes.add(s.trim().toUpperCase());
	                TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                        "CONFIG PC_CUR : " + s.trim().toUpperCase(), mySession);
	            }
	            mySession.setProperty("2FA_FLAG", true);
	            int savingsCount = 0;
	            int currentCount = 0;

	            if (accountsArray != null) {

	                for (Account account : accountsArray) {

	                    String accountType = account.getAccountType();
	                    String productCode = account.getProductCode().toUpperCase();
	                    String isActive = account.getIsActive();

	                    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                            "Account Number: " + account.getAccountNumber() +
	                                    " | Type: " + accountType +
	                                    " | Balance: " + account.getBalance() +
	                                    " | Active: " + isActive +
	                                    " | ProductCode: " + productCode,
	                            mySession);

	                    String accNo = account.getAccountNumber();
	                    String balance = String.valueOf(account.getBalance());

	                    String last4Acc = accNo != null && accNo.length() >= 4
	                            ? accNo.substring(accNo.length() - 4)
	                            : accNo;

	                    Map<String, Object> accountMap = new HashMap<>();
	                    accountMap.put("last4Acc", last4Acc);
	                    accountMap.put("balance", balance);

	                    if ("Y".equalsIgnoreCase(isActive)) {

	                        if ("SAVINGS".equalsIgnoreCase(accountType)
	                                && savingsProductCodes.contains(productCode)) {

	                            savingsCount++;
	                            savAccNo = accNo;
	                            savBalance = balance;
	                            savAccounts.add(accountMap);

	                        } else if ("CURRENT".equalsIgnoreCase(accountType)
	                                && currentProductCodes.contains(productCode)) {

	                            currentCount++;
	                            curAccNo = accNo;
	                            curBalance = balance;
	                            curAccounts.add(accountMap);
	                        }
	                    }
	                }
	            }

	            mySession.setProperty("SAV_ACCOUNT_LIST", savAccounts);
	            mySession.setProperty("CUR_ACCOUNT_LIST", curAccounts);

	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                    "Total Active Savings Accounts matching PC_SAV: " + savingsCount, mySession);
	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                    "Total Active Current Accounts matching PC_CUR: " + currentCount, mySession);

	            mySession.getVariableField(IProjectVariables.ACC_COUNT,
	                    IProjectVariables.ACC_COUNT_FIELD_SAV).setValue(savingsCount);

	            mySession.getVariableField(IProjectVariables.ACC_COUNT,
	                    IProjectVariables.ACC_COUNT_FIELD_CUR).setValue(currentCount);

	            // FIXED checks
	            if (accountsArray == null || accountsArray.isEmpty()) {

	                TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                        "******** NO ACCOUNT FOUND FOR THE CUSTOMER ********", mySession);

	                mySession.getVariableField(IProjectVariables.FLAG,
	                        IProjectVariables.FLAG_FIELD_ACCOUNT_STATUS_FLAG).setValue(true);

	            } else if (accountsArray.size() == 1) {

	                TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                        "******** CUSTOMER HAS ONLY ONE ACCOUNT ********", mySession);

	                Account account = accountsArray.get(0);

	                String accountType = account.getAccountType();
	                String isActive = account.getIsActive();
	                String productCode = account.getProductCode();

	                if ("Y".equalsIgnoreCase(isActive)) {

	                    boolean isSavings =
	                            "SAVINGS".equalsIgnoreCase(accountType)
	                                    && savingsProductCodes.contains(productCode.toUpperCase());

	                    boolean isCurrent =
	                            "CURRENT".equalsIgnoreCase(accountType)
	                                    && currentProductCodes.contains(productCode.toUpperCase());

	                    if (isSavings) {

	                        mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
	                                IProjectVariables.ACCOUNT_DETAILS_FIELD_SAV_ACC_NUMBER)
	                                .setValue(savAccNo);

	                        mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
	                                IProjectVariables.ACCOUNT_DETAILS_FIELD_SAV_BALANCE)
	                                .setValue(savBalance);

	                        mySession.getVariableField(IProjectVariables.FLAG,
	                                IProjectVariables.FLAG_FIELD_SAVING_ACC).setValue(true);

	                    } else if (isCurrent) {

	                        mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
	                                IProjectVariables.ACCOUNT_DETAILS_FIELD_CUR_ACC_NUMBER)
	                                .setValue(curAccNo);

	                        mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
	                                IProjectVariables.ACCOUNT_DETAILS_FIELD_CUR_BALANCE)
	                                .setValue(curBalance);

	                        mySession.getVariableField(IProjectVariables.FLAG,
	                                IProjectVariables.FLAG_FIELD_CURRENT_ACC).setValue(true);
	                    }
	                }

	            } else if (savingsCount > 2 && currentCount > 2) {

	                mySession.getVariableField(IProjectVariables.FLAG,
	                        IProjectVariables.FLAG_FIELD_MULI_ACC).setValue(true);

	            } else if (savingsCount > 1 && currentCount == 1) {

	                mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
	                        IProjectVariables.ACCOUNT_DETAILS_FIELD_CUR_ACC_NUMBER)
	                        .setValue(curAccNo);

	                mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
	                        IProjectVariables.ACCOUNT_DETAILS_FIELD_CUR_BALANCE)
	                        .setValue(curBalance);

	                mySession.getVariableField(IProjectVariables.FLAG,
	                        IProjectVariables.FLAG_FIELD_CHECK_ACC_STAUS).setValue(true);

	            } else if (currentCount > 1 && savingsCount == 1) {

	                mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
	                        IProjectVariables.ACCOUNT_DETAILS_FIELD_SAV_ACC_NUMBER)
	                        .setValue(savAccNo);

	                mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
	                        IProjectVariables.ACCOUNT_DETAILS_FIELD_SAV_BALANCE)
	                        .setValue(savBalance);

	                mySession.getVariableField(IProjectVariables.FLAG,
	                        IProjectVariables.FLAG_FIELD_CHECK_ACC_STAUS).setValue(true);

	            } else if (savingsCount == 1 && currentCount == 1) {

	                mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
	                        IProjectVariables.ACCOUNT_DETAILS_FIELD_CUR_ACC_NUMBER)
	                        .setValue(curAccNo);

	                mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
	                        IProjectVariables.ACCOUNT_DETAILS_FIELD_CUR_BALANCE)
	                        .setValue(curBalance);

	                mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
	                        IProjectVariables.ACCOUNT_DETAILS_FIELD_SAV_ACC_NUMBER)
	                        .setValue(savAccNo);

	                mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
	                        IProjectVariables.ACCOUNT_DETAILS_FIELD_SAV_BALANCE)
	                        .setValue(savBalance);

	                mySession.getVariableField(IProjectVariables.FLAG,
	                        IProjectVariables.FLAG_FIELD_CHECK_ACC_STAUS).setValue(true);

	            } else if (savingsCount > 1 && currentCount == 0) {

	                mySession.getVariableField(IProjectVariables.FLAG,
	                        IProjectVariables.FLAG_FIELD_HAVING_ONLY_SAV_ACC).setValue(true);

	            } else if (savingsCount == 0 && currentCount > 1) {

	                mySession.getVariableField(IProjectVariables.FLAG,
	                        IProjectVariables.FLAG_FIELD_HAVING_ONLY_CUR_ACC).setValue(true);
	            }
	        }

	    } catch (Exception e) {

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                "ERROR : " + e.getMessage(), mySession);
	        
	        String baseURL = mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_BASE_URL).getStringValue();
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"URL : "+baseURL,mySession);
			if (baseURL.equalsIgnoreCase("/Prompts/ENGLISH/")) {
				String VDN = IVRFlow.getTransferVDN("ENGLISH","BANKING_SERVICES");
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS ENGLISH VDN : "+VDN,mySession);
				mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRANSFER_VDN).setValue(VDN);
			}else if (baseURL.equalsIgnoreCase("/Prompts/HINDI/")) {
				String VDN = IVRFlow.getTransferVDN("HINDI","BANKING_SERVICES");
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS HINDI VDN : "+VDN,mySession);
				mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRANSFER_VDN).setValue(VDN);
			}else {
				String VDN = IVRFlow.getTransferVDN("DEFAULT","BANKING_SERVICES");
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS DEFAULT VDN : "+VDN,mySession);
				mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRANSFER_VDN).setValue(VDN);
			}
			mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_API_STATUS).setValue(true);
			
	        e.printStackTrace();
	    }
	}

}
