package flow;

/**
 * This is a special reserved class that is repsonsible for loading application 
 * variables as well as the forward to the actual first form of the application.<br>
 * This class should not be manually edited as changes may be overridden by the 
 * code generator.<br>
 * Last generated by Orchestration Designer at: 2026-FEB-07  03:22:30 PM
 */
public class Start extends com.avaya.sce.runtime.Entry {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-07  03:22:30 PM
	 */
	public Start() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method is generated automatically.  Any changes may be overwritten.
	 * Returns the submit object that will redirect application flow to the first
	 * form in the application.  This also adds various standard variables to the
	 * list of data to be submitted to the runtime variable table.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 * @return the Submit object that contains the standard variables and the first form
	 */
	public com.avaya.sce.runtime.Submit getSubmit(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Submit submit = new com.avaya.sce.runtime.Submit("GetAccountList");
		return ( submit );
	}
	/**
	 * This method initializes the SCE session with the variables that
	 * are defined in the application.<BR>
	 * 
	 * This method is generated automatically and should not be manually
	 * edited because changes may be overwritten by future code 
	 * generation.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public void initializeVariables(com.avaya.sce.runtimecommon.SCESession session) {
		com.avaya.sce.runtimecommon.IVariable variable = null;
		String[] variableFields = null;

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.BALANCE, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.ACC_COUNT_FIELD_CUR,
			IProjectVariables.ACC_COUNT_FIELD_SAV };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.ACC_COUNT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CALL_HISTORY_FIELD_DISPOSITION_TYPE,
			IProjectVariables.CALL_HISTORY_FIELD_EXIT_LOCATION,
			IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CALL_HISTORY, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.TRANSFER, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.RETRY_FIELD_MAX,
			IProjectVariables.RETRY_FIELD_NOINPUT,
			IProjectVariables.RETRY_FIELD_NOMATCH };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.RETRY, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.REDIRECTINFO_FIELD_PRESENTATIONINFO,
			IProjectVariables.REDIRECTINFO_FIELD_REASON,
			IProjectVariables.REDIRECTINFO_FIELD_SCREENINGINFO,
			IProjectVariables.REDIRECTINFO_FIELD_URI };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.REDIRECTINFO, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___1,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___1_0,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___1_1,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___1_2,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___1_3,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___1_4,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___1_5,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___2,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___3,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___4,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___5,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___6,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___7,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___8,
			IProjectVariables.ACCOUNT_LIST_FIELD_ACCOUNT_NUMBER___9,
			IProjectVariables.ACCOUNT_LIST_FIELD_PRESSCOUNT___1,
			IProjectVariables.ACCOUNT_LIST_FIELD_PRESSCOUNT___2,
			IProjectVariables.ACCOUNT_LIST_FIELD_PRESSCOUNT___3,
			IProjectVariables.ACCOUNT_LIST_FIELD_PRESSCOUNT___4,
			IProjectVariables.ACCOUNT_LIST_FIELD_PRESSCOUNT___5,
			IProjectVariables.ACCOUNT_LIST_FIELD_PRESSCOUNT___6 };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.ACCOUNT_LIST, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.PAISE, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.PROMPT_FIELD_PROMPT___1,
			IProjectVariables.PROMPT_FIELD_PROMPT___2 };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.PROMPT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DATE_FIELD_AUDIO,
			IProjectVariables.DATE_FIELD_DAYOFMONTH,
			IProjectVariables.DATE_FIELD_DAYOFWEEK,
			IProjectVariables.DATE_FIELD_DAYOFWEEKNUM,
			IProjectVariables.DATE_FIELD_DAYOFYEAR,
			IProjectVariables.DATE_FIELD_MONTH,
			IProjectVariables.DATE_FIELD_MONTHINYEAR,
			IProjectVariables.DATE_FIELD_YEAR };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DATE, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.PAGE_FIELD_PAGE_INDEX,
			IProjectVariables.PAGE_FIELD_PAGE_SIZE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.PAGE, variableFields, new String[] {"0", ""}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SAV__OR__CUR__MENU_FIELD_CONFIDENCE,
			IProjectVariables.SAV__OR__CUR__MENU_FIELD_INPUTMODE,
			IProjectVariables.SAV__OR__CUR__MENU_FIELD_INTERPRETATION,
			IProjectVariables.SAV__OR__CUR__MENU_FIELD_NOINPUTCOUNT,
			IProjectVariables.SAV__OR__CUR__MENU_FIELD_NOMATCHCOUNT,
			IProjectVariables.SAV__OR__CUR__MENU_FIELD_UTTERANCE,
			IProjectVariables.SAV__OR__CUR__MENU_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SAV__OR__CUR__MENU, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.PROMPT_URL_FIELD_BASE_URL,
			IProjectVariables.PROMPT_URL_FIELD_ENG_BASE_URL,
			IProjectVariables.PROMPT_URL_FIELD_HINDI_BASE_URL,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___1,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___1_0,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___2,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___3,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___4,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___5,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___6,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___7,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___8,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___9,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT_COUNT,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT_FULL_URL };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.PROMPT_URL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.ACCOUNT_DETAILS_FIELD_ACCOUNT_NUMBER,
			IProjectVariables.ACCOUNT_DETAILS_FIELD_BALANCE,
			IProjectVariables.ACCOUNT_DETAILS_FIELD_CUR_ACC_NUMBER,
			IProjectVariables.ACCOUNT_DETAILS_FIELD_CUR_BALANCE,
			IProjectVariables.ACCOUNT_DETAILS_FIELD_SAV_ACC_NUMBER,
			IProjectVariables.ACCOUNT_DETAILS_FIELD_SAV_BALANCE,
			IProjectVariables.ACCOUNT_DETAILS_FIELD_TYPE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.ACCOUNT_DETAILS, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.FLAG_FIELD_ACCOUNT_MENU_FLAG,
			IProjectVariables.FLAG_FIELD_ACCOUNT_STATUS_FLAG,
			IProjectVariables.FLAG_FIELD_AN_PLAYED,
			IProjectVariables.FLAG_FIELD_BALANCE_PLAYED,
			IProjectVariables.FLAG_FIELD_CHECK_ACC_STAUS,
			IProjectVariables.FLAG_FIELD_CURRENT_ACC,
			IProjectVariables.FLAG_FIELD_HAVING_ONLY_CUR_ACC,
			IProjectVariables.FLAG_FIELD_HAVING_ONLY_SAV_ACC,
			IProjectVariables.FLAG_FIELD_MULI_ACC,
			IProjectVariables.FLAG_FIELD_SAVING_ACC,
			IProjectVariables.FLAG_FIELD_SAV_NCUR_MENU_DTMF,
			IProjectVariables.FLAG_FIELD_TRANSFER_VDN,
			IProjectVariables.FLAG_FIELD_VISITED_PLAY_BALANCE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.FLAG, variableFields, new String[] {"", "false", "", "", "", "false", "false", "false", "", "false", "0", "", ""}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SESSION_FIELD_AAI,
			IProjectVariables.SESSION_FIELD_ANI,
			IProjectVariables.SESSION_FIELD_CALLTAG,
			IProjectVariables.SESSION_FIELD_CHANNEL,
			IProjectVariables.SESSION_FIELD_CHANNELTYPE,
			IProjectVariables.SESSION_FIELD_CONVERSEFIRST,
			IProjectVariables.SESSION_FIELD_CONVERSESECOND,
			IProjectVariables.SESSION_FIELD_CURRENTLANGUAGE,
			IProjectVariables.SESSION_FIELD_DNIS,
			IProjectVariables.SESSION_FIELD_EXIT_CUSTOMER_ID,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_1,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_2,
			IProjectVariables.SESSION_FIELD_EXIT_PARENT_ID,
			IProjectVariables.SESSION_FIELD_EXIT_PREFERRED_PATH,
			IProjectVariables.SESSION_FIELD_EXIT_REASON,
			IProjectVariables.SESSION_FIELD_EXIT_TOPIC,
			IProjectVariables.SESSION_FIELD_LASTERROR,
			IProjectVariables.SESSION_FIELD_MEDIATYPE,
			IProjectVariables.SESSION_FIELD_PROTOCOLNAME,
			IProjectVariables.SESSION_FIELD_PROTOCOLVERSION,
			IProjectVariables.SESSION_FIELD_SESSIONID,
			IProjectVariables.SESSION_FIELD_SESSIONLABEL,
			IProjectVariables.SESSION_FIELD_SHAREDMODE,
			IProjectVariables.SESSION_FIELD_UCID,
			IProjectVariables.SESSION_FIELD_UUI,
			IProjectVariables.SESSION_FIELD_VIDEOBITRATE,
			IProjectVariables.SESSION_FIELD_VIDEOCODEC,
			IProjectVariables.SESSION_FIELD_VIDEOENABLED,
			IProjectVariables.SESSION_FIELD_VIDEOFARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOFORMAT,
			IProjectVariables.SESSION_FIELD_VIDEOFPS,
			IProjectVariables.SESSION_FIELD_VIDEOHEIGHT,
			IProjectVariables.SESSION_FIELD_VIDEONEARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOWIDTH,
			IProjectVariables.SESSION_FIELD_VPCALLEDEXTENSION,
			IProjectVariables.SESSION_FIELD_VPCONVERSEONDATA,
			IProjectVariables.SESSION_FIELD_VPCOVERAGEREASON,
			IProjectVariables.SESSION_FIELD_VPCOVERAGETYPE,
			IProjectVariables.SESSION_FIELD_VPRDNIS,
			IProjectVariables.SESSION_FIELD_VPREPORTURL };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SESSION, variableFields, null, session, false, true );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.MENU_OPTIONS_FIELD_NEXT_OPTION,
			IProjectVariables.MENU_OPTIONS_FIELD_PREVIOUS_OPTION,
			IProjectVariables.MENU_OPTIONS_FIELD_REPEAT_OPTION };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.MENU_OPTIONS, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.VARIABLES_FIELD_EVENT_TYPE,
			IProjectVariables.VARIABLES_FIELD_EXCEED_COUNT,
			IProjectVariables.VARIABLES_FIELD_FINAL_FLAG,
			IProjectVariables.VARIABLES_FIELD_NO_AGENT,
			IProjectVariables.VARIABLES_FIELD_RETRY_COUNT,
			IProjectVariables.VARIABLES_FIELD_TRANSFER_FLAG };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.VARIABLES, variableFields, new String[] {"", "3", "", "", "0", ""}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DYNAMIC_MENU_FIELD_CONFIDENCE,
			IProjectVariables.DYNAMIC_MENU_FIELD_INPUTMODE,
			IProjectVariables.DYNAMIC_MENU_FIELD_INTERPRETATION,
			IProjectVariables.DYNAMIC_MENU_FIELD_NOINPUTCOUNT,
			IProjectVariables.DYNAMIC_MENU_FIELD_NOMATCHCOUNT,
			IProjectVariables.DYNAMIC_MENU_FIELD_UTTERANCE,
			IProjectVariables.DYNAMIC_MENU_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DYNAMIC_MENU, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.NODE_DETAILS_FIELD_API_STATUS,
			IProjectVariables.NODE_DETAILS_FIELD_DESCRIPTION,
			IProjectVariables.NODE_DETAILS_FIELD_DTMF,
			IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE,
			IProjectVariables.NODE_DETAILS_FIELD_ID,
			IProjectVariables.NODE_DETAILS_FIELD_LANGUAGE,
			IProjectVariables.NODE_DETAILS_FIELD_NEXT_NODE,
			IProjectVariables.NODE_DETAILS_FIELD_PREFERRED_LANGUAGE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.NODE_DETAILS, variableFields, new String[] {"", "", "", "BANKING_SERVICES", "", "", "", ""}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_ERRORCODE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_MESSAGE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_OBJECT,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_STACKTRACE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_TYPE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DD_LAST_EXCEPTION, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.OAUTH_FIELD_TOKEN };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.OAUTH, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.ACCOUNT_NUMBER, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TIME_FIELD_AUDIO,
			IProjectVariables.TIME_FIELD_HOUR,
			IProjectVariables.TIME_FIELD_MILLISECOND,
			IProjectVariables.TIME_FIELD_MINUTE,
			IProjectVariables.TIME_FIELD_SECOND,
			IProjectVariables.TIME_FIELD_TIMEZONE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TIME, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.API_FIELD_API_FAILED };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.API, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SHAREDUUI_FIELD_ID,
			IProjectVariables.SHAREDUUI_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SHAREDUUI, variableFields, null, session, false, false );
		session.putVariable(variable);
	}
	/**
	 * This method returns the name of the application.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public String getEntryName() {
		return("BankingServices");
	}
	/**
	 * This method returns a list of life cycle classes for Pluggable Connectors.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public java.util.Collection getPluggableLifeCycle() {
		java.util.ArrayList result = new java.util.ArrayList();
		return(result);
	}
	/**
	 * This method returns a list of VXML contributor classes for Pluggable Connectors.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public java.util.Collection getPluggableVXMLContrib() {
		java.util.ArrayList result = new java.util.ArrayList();
		return(result);
	}
	/**
	 * This method returns the root document for the application.
	 * This method is generated automatically and should not be modified
	 * because changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public String getRootDoc() {
		return("AppRoot");
	}
	/**
	 * This method returns a boolean to indicate if the approot node has a web page to show.
	 * This method is generated automatically and should not be modified
	 * because changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public boolean hasWebPage(com.avaya.sce.runtimecommon.SCESession mySession) {
		return false;
	}
	/**
	 * Builds the list of input parameters that are defined for this application 
	 * entry.  This list is built automatically by adding Input Parameter
	 * nodes to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>java.lang.String</code> objects that
	 * are the names of parameters the application is expecting.
	 * If the AppRoot node does not have any input parameters, then 
	 * this returns an empty list
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public java.util.Collection getInputParams(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
	/**
	 * Builds the list of capture expression that are defined for this application 
	 * entry.  This list is built automatically by adding Capture Expression
	 * items to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>CaptureExpression</code> objects that
	 * specify the ECMA script expression and the Orchestration Designer 
	 * session variable that will store the captured result.
	 * If the AppRoot node does not have any capture expression items, then 
	 * this returns an empty list
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public java.util.Collection getCaptureExpressions(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
}
