/**
 * Last generated by Orchestration Designer at: 2026-FEB-07  05:53:09 PM
 */
package english.prompts;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.avaya.sce.runtime.PhraseVariableElement;
import com.avaya.sce.runtime.PromptElement;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

public class DynamicPrompt extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for DynamicPrompt.
	 */
	public DynamicPrompt() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("DynamicPrompt");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}
	@Override
	public void updatePrompt(SCESession mySession) {
		super.updatePrompt(mySession);
		 int DTMF = mySession.getVariableField(IProjectVariables.FLAG,
		            IProjectVariables.FLAG_FIELD_SAV_NCUR_MENU_DTMF).getIntValue();
		    int savingsCount = mySession.getVariableField(IProjectVariables.ACC_COUNT,
		            IProjectVariables.ACC_COUNT_FIELD_SAV).getIntValue();
		    int currentCount = mySession.getVariableField(IProjectVariables.ACC_COUNT,
		            IProjectVariables.ACC_COUNT_FIELD_CUR).getIntValue();
		    int totalAccounts = savingsCount + currentCount;

		    boolean clearAllPrompts = false;
		    
		    // =======================
		    // Early exit if prompts cleared
		    // =======================
		    if (clearAllPrompts) {
		        int totalPrompts = mySession.getVariableField(
		                IProjectVariables.PROMPT_URL,
		                IProjectVariables.PROMPT_URL_FIELD_PROMPT_COUNT
		        ).getIntValue();

		        for (int i = 1; i <= totalPrompts; i++) {
		            mySession.getVariableField(IProjectVariables.PROMPT_URL,
		                    "Prompt_" + i).setValue(null);
		        }

		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		                "All prompts cleared. Skipping prompt playback.", mySession);
		        return;
		    }

		    // =======================
		    // Existing logic to fetch node & build prompts
		    // =======================
		    String NextNode = mySession.getVariableField(IProjectVariables.NODE_DETAILS,
		            IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
		    String Description = mySession.getVariableField(IProjectVariables.NODE_DETAILS,
		            IProjectVariables.NODE_DETAILS_FIELD_DESCRIPTION).getStringValue();
		    String CurAcc = mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
		            IProjectVariables.ACCOUNT_DETAILS_FIELD_CUR_ACC_NUMBER).getStringValue();
		    String CurBalance = mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
		            IProjectVariables.ACCOUNT_DETAILS_FIELD_CUR_BALANCE).getStringValue();
		    String SavAcc = mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
		            IProjectVariables.ACCOUNT_DETAILS_FIELD_SAV_ACC_NUMBER).getStringValue();
		    String SavBalance = mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
		            IProjectVariables.ACCOUNT_DETAILS_FIELD_SAV_BALANCE).getStringValue();
		    String AccountNmber = mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
		            IProjectVariables.ACCOUNT_DETAILS_FIELD_ACCOUNT_NUMBER).getStringValue();
		    String Balance = mySession.getVariableField(IProjectVariables.ACCOUNT_DETAILS,
		            IProjectVariables.ACCOUNT_DETAILS_FIELD_BALANCE).getStringValue();

		    if (CurAcc != null && CurAcc.length() >= 4) {
		        CurAcc = CurAcc.substring(CurAcc.length() - 4);
		    }
		    if (SavAcc != null && SavAcc.length() >= 4) {
		        SavAcc = SavAcc.substring(SavAcc.length() - 4);
		    }
		    if (AccountNmber != null && AccountNmber.length() >= 4) {
		        AccountNmber = AccountNmber.substring(AccountNmber.length() - 4);
		    }

		    String[] CurrentBalance = splitBalance(CurBalance);
		    String[] SavingBalance = splitBalance(SavBalance);
		    String[] AccountBalance = splitBalance(Balance);

		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "SAVING_ACC_COUNT : " + savingsCount, mySession);
		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "CURRENT_ACC_COUNT : " + currentCount, mySession);
		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "CUR_ACC_NUMBER : " + CurAcc, mySession);
		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "CUR_RUPEES : " + CurrentBalance[0], mySession);
		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "CUR_PAISE : " + CurrentBalance[1], mySession);
		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "SAV_ACC_NUMBER : " + SavAcc, mySession);
		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "SAV_RUPEES : " + SavingBalance[0], mySession);
		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "SAV_PAISE : " + SavingBalance[1], mySession);
		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "ACC_NUMBER : " + AccountNmber, mySession);
		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "RUPEES : " + AccountBalance[0], mySession);
		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "PAISE : " + AccountBalance[1], mySession);

		    if (Description.equalsIgnoreCase("PLAY_BALANACE")) {
		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "******* PLAY_BALANACE *******", mySession);

		        JSONObject nodeDetails = IVRFlow.getNodeByDescription("PLAY_BALANACE");
		        JSONArray Noprompts = nodeDetails.optJSONArray("menuPrompts");
		        int totalPrompts = (Noprompts != null) ? Noprompts.length() : 0;

		        mySession.getVariableField(IProjectVariables.PROMPT_URL,
		                IProjectVariables.PROMPT_URL_FIELD_PROMPT_COUNT).setValue(totalPrompts);

		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "TOTAL PROMPTS COUNT : " + totalPrompts, mySession);

		        try {
		            com.avaya.sce.runtime.Format format = new com.avaya.sce.runtime.Format();
		            format.add("format", "character");
		            format.add("inflection", "Cn");

		            com.avaya.sce.runtime.Format balanceF = new com.avaya.sce.runtime.Format();
		            balanceF.add("balanceF", "currency");
		            balanceF.add("inflection", "Nn");

		            String Audio_Path = mySession.getVariableField(IProjectVariables.PROMPT_URL,
		                    IProjectVariables.PROMPT_URL_FIELD_BASE_URL).getStringValue();

		         // =======================
		         // Decide which account to play
		         // =======================
		         String playAcc = null;
		         String playBal = null;
		         String playPaise = null;

		         if(totalAccounts == 1){
		        	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		        	            "******* SINGLE ACCOUNT CUSTOMER *******", mySession);

		        	    if(savingsCount == 1){
		        	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"******* AUTO PLAY SAVINGS BALANCE *******", mySession);
		        	        playAcc   = SavAcc;
		        	        playBal   = SavingBalance[0];
		        	        playPaise = SavingBalance[1];

		        	    }
		        	    else{
		        	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"******* AUTO PLAY CURRENT BALANCE *******", mySession);
		        	        playAcc   = CurAcc;
		        	        playBal   = CurrentBalance[0];
		        	        playPaise = CurrentBalance[1];
		        	    }
		        	}
		        	else{

		        	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		        	            "******* MULTIPLE ACCOUNTS - PLAY MENU *******", mySession);

		        	    if(DTMF == 1){   // SAVINGS SELECTED
		        	        if(savingsCount > 0){

		        	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		        	                    "******* SAVINGS SELECTED *******", mySession);
		        	            playAcc   = AccountNmber;
		        	            playBal   = AccountBalance[0];
		        	            playPaise = AccountBalance[1];

		        	        }
		        	        else{
		        	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		        	                    "******* CUSTOMER SELECTED SAVINGS BUT NONE EXISTS *******", mySession);
		        	        }
		        	    }
		        	    else if(DTMF == 2){   // CURRENT SELECTED

		        	        if(currentCount > 0){

		        	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		        	                    "******* CURRENT SELECTED *******", mySession);

		        	            playAcc   = AccountNmber;
		        	            playBal   = AccountBalance[0];
		        	            playPaise = AccountBalance[1];

		        	        }
		        	        
		        	        else{

		        	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		        	                    "******* CUSTOMER SELECTED CURRENT BUT NONE EXISTS *******", mySession);

		        	            // Retry / NoMatch
		        	        }
		        	    }
		        	}

		         TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "******* playAcc*******" +playAcc, mySession);
		         TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "******* playBal*******" + playBal, mySession);

		         // Set session variables for VXML
		         mySession.getVariableField(IProjectVariables.ACCOUNT_NUMBER).setValue(playAcc);
		         mySession.getVariableField(IProjectVariables.BALANCE).setValue(playBal);
		         mySession.getVariableField(IProjectVariables.PAISE).setValue(playPaise);
		         int count = 1;

		            if (Noprompts != null) {
		            	for (int i = 1; i <= totalPrompts; i++) {

			                TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"For Loop Count : " + i, mySession);

			                // FIX: use i, not totalPrompts
			                String setPrompt = "Prompt_" + i;

			                String promptName = mySession.getVariableField(IProjectVariables.PROMPT_URL, setPrompt).getStringValue();

			                String promptLocation = Audio_Path + promptName;

			                TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Prompt Location : " + promptLocation, mySession);

			                mySession.getVariableField(IProjectVariables.PROMPT_URL, setPrompt).setValue(promptLocation);

			                add(1, new com.avaya.sce.runtime.PhraseVariableElement("PromptURL:"+setPrompt, com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL));

			                if (count == 1) {
			                	add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"AccountNumber",format,false));
			                    count++;
			                } else if (count == 2) {
								add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"balance",balanceF,false));
			                    count++;
			                } else if (count == 3) {
								add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,"Paise",balanceF,false));
			                    count++;
			                }
			                
			            }
		            }
		            
		        	}catch (Exception e) {
		            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR, "Error in updatePrompts : " + e.getMessage(), mySession);
		        }
		    }
		    if(!Description.equalsIgnoreCase("PLAY_BALANACE")) {
    			String description = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DESCRIPTION).getStringValue();
    			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO , "NODE DESCRIPTION : "+description, mySession);
    			JSONObject nodeDetails = IVRFlow.getNodeByDescription(description);
		        JSONArray Noprompts = nodeDetails.optJSONArray("menuPrompts");
		        int totalPrompts = (Noprompts != null) ? Noprompts.length() : 0;
    	        int PromptCount = (Noprompts != null) ? Noprompts.length() : 0;
    			
    			String BaseURL = mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_BASE_URL).getStringValue();
    	    	
    	    	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"******** FETCH NODE PROMPTS LANG IDENTIFIED ********", mySession);
    	    	if (Noprompts != null && Noprompts.length() > 0) {

    	    	    for (int i = 0; i < Noprompts.length(); i++) {

    	    	        String setPrompt = "Prompt_" + (i + 1);
    	    	        String Prompt = mySession.getVariableField(IProjectVariables.PROMPT_URL,setPrompt).getStringValue();

    	    	        String promptlocation = BaseURL + Prompt;

    	    	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
    	    	                "PROMPT LOCATION : " + promptlocation,
    	    	                mySession);

    	    	        mySession.getVariableField(IProjectVariables.PROMPT_URL, setPrompt).setValue(promptlocation);

    	    	        add(1, new com.avaya.sce.runtime.PhraseVariableElement("PromptURL:Prompt_" + (i + 1),com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL));
    	    	    }
    	    	}

    		}

		}

	public static String[] splitBalance(String balance) {

	    if (balance == null || balance.isEmpty()) {
	        return new String[] { "0", "0" };
	    }

	    String[] parts = balance.split("\\.");

	    String integerPart = parts[0];
	    String decimalPart = (parts.length > 1) ? parts[1] : "0";

	    return new String[] { integerPart, decimalPart };
	}
}
