/**
 * Last generated by Orchestration Designer at: 2026-FEB-04  04:17:32 PM
 */
package english.prompts;

import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

public class Test extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for Test.
	 */
	public Test() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("Test");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}
	@Override

	public void updatePrompt(SCESession mySession) {

		// TODO Auto-generated method stub

		super.updatePrompt(mySession);
 
		mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_BASE_URL).setValue("/Prompts/ENGLISH/");
		
		String location = mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_BASE_URL).getStringValue();
		
		String bankID = location + "WELCOME.wav";
 
		mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_PROMPT_FULL_URL).setValue(bankID);
		
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"New URL Path" + bankID,mySession);
 
		add(1, new com.avaya.sce.runtime.PhraseVariableElement("PromptURL:PromptFullURL",com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL));

 
	}
 
}
