package flow;

import com.HostJar.API.api;
import com.HostJar.Flow.IVRFlow;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import DTO.TpinResponse;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-14  12:23:42 PM
 */
public class ExitPC extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-14  12:23:42 PM
	 */
	public ExitPC() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("Api", "Default");
		next.setDebugId(33);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);
		
		String NodeName = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DESCRIPTION).getStringValue();
//		String Action = mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_ACTION).getStringValue();
		if("COLLECT_NEW_TPIN".equalsIgnoreCase(NodeName)) {
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"ENERTED INTO IF NODE NAME : "+NodeName,mySession);
			String NewTPIN = mySession.getVariableField(IProjectVariables.PROMPT_AND_COLLECT,IProjectVariables.PROMPT_AND_COLLECT_FIELD_VALUE).getStringValue();
		    mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_TPIN___1).setValue(NewTPIN);
			
		}else if ("COLLECT_RE_TPIN".equalsIgnoreCase(NodeName)) {
			String ReEnteredTPIN = mySession.getVariableField(IProjectVariables.PROMPT_AND_COLLECT,IProjectVariables.PROMPT_AND_COLLECT_FIELD_VALUE).getStringValue();
			mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_TPIN___2).setValue(ReEnteredTPIN);
			String NewTPIN = mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_TPIN___1).getStringValue();
			
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NEW TPIN : "+NewTPIN,mySession);
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"RE-ENTERED TPIN : "+ ReEnteredTPIN,mySession);
			
			if(NewTPIN.equalsIgnoreCase(ReEnteredTPIN)) {
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"TPIN MATCH - SUCCESS",mySession);
				
				int DTMF = mySession.getVariableField(IProjectVariables.DYNAMIC_MENU,IProjectVariables.DYNAMIC_MENU_FIELD_VALUE).getIntValue();
				
				String Action = "";
				if(DTMF == 1) {
					Action = "GENERATE";
				}else {
					Action = "CHANGE";
				}
				mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_ACTION).setValue(Action);
			    String RelationshipID = (String) mySession.getProperty("RelationshipID");

		        String requestTime = java.time.Instant.now().toString();

		        String ucid = mySession.getVariableField(IProjectVariables.SESSION,IProjectVariables.SESSION_FIELD_UCID).getStringValue();
				
		        String isEncrypted = mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_TPIN__ENCRYPT__STATUS).getStringValue();
				
		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"RELATION_SHIP_ID : "+RelationshipID,mySession);
		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"ACTION : "+Action,mySession);
		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"TPIN : "+ReEnteredTPIN,mySession);
		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"IS_ENCRYPTED : "+ isEncrypted,mySession);
		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"UCID : "+ucid,mySession);
		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"REQ TIME : "+requestTime,mySession);
		        String current = mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).getStringValue();
				mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).setValue(current + "| "+ Action);
			
			
			    try {
			    	
					TpinResponse response = api.GenerateandChangeTPIN(RelationshipID, Action, ReEnteredTPIN, isEncrypted, ucid, requestTime);
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"TPIN RESPONSE : "+response,mySession);
					
					if(response.getResponseCode().equalsIgnoreCase("0000")) {
						mySession.setProperty("HAS_TPIN", true);	
					}
		
					
					
				} catch (Exception e) {
					e.printStackTrace();
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"ERROR : "+e.getMessage(),mySession);
					mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_API_STATUS).setValue(true);
					 String baseURL = mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_BASE_URL).getStringValue();
						TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"URL : "+baseURL,mySession);
						if (baseURL.equalsIgnoreCase("/Prompts/ENGLISH/")) {
							String VDN = IVRFlow.getTransferVDN("ENGLISH","CREDIT_CARD_SERVICES");
							TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS ENGLISH VDN : "+VDN,mySession);
							mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRANSFER_VDN).setValue(VDN);
						}else if (baseURL.equalsIgnoreCase("/Prompts/HINDI/")) {
							String VDN = IVRFlow.getTransferVDN("HINDI","CREDIT_CARD_SERVICES");
							TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS HINDI VDN : "+VDN,mySession);
							mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRANSFER_VDN).setValue(VDN);
						}else {
							String VDN = IVRFlow.getTransferVDN("DEFAULT","CREDIT_CARD_SERVICES");
							TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS DEFAULT VDN : "+VDN,mySession);
							mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRANSFER_VDN).setValue(VDN);
						}
				}
				mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_TPINSTATUS).setValue(true);
			}else {
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"TPIN MATCH - FAILED",mySession);
				mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_TPINSTATUS).setValue(false);
			}
			
		}
		
	}
}
