package flow;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-14  12:56:16 PM
 */
public class GetDetails extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-14  12:56:16 PM
	 */
	public GetDetails() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("DynamicNectNode", "Default");
		next.setDebugId(72);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);

	    try {
	    String NodeName = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();		
    	String Description = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DESCRIPTION).getStringValue(); 	    	
        String nodeType = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_ID).getStringValue();
        NodeName = NodeName != null ? NodeName.trim() : "";
        
        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"ROUTING | NODE_TYPE : " + nodeType + " NODE_NAME : " + Description+" NEXT_NODE :"+NodeName,mySession);
        
        boolean TwoFA=  (boolean) mySession.getProperty("2FA_FLAG");
        boolean HasTPIN=  (boolean) mySession.getProperty("HAS_TPIN");
        
        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"2FA STATUS : "+TwoFA,mySession);
        
        String nextNode ="";
        if("CHK_HAS_TPIN".equalsIgnoreCase(NodeName)) {
        	
        	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= CHK_HAS_TPIN =============",mySession);
        	
        	JSONObject nodeDetails = IVRFlow.getNodeByDescription(NodeName);
        	JSONArray parentNextNodes = nodeDetails.getJSONArray("nextNode");
        	// Next Node
        	if (parentNextNodes != null && parentNextNodes.length() > 0) {
        	    for (int i = 0; i < parentNextNodes.length(); i++) {
        	    	
        	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Next Node [" + i + "] : " + parentNextNodes.getString(i),mySession);
        	    }
        	} else {
        	    TraceInfo.trace(
        	        ITraceInfo.TRACE_LEVEL_INFO,"Next Node : NA",mySession
        	    );
        	}
        	
        	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"TPIN STATUS : "+HasTPIN,mySession);
        	
        	if(HasTPIN){
        		
           		nextNode = parentNextNodes.getString(0);
        		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"CUSTOMER HAS TPIN",mySession);
        		processNode(nextNode,0, mySession);
        		mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_ACTION).setValue("CHANGE");

        	}else {
        		nextNode = parentNextNodes.getString(1);
        		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"CUSTOMER NOT HAS TPIN",mySession);
        		processNode(nextNode,0, mySession);
        		mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_ACTION).setValue("GENERATE");
        	}
        }
        
        String ANY_NODE = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
        boolean Tpin_Flag =  mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_TPINSTATUS).getBooleanValue();
        int Count= mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_COUNT).getIntValue();
        
        if("CHK_2FA".equalsIgnoreCase(ANY_NODE)) {        	
        	
        	if(TwoFA) {
        		processNode(ANY_NODE,0, mySession);
        		String NEXT_NODE = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
        		processNode(NEXT_NODE,0, mySession);
        	}else {
        		mySession.setProperty("2FA_FLAG", false);
        		processNode(ANY_NODE,1, mySession);
        		String NEXT_NODE = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
        		processNode(NEXT_NODE,0, mySession);
        	}     	
        }else if ("VALIDATE_TPIN_MATCH".equalsIgnoreCase(ANY_NODE)){
        	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"ENTERED INTO THE VALIDATE_TPIN_MATCH", mySession);
        	if(Tpin_Flag) {
        		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"ENTERED INTO THE VALIDATE_TPIN_MATCH - IF", mySession);
        		processNode(ANY_NODE,0, mySession);
        		String NEXT_NODE = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
        		String Action = mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_ACTION).getStringValue();
        		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"ACTION : "+Action, mySession);
        		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NODE NAME : "+NEXT_NODE, mySession);
         		if("GENERATE".equalsIgnoreCase(Action)) {
        			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"ENTERED INTO THE GENERATE SUCCESS MSG", mySession);
            		processNode(NEXT_NODE,1, mySession);
            		String CHANGE_SUCCESS = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
            		processNode(CHANGE_SUCCESS,1, mySession);          		
        		}else if("CHANGE".equalsIgnoreCase(Action)) {
        			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"ENTERED INTO THE CHANGE SUCCESS MSG", mySession);
            		processNode(NEXT_NODE,0, mySession);
            		String GENERATE_SUCCESS = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
            		processNode(GENERATE_SUCCESS,1, mySession);
  
        		}
            	
        	} else {
        		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"ENTERED INTO THE VALIDATE_TPIN_MATCH - ELSE", mySession);
                // TPIN MISMATCH
                Count++;

                mySession.getVariableField(IProjectVariables.PC__TPIN, IProjectVariables.PC__TPIN_FIELD_COUNT).setValue(Count);

                TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"RETRY COUNT - " + Count, mySession);

                // CHECK MAX ATTEMPTS
                if (Count <= 3) {
                	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"ENTERED INTO THE CHECK MAX ATTEMPTS - IF", mySession);
                    processNode("NO_MATCH", 0, mySession);
                    return;

                } else {
                	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"ENTERED INTO THE CHECK MAX ATTEMPTS - ELSE", mySession);
                    processNode("MAXTRICES", 1, mySession);
                }
            }
        }else {
        	processNode(ANY_NODE,0, mySession);
        }
              
        
		} catch (Exception e) {
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"ERROR : " + e.getMessage(),mySession);
			e.printStackTrace();
		}			
	}
	private void processNode(String nodeDescription,int NextNode, SCESession mySession) throws Exception {

	    // ================================
	    // FETCH NODE JSON
	    // ================================
	    JSONObject nodeDetails = IVRFlow.getNodeByDescription(nodeDescription);

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NODE JSON DETAILS : " + nodeDetails.toString(), mySession);
	    
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"============= NODE DETAILS START =============",mySession);

	    // ================================
	    // NODE NAME (DESCRIPTION)
	    // ================================
	    String nodeName = nodeDetails.getString("Description");
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NODE NAME : " + nodeName, mySession);
	    mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DESCRIPTION).setValue(nodeName);

	    // ================================
	    // NODE ID
	    // ================================
	    String nodeId = nodeDetails.getString("ID");

	    mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_ID).setValue(nodeId);

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NODE TYPE : " + nodeId,mySession);

	    // ================================
	    // MENU PROMPTS
	    // ================================
	    JSONArray menuPrompts = nodeDetails.getJSONArray("menuPrompts");
	    int promptCount = menuPrompts.length();

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"MENU PROMPT COUNT : " + promptCount,mySession);

	    mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_PROMPT_COUNT).setValue(promptCount);

	    for (int i = 0; i < promptCount; i++) {

	        String prompt = menuPrompts.getString(i);
	        String promptKey = "Prompt_" + (i + 1);

	        mySession.getVariableField(IProjectVariables.PROMPT_URL,promptKey).setValue(prompt);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,promptKey + " : " + prompt,mySession);
	    }

	    // ================================
	    // MENU DTMF (ONLY FOR MENU NODES)
	    // ================================
	    if (nodeId.toUpperCase().startsWith("MEN")) {

	        JSONArray menuDTMFArray = nodeDetails.getJSONArray("menuDTMF");
	        int maxDTMF = 0;

	        for (int i = 0; i < menuDTMFArray.length(); i++) {
	            int value = Integer.parseInt(menuDTMFArray.getString(i));
	            maxDTMF = Math.max(maxDTMF, value);
	        }

	        mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DTMF).setValue(maxDTMF);

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"MENU DTMF : " + maxDTMF,mySession);
	    }
	    

	 // ================================
	 // NEXT NODE HANDLING
	 // ================================
		 JSONArray nextNodeArray = nodeDetails.optJSONArray("nextNode");
		 String nextNodeToUse = null;

		 if (nextNodeArray != null && nextNodeArray.length() > 0) {

		     if (NextNode >= 0 && NextNode < nextNodeArray.length()) {

		         nextNodeToUse = nextNodeArray.getString(NextNode);

		     } else {

		         TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
		                 "Invalid NextNode index: " + NextNode +
		                 " Array Size: " + nextNodeArray.length(),
		                 mySession);

		         // fallback to first element
		         nextNodeToUse = nextNodeArray.getString(0);
		     }

		 } else if (nodeDetails.has("nextNode")) {

		     nextNodeToUse = nodeDetails.getString("nextNode");
		 }
		 TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NEXT NODE TO USE : " + nextNodeToUse,mySession);
		 mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).setValue(nextNodeToUse);
	}
}
