package flow;

import javax.servlet.ServletContext;

import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2026-FEB-14  05:02:59 PM
 */
public class LoadValues extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-14  05:02:59 PM
	 */
	public LoadValues() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Experienve Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2026-FEB-14  05:02:59 PM
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {

		// TODO: Add your code here!

	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("GetDetails", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);


		try {

	        ServletContext context = mySession.getServlet().getServletContext();
 
	        // Fetch the context-param value

	        String propertyFilePath = context.getInitParameter("PropertyFile");
 
	        // Log it

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "Property File Path: " + propertyFilePath, mySession);

	        Load.getInstance().loadConfig(propertyFilePath);
 
	    } catch (Exception e) {

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR, "Error fetching Property File Path: " + e, mySession);

	    }

		
		String baseURL = (String) mySession.getProperty("BASE_URL"); 
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"AUDIO URL : " + baseURL, mySession);
		 mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_BASE_URL).setValue(baseURL);
		
		mySession.getVariableField(IProjectVariables.PC__TPIN,IProjectVariables.PC__TPIN_FIELD_TPIN__ENCRYPT__STATUS).setValue(Load.getInstance().getProperty("ENCRYPT_STATUS"));

	}
 
}
