package flow.subflow.ApiFail;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-18  05:27:19 PM
 */
public class ApiFlagFetch extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-18  05:27:19 PM
	 */
	public ApiFlagFetch() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("ApiFail-Ann", "Default");
		next.setDebugId(7);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:57 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
	    super.requestBegin(mySession);
	    
	    

        boolean transferFlag = IVRFlow.isWithinBusinessHours();

        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
                "Transfer Flag : " + transferFlag,
                mySession);

        mySession.getVariableField(IProjectVariables.VARIABLES,
                IProjectVariables.VARIABLES_FIELD_TRANSFER_FLAG)
                .setValue(transferFlag);


        // Convert API flag safely
        boolean apiFlag = Boolean.parseBoolean(
                mySession.getVariableField(IProjectVariables.NODE_DETAILS,
                        IProjectVariables.NODE_DETAILS_FIELD_API_STATUS)
                        .getStringValue()
        );


        // ✅ Final Decision (YOUR LOGIC KEPT SAME)
        boolean finalTransferFlag = false;

        if (apiFlag && transferFlag) {

            finalTransferFlag = true;

        } else if (apiFlag && !transferFlag) {

            finalTransferFlag = false;
        }


        // Store final result
        mySession.getVariableField(IProjectVariables.VARIABLES,
                IProjectVariables.VARIABLES_FIELD_FINAL_FLAG)
                .setValue(finalTransferFlag);

        boolean flag = mySession.getVariableField(
        		IProjectVariables.VARIABLES,
                IProjectVariables.VARIABLES_FIELD_FINAL_FLAG)
                .getBooleanValue();

        
        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
                "Flaggg : " + flag,
                mySession);

	   // String nextNode = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NODE).getStringValue();
        JSONObject nodeDetails = IVRFlow.getNodeByDescription("AgentTransfer");
		JSONArray Noprompts = nodeDetails.optJSONArray("menuPrompts");
		int totalPrompts = (Noprompts != null) ? Noprompts.length() : 0;
		
		mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_BASE_URL).setValue(Load.getInstance().getProperty("PROMPT_ENG"));
		    
		
		String Audio_Path = mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_BASE_URL).getStringValue();
        int count = 1;
 
        for (int i = 0; i < totalPrompts; i++) {

            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
                "For Loop Count : " + i, mySession);

            String prompt = Noprompts.getString(i);
                String setPrompt = "Prompt_" + (i + 1);

                mySession.getVariableField(
                    IProjectVariables.PROMPT,
                    setPrompt
                ).setValue(Audio_Path + prompt);
                
            }
        }
}
