package flow.subflow.ApiFail;

import java.util.Collection;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.PhraseVariableElement;
import com.avaya.sce.runtime.Prompt;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

/**
 * Class that represents a form.  A form can contain prompts, fields  and links
 * as well as handlers for various events that may occur while the form is executing
 * Last generated by Orchestration Designer at: 2026-FEB-18  07:57:20 PM
 */
public class Ann extends com.avaya.sce.runtime.Form {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-18  07:57:20 PM
	 */
	public Ann() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the links for the node, override:
	 *     void updateLinks(Collection links, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 * @return a collection of links
	 */
	public java.util.Collection getLinks(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Link link;
		java.util.List list;
		java.util.Collection grammarInfo = null;
		java.util.Collection<com.avaya.sce.runtime.CaptureExpression> captureExpr = null;
		// This item does not have any defined links
		list = new java.util.ArrayList();
		String ___tempGrammarName = null;

		return(list);
	}
	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the properties for the node, override:
	 *     void updateProperties(Collection properties, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 * @return a collection of properties
	 */
	public java.util.Collection getProperties(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Property property;
		java.util.List list;
		// This item does not have any defined properties
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the event handlers for the node, override:
	 *    void updateEvents(Collection events, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 * @return a collection of Events
	 */
	public java.util.Collection getEvents(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list;
		com.avaya.sce.runtime.Event event;
		list = new java.util.ArrayList();
		java.util.List eventPromptNames = null;
		String ___tempPromptName = null;
		return(list);
	}
	/**
	 * Builds the list of fields for the form.  This list is built
	 * by the code generator based on items in the call flow editor.
	 * This method should not be manually edited as changes may be
	 * overwritten by the code generator.  <br>
	 * To update the fields for the form, override
	 *     public void updateFields(Collection fields, com.avaya.sce.runtimecommon.SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getFields(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		java.util.List promptNames = null;
		java.util.List eventPromptNames = null;
		java.util.List grammarInfo = null;
		java.util.List events = null;
		java.util.List properties = null;
		com.avaya.sce.runtime.Field field = null;
		com.avaya.sce.runtime.Event event = null;
		com.avaya.sce.runtime.Property property = null;
		String ___tempPromptName = null;
		String ___tempGrammarName = null;

		int nbest = 0;

		// Form has no fields associated
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * Builds the list of prompts that are used by this flow item<br>
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of prompts for the flow item, override:
	 *     updatePrompts(Collection prompts, SCESession mySession)
	 * @return list of prompts for the menu
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getPrompts(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		String ___tempPromptName = null;
		// Item has no prompts associated
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * Returns the submit item that identifies the next form to transition to.
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Submit getSubmit(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Submit submit = null;
		submit = new com.avaya.sce.runtime.Submit("ApiFail-ApiFail");
		return submit;
	}
	/**
	 * Returns the record item for the form.
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Record getRecord(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Record record = null;
		java.util.Collection events = null;
		java.util.Collection promptNames = null;
		java.util.Collection eventPromptNames = null;
		java.util.Collection grammarInfo = null;
		com.avaya.sce.runtime.Event event = null;
		return record;
	}
	/**
	 * Returns the transfer item for the form.
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Transfer getTransfer(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Transfer transfer = null;
		return transfer;
	}
	/**
	 * Returns a Throw object that will throw an event at runtime if set.
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Throw getThrow(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Throw event = null;
		return event;
	}
	/**
	 * Builds the list of tracking items that are generated by this flow item<br>
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 * @return list of tracking items for the item
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getTrackingActions(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;

		// Item has no tracking items.
		list = new java.util.ArrayList();
		return(list);
	}
	/**
	 * Returns a collection of platform objects, or extensions to VXML.
	 * These objects result in the generation of the VXML object tag that
	 * the VXML platform attempts to use to load the runtime library that implements
	 * the extension.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getPlatformObjects(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.Collection objectList = null;
		java.util.Collection promptNames = null;
		com.avaya.sce.runtime.PlatformObject platformObject = null;

		// Form has no extension objects defined
		objectList = new java.util.ArrayList();
		return(objectList);
	}
	/**
	 * Builds the initial element for the form.  This method is built
	 * by the code generator based on items in the call flow editor.
	 * This method should not be manually edited as changes may be
	 * overwritten by the code generator.  <br>Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Initial getInitial(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Initial initial = null;
		java.util.List promptNames = null;
		java.util.List eventPromptNames = null;
		java.util.List events = null;
		com.avaya.sce.runtime.Event event = null;
		return initial;
	}
	/**
	 * Builds the grammar elements for the form.  This method is built
	 * by the code generator based on items in the call flow editor.
	 * This method should not be manually edited as changes may be
	 * overwritten by the code generator.  <br>Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getGrammars(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List grammarInfo = null;
		grammarInfo = new java.util.ArrayList();

		return grammarInfo;
	}
	@Override
	public void requestBegin(SCESession mySession) {
	    super.requestBegin(mySession);

	    

		String current = mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).getStringValue();
		mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).setValue(current + " | APIDOWN");
		mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_EXIT_LOCATION).setValue("APIDOWN");
	
	    JSONObject nodeDetails = IVRFlow.getNodeByDescription("AgentTransfer");
	    JSONArray Noprompts = nodeDetails.optJSONArray("menuPrompts");
	    int totalPrompts = (Noprompts != null) ? Noprompts.length() : 0;

	    mySession.getVariableField(
	        IProjectVariables.PROMPT_URL,
	        IProjectVariables.PROMPT_URL_FIELD_BASE_URL
	    ).setValue(Load.getInstance().getProperty("PROMPT_ENG"));

	    String Audio_Path = mySession.getVariableField(
	        IProjectVariables.PROMPT_URL,
	        IProjectVariables.PROMPT_URL_FIELD_BASE_URL
	    ).getStringValue();

	    for (int i = 0; i < totalPrompts; i++) {

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "For Loop Count : " + i, mySession);

	        String promptFile = Noprompts.getString(i);
	        String setPrompt = "Prompt_" + (i + 1);

	        mySession.getVariableField(
	            IProjectVariables.PROMPT,
	            setPrompt
	        ).setValue(Audio_Path + promptFile);
	    }
	}

	@Override
	public void updatePrompts(Collection prompts, SCESession mySession) {
	    super.updatePrompts(prompts, mySession);

	    Prompt prompt = new Prompt() {
	        @Override
	        public void buildPrompt() {}
	    };

	    prompt.setSession(mySession);
	    prompt.setOrder(Prompt.STANDARD);
	    prompt.setTimeout(1, 8000);
	    prompt.setBargin(1, true);

	    boolean flag = mySession.getVariableField(
	            IProjectVariables.VARIABLES,
	            IProjectVariables.VARIABLES_FIELD_FINAL_FLAG
	    ).getBooleanValue();

	    if(flag){
	    	 TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                 "Flag Enabled", mySession);
	        prompt.add(1, new PhraseVariableElement("Prompt:Prompt_1",
	                PhraseVariableElement.Type.AUDIO_URL));

	    }
	    else{
	    	 TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                 "Flag Not Enabled", mySession);
	    	mySession.getVariableField(
		            IProjectVariables.VARIABLES,
		            IProjectVariables.VARIABLES_FIELD_FINAL_FLAG
		    ).setValue(true);
	    	 prompt.add(1, new PhraseVariableElement("Prompt:Prompt_2",
		                PhraseVariableElement.Type.AUDIO_URL));
	    	 
	       
	    }
	    boolean noagnt = mySession.getVariableField(
	    		IProjectVariables.VARIABLES,
	            IProjectVariables.VARIABLES_FIELD_NO_AGENT
	    ).getBooleanValue();
	    
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
                "NO Agent Flag " + noagnt, mySession);

	    // ⭐ VERY IMPORTANT
	    prompts.add(prompt);
	}

}
