package flow.subflow.ApiFail;

/**
 * This servlet is the exit point of a subflow.  The base class handles
 * the logic for forwarding to the next servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-19  11:04:46 AM
 */
public class ApiFailse extends com.avaya.sce.runtime.SubflowReturn {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-19  11:04:46 AM
	 */
	public ApiFailse() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

}
