package flow.subflow.NINM_FLOW;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-15  08:26:09 PM
 */
public class FetchJson extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-15  08:26:09 PM
	 */
	public FetchJson() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("NINM_FLOW-NINM_CHECK", "Default");
		next.setDebugId(82);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	private String getPrompt(JSONObject nodeDetails, String key, SCESession mySession) {

	    if(nodeDetails == null){
	        return "";
	    }

	    Object obj = nodeDetails.opt(key);

	    if(obj == null){

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                key + " NOT CONFIGURED!",
	                mySession);

	        return "";
	    }

	    try {

	        // If Array
	        if(obj instanceof JSONArray){

	            JSONArray arr = (JSONArray) obj;

	            if(arr.length() > 0){
	                return arr.optString(0, "");
	            }
	        }

	        // If String
	        return String.valueOf(obj);

	    } catch (Exception e) {

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                "Error reading prompt : " + key + " -> " + e.getMessage(),
	                mySession);
	    }

	    return "";
	}

	@Override
	public void requestBegin(SCESession mySession) {

	    super.requestBegin(mySession);

	    
	    mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_BASE_URL).setValue(Load.getInstance().getProperty("PROMPT_ENG"));
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	            "******* SAV_OR_CUR_MENU *******",
	            mySession);

	    String nextNode = mySession.getVariableField(
	            IProjectVariables.NODE_DETAILS,
	            IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE
	    ).getStringValue();
	    
	    
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
                "NEXT NODE IN RETRYS" +nextNode ,
                mySession);

	    JSONObject nodeDetails = IVRFlow.getNodeByDescription(nextNode);

	    if (nodeDetails == null) {

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                "Node details not found!",
	                mySession);
	        return;
	    }

	    // ✅ SAFE PROMPT LOADING
	    String noInputFile = getPrompt(nodeDetails, "noInputPrompt", mySession);
	    String noMatchFile = getPrompt(nodeDetails, "noMatchPrompt", mySession);
	    String maxFile     = getPrompt(nodeDetails, "maxTriesPrompt", mySession);

	    // ✅ SET SESSION VARIABLES
	    mySession.getVariableField(
	            IProjectVariables.RETRY,
	            IProjectVariables.RETRY_FIELD_NOINPUT
	    ).setValue(noInputFile);

	    mySession.getVariableField(
	            IProjectVariables.RETRY,
	            IProjectVariables.RETRY_FIELD_NOMATCH
	    ).setValue(noMatchFile);

	    mySession.getVariableField(
	            IProjectVariables.RETRY,
	            IProjectVariables.RETRY_FIELD_MAX
	    ).setValue(maxFile);

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	            "NOINPUT : " + noInputFile,
	            mySession);

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	            "NOMATCH : " + noMatchFile,
	            mySession);

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	            "MAXTRIES : " + maxFile,
	            mySession);
	}
}
