package flow.subflow.ApiFail;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-18  02:34:27 AM
 */
public class ApiFlagFetch extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-18  02:34:27 AM
	 */
	public ApiFlagFetch() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("ApiFail-Ann", "Default");
		next.setDebugId(7);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
	    super.requestBegin(mySession);

	    try {

	        // 1️⃣ Check Business Hours
	        boolean transferFlag = IVRFlow.isWithinBusinessHours();

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "Business Hours Transfer Flag : " + transferFlag,
	                mySession);

	        mySession.getVariableField(IProjectVariables.VARIABELS,
	                IProjectVariables.VARIABELS_FIELD_TRANSFER_FLAG)
	                .setValue(transferFlag);


	        // 2️⃣ Fetch API Failed Flag (RAW VALUE)
	        String apiFlagRaw = mySession.getVariableField(
	                IProjectVariables.NODE_DETAILS,
	                IProjectVariables.NODE_DETAILS_FIELD_API__STATUS)
	                .getStringValue();

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "API_FAILED Raw Value : " + apiFlagRaw,
	                mySession);


	        // 3️⃣ Convert Safely to Boolean
	        boolean apiFlag = false;

	        if (apiFlagRaw != null && apiFlagRaw.trim().equalsIgnoreCase("true")) {
	            apiFlag = true;
	        }

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "API_FAILED Boolean Value : " + apiFlag,
	                mySession);


	        // 4️⃣ Final Decision
	        // Transfer ONLY if API Failed AND inside Business Hours
	        boolean finalTransferFlag = apiFlag && transferFlag;

	        mySession.getVariableField(IProjectVariables.VARIABELS,
	                IProjectVariables.VARIABELS_FIELD_FINAL_FLAG)
	                .setValue(finalTransferFlag);


	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "FINAL_TRANSFER_FLAG : " + finalTransferFlag,
	                mySession);

	    } catch (Exception e) {

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                "Error in ApiFail-ApiFlagFetch : " + e.getMessage(),
	                mySession);

	        e.printStackTrace();
	    }
	}

}
