package flow.subflow.OTP_Authentication;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-04  01:32:15 PM
 */
public class OTPLoadValues extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-04  01:32:15 PM
	 */
	public OTPLoadValues() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("OTP_Authentication-Validate", "Default");
		next.setDebugId(9);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);
		
					String NextNodeDescription = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
				
					IVRFlow IVR = new IVRFlow();
					
					String nextNode;
					
					if("AUTHENTICATION".equalsIgnoreCase(NextNodeDescription)) {
						JSONObject NodeDetails = IVRFlow.getNodeByDescription(NextNodeDescription);
						
						if (NodeDetails.get("nextNode") instanceof JSONArray) {
						    nextNode = NodeDetails.getJSONArray("nextNode").getString(0);
						} else {
						    nextNode = NodeDetails.getString("nextNode");
						}
						mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).setValue(nextNode);
					}
					String ANY_NODE = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
						JSONObject NodeDetails = IVRFlow.getNodeByDescription(ANY_NODE);
						
						String nodeName = NodeDetails.getString("Description");
					    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"NODE NAME : " + nodeName, mySession);
					    mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DESCRIPTION).setValue(nodeName);
						
						TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Node Details : " + NodeDetails.toString(),mySession);
						
						// Fetch the Next node
						if (NodeDetails.get("nextNode") instanceof JSONArray) {
						    nextNode = NodeDetails.getJSONArray("nextNode").getString(0);
						} else {
						    nextNode = NodeDetails.getString("nextNode");
						}

						mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).setValue(nextNode);

					
					
					
					String nodeType = NodeDetails.getString("ID");	
					
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Next Node : " + nextNode, mySession);	
					
					JSONArray menuPrompts = NodeDetails.getJSONArray("menuPrompts");
				    int promptCount = menuPrompts.length();

				    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"MENU PROMPT COUNT : " + promptCount,mySession);

				    mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_PROMPT_COUNT).setValue(promptCount);

				    for (int i = 0; i < promptCount; i++) {

				        String prompt = menuPrompts.getString(i);
				        String promptKey = "Prompt_" + (i + 1);

				        mySession.getVariableField(IProjectVariables.PROMPT_URL,promptKey).setValue(prompt);
				        mySession.getVariableField(IProjectVariables.PROMPT_HIN_URL,promptKey).setValue(prompt);

				        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,promptKey + " : " + prompt,mySession);
				    }
					
					
				    mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_NEXT_NODE).setValue(nodeType);
				    
				    mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_NEXT_NODE).setValue(nodeType);
					
					String SessionNextNode = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_NEXT_NODE).getStringValue();
					
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SessionNextNode : "+nodeType, mySession);

	}
}
