package flow.subflow.IdentificationRMN;

import java.util.Collection;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.Goto;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2026-FEB-04  07:23:24 AM
 */
public class RMN extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-04  07:23:24 AM
	 */
	public RMN() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Experienve Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2026-FEB-04  07:23:24 AM
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {

		// TODO: Add your code here!

	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2026-FEB-04  07:30:04 AM
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("IdentificationRMN-End", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
	@Override
	public void updateBranches(Collection branches, SCESession mySession) {

    	Goto aGoto = null;
		boolean error = false;
		
		
		try {
			
			// Get Next Node Description
			String NextNodeDescription = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
			String PreferredLanguage = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_PREFERRED_LANGUAGE).getStringValue();
		
			
			IVRFlow IVR = new IVRFlow();
			JSONObject NodeDetails = IVRFlow.getNodeByDescription(NextNodeDescription);
			
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Node Details : " + NodeDetails.toString(),mySession);
			
			
			// Fetch the Next node
			String nextNode;

			if (NodeDetails.get("nextNode") instanceof JSONArray) {
			    nextNode = NodeDetails.getJSONArray("nextNode").getString(0);
			} else {
			    nextNode = NodeDetails.getString("nextNode");
			}

			mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).setValue(nextNode);

			String nodeType = NodeDetails.getString("ID");	
			
			
			// Fetch Prompt name
			JSONArray menuPrompts = NodeDetails.getJSONArray("menuPrompts");

			for (int i = 0; i < menuPrompts.length(); i++) {
			    String prompt = menuPrompts.getString(i);

			    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Prompt : " + prompt, mySession);
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Node Type : " + nodeType,mySession);   
//			    
//				mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_PROMPT_ENG).setValue(prompt);
//				mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_PROMPT_HIN).setValue(prompt);
//				mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_PROMPT).setValue(prompt);
			}
			
			// Fetch Number of Options For Menu 
			if (nodeType.toUpperCase().startsWith("MEN")) {
				JSONArray menuDTMFArray = NodeDetails.getJSONArray("menuDTMF");

				int largestDTMF = 0;
				for (int i = 0; i < menuDTMFArray.length(); i++) {
				    int value = Integer.parseInt(menuDTMFArray.getString(i));
				    largestDTMF = Math.max(largestDTMF, value);
				}

				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,NextNodeDescription+" DTMF : " + largestDTMF,mySession);
				
				mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DTMF).setValue(largestDTMF);
			}
		    mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_NEXT_NODE).setValue(nodeType);
			
			String SessionNextNode = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_NEXT_NODE).getStringValue();
			
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SessionNextNode : "+SessionNextNode, mySession);

				aGoto = new Goto(SessionNextNode, 0);
				branches.clear();
				branches.add(aGoto);

		} catch(Exception e) {

			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"Error on Getting Next Node", mySession);
			mySession.getVariableField("Error").setValue(true);
			aGoto = new Goto("SetTechDiffPrompt", 0);
			branches.clear();
			branches.add(aGoto);
			
		}

		super.updateBranches(branches, mySession);
	}
}
