package flow;

import java.util.Collection;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.Format;
import com.avaya.sce.runtime.Goto;
import com.avaya.sce.runtime.PhraseVariableElement;
import com.avaya.sce.runtime.Prompt;
import com.avaya.sce.runtime.PromptElement;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.sun.xml.internal.bind.v2.runtime.Location;

/**
 * Class that represents a form.  A form can contain prompts, fields  and links
 * as well as handlers for various events that may occur while the form is executing
 * Last generated by Orchestration Designer at: 2026-FEB-09  03:36:41 PM
 */
public class Balance extends com.avaya.sce.runtime.Form {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-09  03:36:41 PM
	 */
	public Balance() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the links for the node, override:
	 *     void updateLinks(Collection links, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 * @return a collection of links
	 */
	public java.util.Collection getLinks(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Link link;
		java.util.List list;
		java.util.Collection grammarInfo = null;
		java.util.Collection<com.avaya.sce.runtime.CaptureExpression> captureExpr = null;
		// This item does not have any defined links
		list = new java.util.ArrayList();
		String ___tempGrammarName = null;

		return(list);
	}
	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the properties for the node, override:
	 *     void updateProperties(Collection properties, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 * @return a collection of properties
	 */
	public java.util.Collection getProperties(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Property property;
		java.util.List list;
		// This item does not have any defined properties
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the event handlers for the node, override:
	 *    void updateEvents(Collection events, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 * @return a collection of Events
	 */
	public java.util.Collection getEvents(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list;
		com.avaya.sce.runtime.Event event;
		list = new java.util.ArrayList();
		java.util.List eventPromptNames = null;
		String ___tempPromptName = null;
		return(list);
	}
	/**
	 * Builds the list of fields for the form.  This list is built
	 * by the code generator based on items in the call flow editor.
	 * This method should not be manually edited as changes may be
	 * overwritten by the code generator.  <br>
	 * To update the fields for the form, override
	 *     public void updateFields(Collection fields, com.avaya.sce.runtimecommon.SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getFields(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		java.util.List promptNames = null;
		java.util.List eventPromptNames = null;
		java.util.List grammarInfo = null;
		java.util.List events = null;
		java.util.List properties = null;
		com.avaya.sce.runtime.Field field = null;
		com.avaya.sce.runtime.Event event = null;
		com.avaya.sce.runtime.Property property = null;
		String ___tempPromptName = null;
		String ___tempGrammarName = null;

		int nbest = 0;

		// Form has no fields associated
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * Builds the list of prompts that are used by this flow item<br>
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of prompts for the flow item, override:
	 *     updatePrompts(Collection prompts, SCESession mySession)
	 * @return list of prompts for the menu
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getPrompts(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		String ___tempPromptName = null;
		// Item has no prompts associated
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * Returns the submit item that identifies the next form to transition to.
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Submit getSubmit(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Submit submit = null;
		submit = new com.avaya.sce.runtime.Submit("end");
		return submit;
	}
	/**
	 * Returns the record item for the form.
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Record getRecord(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Record record = null;
		java.util.Collection events = null;
		java.util.Collection promptNames = null;
		java.util.Collection eventPromptNames = null;
		java.util.Collection grammarInfo = null;
		com.avaya.sce.runtime.Event event = null;
		return record;
	}
	/**
	 * Returns the transfer item for the form.
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Transfer getTransfer(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Transfer transfer = null;
		return transfer;
	}
	/**
	 * Returns a Throw object that will throw an event at runtime if set.
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Throw getThrow(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Throw event = null;
		return event;
	}
	/**
	 * Builds the list of tracking items that are generated by this flow item<br>
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 * @return list of tracking items for the item
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getTrackingActions(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;

		// Item has no tracking items.
		list = new java.util.ArrayList();
		return(list);
	}
	/**
	 * Returns a collection of platform objects, or extensions to VXML.
	 * These objects result in the generation of the VXML object tag that
	 * the VXML platform attempts to use to load the runtime library that implements
	 * the extension.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getPlatformObjects(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.Collection objectList = null;
		java.util.Collection promptNames = null;
		com.avaya.sce.runtime.PlatformObject platformObject = null;

		// Form has no extension objects defined
		objectList = new java.util.ArrayList();
		return(objectList);
	}
	/**
	 * Builds the initial element for the form.  This method is built
	 * by the code generator based on items in the call flow editor.
	 * This method should not be manually edited as changes may be
	 * overwritten by the code generator.  <br>Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Initial getInitial(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Initial initial = null;
		java.util.List promptNames = null;
		java.util.List eventPromptNames = null;
		java.util.List events = null;
		com.avaya.sce.runtime.Event event = null;
		return initial;
	}
	/**
	 * Builds the grammar elements for the form.  This method is built
	 * by the code generator based on items in the call flow editor.
	 * This method should not be manually edited as changes may be
	 * overwritten by the code generator.  <br>Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getGrammars(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List grammarInfo = null;
		grammarInfo = new java.util.ArrayList();

		return grammarInfo;
	}
	 private static String last4(String acctNum) {
         if (acctNum == null) return "";
         acctNum = acctNum.trim();
         if (acctNum.length() <= 4) {
             return acctNum; 
         }
         return acctNum.substring(acctNum.length() - 4);
     }
	 
	 @Override
	public void requestBegin(SCESession mySession) {
		// TODO Auto-generated method stub
		super.requestBegin(mySession);
		
			
				super.requestBegin(mySession);
				
				
		
		  String nextNode  = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NODE).getStringValue();
		  JSONObject nodeDetails = IVRFlow.getNodeByDescription(nextNode);
		  JSONArray parentNextNodes = nodeDetails.getJSONArray("nextNode");

		  if (nextNode == null) {
		      TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR, "FETCH_NODE is NULL!", mySession);
		      return;
		  }

		  String next = parentNextNodes.getString(0);

		  mySession.getVariableField(
		      IProjectVariables.NODE_DETAILS,
		      IProjectVariables.NODE_DETAILS_FIELD_FETCH_NODE
		  ).setValue(next);

		  TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "******* next node ******* " + nextNode, mySession);
		
	 }
 	    
	
	 @Override
	 public void updatePrompts(Collection prompts, SCESession mySession) {

	     super.updatePrompts(prompts, mySession);
	     

	     try {
	    	 String current = mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).getStringValue();
				mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).setValue(current + " | CREDITCARDBALANCE");
				mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_EXIT_LOCATION).setValue("CREDITCARDBALANCE");
			
				String existingDesc =mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).getStringValue();
				String dis =  mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_EXIT_LOCATION).getStringValue();
			
				
				mySession.setProperty("MENU_DESCRIPTION", existingDesc);
		    	mySession.setProperty("DISPOSITION_TYPE", dis);
		    	
		    	String MENU_DESCRIPTION = (String) mySession.getProperty("MENU_DESCRIPTION");  
				String DISPOSITION_TYPE =	(String) mySession.getProperty("DISPOSITION_TYPE"); 
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "MENU_DESCRIPTION_CREDIT" + MENU_DESCRIPTION, mySession);
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "DISPOSITION_TYPE_CREDIT: " + DISPOSITION_TYPE, mySession);
	    	 
		      mySession.setProperty("JSON","REPEAT_MENU");
		       

	         //---------------- BASE URL ----------------//

		      String baseURL = (String) mySession.getProperty("BASE_URL"); 
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"AUDIO URL : " + baseURL, mySession);
				 mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_BASE_URL).setValue(baseURL);

	         if (baseURL == null || baseURL.isEmpty()) {

	             TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                     "BASE URL is NULL!", mySession);
	             return;
	         }
	         
	         

	         if (!baseURL.endsWith("/"))
	        	 baseURL += "/";

	         mySession.getVariableField(
	                 IProjectVariables.PROMPT_URL,
	                 IProjectVariables.PROMPT_URL_FIELD_BASE_URL)
	                 .setValue(baseURL);

	         TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                 "BASE URL : " + baseURL, mySession);
	         
	       String ApiAcc =   mySession.getVariableField(
	                 IProjectVariables.API,
	                 IProjectVariables.API_FIELD_CCNUMBER)
	                 .getStringValue();
	       
	       String balance =   mySession.getVariableField(
	                 IProjectVariables.API,
	                 IProjectVariables.API_FIELD_CREDITCARD_BALANCE)
	                 .getStringValue();
	       
	       
	       
	       
	       
	       TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                 "Accountnumberr    : " + ApiAcc, mySession);
	       
	       TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                 "Balanceee    : " + balance, mySession);

	         //---------------- GET USER SELECTION ----------------//

	       boolean flag = mySession.getVariableField(
	                 IProjectVariables.VARIABLES,
	                 IProjectVariables.VARIABLES_FIELD_FLAG)
	                 .getBooleanValue();
	         
	       
	     
	       
	         Prompt prompt = new Prompt() {
	             @Override
	             public void buildPrompt() {}
	         };

	         prompt.setSession(mySession);
	         prompt.setOrder(Prompt.STANDARD);
	         prompt.setTimeout(1, 8000);
	         prompt.setBargin(1, true);

	       
	       if(flag) {
	    	   
	    	   
	    	   String nextNode = mySession.getVariableField(
		                 IProjectVariables.NODE_DETAILS,
		                 IProjectVariables.NODE_DETAILS_FIELD_FETCH_NODE)
		                 .getStringValue();
		         

		         
		         if (nextNode == null) {

		        	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
		        	            "FETCH_NODE is NULL!",
		        	            mySession);
		        	    return;
		        	}
		       
		       
		       TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	    	            "**************!" + nextNode,
	    	            mySession);

		         JSONObject nodeDetails = IVRFlow.getNodeByDescription(nextNode);
		         
		         TraceInfo.trace(
		        	        ITraceInfo.TRACE_LEVEL_INFO,
		        	        "NODE -> " + nextNode + "\n" +
		        	        nodeDetails.toString(4),
		        	        mySession);

		         JSONArray promptsArray = nodeDetails.optJSONArray("menuPrompts");
		       

		         if (ApiAcc.length() >= 4) {

		             String last4Digits =
		            		 ApiAcc.substring(ApiAcc.length() - 4);

		             mySession.getVariableField(IProjectVariables.ACCOUNT)
		                     .setValue(last4Digits);
		         }

		         
		         String[] parts = balance.split("\\.");
				    String rupeesPart = parts[0];
				    String paisaPart = (parts.length > 1) ? parts[1] : "00";
				    
				    // Ensure paisa is always 2 digits (e.g., .5 becomes 50)
				    if (paisaPart.length() == 1) {
				        paisaPart += "0";
				    }
		         mySession.getVariableField(IProjectVariables.BALANCE)
		                 .setValue(rupeesPart);

		         mySession.getVariableField(IProjectVariables.PAISA)
		                 .setValue(paisaPart);


		         TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		                 "Selected Account : " + ApiAcc, mySession);

		         TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		                 "Balance : " + rupeesPart + "." + paisaPart, mySession);
		         
		         
	

		       
		         //---------------- FETCH NODE ----------------//


		         int totalPrompts = (promptsArray != null) ? promptsArray.length() : 0;
		        

		        String b =  mySession.getVariableField(IProjectVariables.BALANCE)
	             .getStringValue();
		        

		     

	    String f =  mySession.getVariableField(IProjectVariables.PAISA)
	             .getStringValue();
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	            "Balance********* : " + b + "paisa*****" + f, mySession);
		        
		        
		         


		         //---------------- FORMATS ----------------//


		         
		        com.avaya.sce.runtime.Format format = new com.avaya.sce.runtime.Format();
		 	    format.add("format", "character");
		 	    format.add("inflection", "Cn");
		         
		        
		         
		        com.avaya.sce.runtime.Format balanceF = new com.avaya.sce.runtime.Format();
	            balanceF.add("balanceF", "currency");
	            balanceF.add("inflection", "Nn");


		         
	      int count =0;
	     for (int i = 0; i < promptsArray.length(); i++) {

		    String promptFile = promptsArray.getString(i);

		    String setPrompt = "Prompt_" + (i + 1);

		    String promptLocation = baseURL + promptFile;

		    mySession.getVariableField(
		            IProjectVariables.PROMPT,
		            setPrompt).setValue(promptLocation);

		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		            "Prompt Location : " + promptLocation,
		            mySession);

		    // PLAY AUDIO
		    prompt.add(1,
		        new PhraseVariableElement(
		            "Prompt:" + setPrompt,
		            PhraseVariableElement.Type.AUDIO_URL));


		    //---------------- INSERT VARIABLES IN ORDER ----------------//

		    // AFTER "For account number ending with"
		    if (i == 0) {

		        prompt.add(1,
		            new PromptElement(
		                PromptElement.VARIABLE_AUDIO,
		                "Account",
		                format,
		                false));
		    }

		    // AFTER "The balance is"
		    else if (i == 1) {

		        prompt.add(1,
		            new PromptElement(
		                PromptElement.VARIABLE_AUDIO,
		                "Balance",
		                balanceF,
		                false));
		    }

		    // AFTER "RUPEES"
		    else if (i == 2) {

		        prompt.add(1,
		            new PromptElement(
		                PromptElement.VARIABLE_AUDIO,
		                "Paisa",
		                balanceF,
		                false));
		    }
		}

		prompts.add(prompt);

	          
		         
	       }
	       
	       else {
	    	   
	       
	         String nextNode = mySession.getVariableField(
	                 IProjectVariables.NODE_DETAILS,
	                 IProjectVariables.NODE_DETAILS_FIELD_FETCH_NODE)
	                 .getStringValue();
	         

	         
	         if (nextNode == null) {

	        	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	        	            "FETCH_NODE is NULL!",
	        	            mySession);
	        	    return;
	        	}
	       
	       
	       TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
    	            "**************!" + nextNode,
    	            mySession);

	         JSONObject nodeDetails = IVRFlow.getNodeByDescription(nextNode);
	         
	         TraceInfo.trace(
	        	        ITraceInfo.TRACE_LEVEL_INFO,
	        	        "NODE -> " + nextNode + "\n" +
	        	        nodeDetails.toString(4),
	        	        mySession);

	         JSONArray promptsArray = nodeDetails.optJSONArray("menuPrompts");
	       
	         String dtmf = mySession.getVariableField(
	                 IProjectVariables.CREDIT_CARD_LIST_MENU,
	                 IProjectVariables.CREDIT_CARD_LIST_MENU_FIELD_VALUE)
	                 .getStringValue();

	         if (dtmf == null) {
	             TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                     "DTMF is NULL!", mySession);
	             return;
	         }


	         String selectedNo = mySession.getVariableField(
	                 IProjectVariables.ACCOUNT_NUMBER,
	                 "Selected_" + dtmf).getStringValue();

	         String selectedBalance = mySession.getVariableField(
	                 IProjectVariables.ACCOUNT_NUMBER,
	                 "Balance_" + dtmf).getStringValue();


	         if (selectedNo == null || selectedBalance == null) {

	             TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                     "Account or Balance is NULL!", mySession);
	             return;
	         }


	         //---------------- STORE API VALUES ----------------//

	         mySession.getVariableField(
	                 IProjectVariables.API,
	                 IProjectVariables.API_FIELD_CCNUMBER)
	                 .setValue(selectedNo);

	         mySession.getVariableField(
	                 IProjectVariables.API,
	                 IProjectVariables.API_FIELD_CREDITCARD_BALANCE)
	                 .setValue(selectedBalance);


	         //---------------- LAST 4 DIGITS ----------------//

	         if (selectedNo.length() >= 4) {

	             String last4Digits =
	                     selectedNo.substring(selectedNo.length() - 4);

	             mySession.getVariableField(IProjectVariables.ACCOUNT)
	                     .setValue(last4Digits);
	         }


	    

	       
	       
	         // 3. Split Balance into Rupees and Paisa
			    String[] parts = selectedBalance.split("\\.");
			    String rupeesPart = parts[0];
			    String paisaPart = (parts.length > 1) ? parts[1] : "00";
			    
			    // Ensure paisa is always 2 digits (e.g., .5 becomes 50)
			    if (paisaPart.length() == 1) {
			        paisaPart += "0";
			    }
	         mySession.getVariableField(IProjectVariables.BALANCE)
	                 .setValue(rupeesPart);

	         mySession.getVariableField(IProjectVariables.PAISA)
	                 .setValue(paisaPart);


	         TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                 "Selected Account : " + selectedNo, mySession);

	         TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                 "Balance : " + rupeesPart + "." + paisaPart, mySession);

	       
	         //---------------- FETCH NODE ----------------//


	         int totalPrompts = (promptsArray != null) ? promptsArray.length() : 0;
	        

	        String b =  mySession.getVariableField(IProjectVariables.BALANCE)
             .getStringValue();
	        

	     

    String f =  mySession.getVariableField(IProjectVariables.PAISA)
             .getStringValue();
    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
            "Balance********* : " + b + "paisa*****" + f, mySession);
	        



	         
	        com.avaya.sce.runtime.Format format = new com.avaya.sce.runtime.Format();
	 	    format.add("format", "character");
	 	    format.add("inflection", "Cn");
	         
	        
	         
	        com.avaya.sce.runtime.Format balanceF = new com.avaya.sce.runtime.Format();
            balanceF.add("balanceF", "currency");
            balanceF.add("inflection", "Nn");


	         
      int count =0;
     for (int i = 0; i < promptsArray.length(); i++) {

	    String promptFile = promptsArray.getString(i);

	    String setPrompt = "Prompt_" + (i + 1);

	    String promptLocation = baseURL + promptFile;

	    mySession.getVariableField(
	            IProjectVariables.PROMPT,
	            setPrompt).setValue(promptLocation);

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	            "Prompt Location : " + promptLocation,
	            mySession);

	    // PLAY AUDIO
	    prompt.add(1,
	        new PhraseVariableElement(
	            "Prompt:" + setPrompt,
	            PhraseVariableElement.Type.AUDIO_URL));


	    //---------------- INSERT VARIABLES IN ORDER ----------------//

	   
	    if (i == 0) {

	        prompt.add(1,
	            new PromptElement(
	                PromptElement.VARIABLE_AUDIO,
	                "Account",
	                format,
	                false));
	    }

	  
	    else if (i == 1) {

	        prompt.add(1,
	            new PromptElement(
	                PromptElement.VARIABLE_AUDIO,
	                "Balance",
	                balanceF,
	                false));
	    }

	    // AFTER "RUPEES"
	    else if (i == 2) {

	        prompt.add(1,
	            new PromptElement(
	                PromptElement.VARIABLE_AUDIO,
	                "Paisa",
	                balanceF,
	                false));
	    }
     }

	prompts.add(prompt);

	     }
     
	       }
	catch (Exception e) {

	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	            "BALANCE NODE ERROR",
	            mySession);

	    e.printStackTrace();
	}

	 }	
	
}
