package flow;

import java.util.ArrayList;
import java.util.List;

import com.HostJar.API.api;
import com.HostJar.Flow.IVRFlow;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import DTO.CreditCardResponse;
import DTO.CustomerCardDetails;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-09  09:55:35 AM
 */
public class CreditcardFetch extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-09  09:55:35 AM
	 */
	public CreditcardFetch() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("Api", "Default");
		next.setDebugId(8);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}

		
	@Override
	public void requestBegin(SCESession mySession) {

	    super.requestBegin(mySession);

	    try {
	    	
	    		mySession.getVariableField(IProjectVariables.VARIABLES, IProjectVariables.VARIABLES_FIELD_RETRY_COUNT).setValue(0);
	    	
	        
	        mySession.getVariableField(IProjectVariables.API,
	                IProjectVariables.API_FIELD_CCNUMBER).setValue("");

	        mySession.getVariableField(IProjectVariables.API,
	                IProjectVariables.API_FIELD_CREDITCARD_BALANCE).setValue("");

	        mySession.getVariableField(IProjectVariables.API,
	                IProjectVariables.API_FIELD_CREDIT_ACC_FLAG).setValue("false");
	    	mySession.setProperty("2FA_FLAG", true);



		       String relationshipId = (String) mySession.getProperty("RelationshipID");
		       String baseURL = (String) mySession.getProperty("BASE_URL"); 
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"AUDIO URL : " + baseURL, mySession);
				 mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_BASE_URL).setValue(baseURL);
	 
		       TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"relationshipIddddd : " + relationshipId,mySession);

	        String requestTime = java.time.Instant.now().toString();

	        String ucid = mySession
	                .getVariableField(IProjectVariables.SESSION,
	                        IProjectVariables.SESSION_FIELD_UCID)
	                .getStringValue();

	        if (ucid == null || ucid.isEmpty()) {
	            ucid = "UNKNOWN";
	        }

	        // ✅ NOW RECEIVE POJO (Correct Type)
	        CreditCardResponse response =
	                api.CreditCardList(ucid, relationshipId, requestTime);

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "CreditCardResponse : " + response,
	                mySession);

	        // ✅ Null + Empty check
	        if (response == null ||
	                response.getCreditCards() == null ||
	                response.getCreditCards().isEmpty()) {

	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                    "No Credit Cards Found",
	                    mySession);

	            return;
	        }

	        List<String> accList = new ArrayList<>();
	        List<String> balList = new ArrayList<>();

	        for (CustomerCardDetails card : response.getCreditCards()) {

	            String accNo = card.getCreditCardNumber();
	            String bal = card.getCreditCardBalance();

	            accList.add(accNo != null ? accNo : "NA");
	            balList.add(bal != null ? bal : "0");
	        }

	        String accNumbers = String.join(",", accList);
	        String balances = String.join(",", balList);

	        boolean multiAccFlag = accList.size() > 1;

	        // ✅ Store in OD variables
	        mySession.getVariableField(IProjectVariables.API,
	                IProjectVariables.API_FIELD_CCNUMBER)
	                .setValue(accNumbers);

	        mySession.getVariableField(IProjectVariables.API,
	                IProjectVariables.API_FIELD_CREDITCARD_BALANCE)
	                .setValue(balances);

	        mySession.getVariableField(IProjectVariables.API,
	                IProjectVariables.API_FIELD_CREDIT_ACC_FLAG)
	                .setValue(String.valueOf(multiAccFlag));

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "Stored Accounts: " + accNumbers +
	                        " | MultiCard: " + multiAccFlag,
	                mySession);

	    } catch (Exception e) {

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                "Exception in CreditCard API : " + e.getMessage(),
	                mySession);
	        mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_API_STATUS).setValue(true);
	        String baseURL = mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_BASE_URL).getStringValue();
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"URL : "+baseURL,mySession);
			if (baseURL.equalsIgnoreCase("/Prompts/ENGLISH/")) {
				String VDN = IVRFlow.getTransferVDN("ENGLISH","CREDIT_CARD_SERVICES");
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS ENGLISH VDN : "+VDN,mySession);
				mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRASNFER_VDN).setValue(VDN);
			}else if (baseURL.equalsIgnoreCase("/Prompts/HINDI/")) {
				String VDN = IVRFlow.getTransferVDN("HINDI","CREDIT_CARD_SERVICES");
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS HINDI VDN : "+VDN,mySession);
				mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRASNFER_VDN).setValue(VDN);
			}else {
				String VDN = IVRFlow.getTransferVDN("DEFAULT","CREDIT_CARD_SERVICES");
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS DEFAULT VDN : "+VDN,mySession);
				mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRASNFER_VDN).setValue(VDN);
			}
	        
	    }
	}
}