package flow;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.Choice;
import com.avaya.sce.runtime.PhraseVariableElement;
import com.avaya.sce.runtime.Prompt;
import com.avaya.sce.runtime.PromptElement;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

/**
 * Class that represents a menu.  A menu can contain prompts, choices and links
 * as well as handlers for various events that may occur while the menu is executing
 * Last generated by Orchestration Designer at: 2026-FEB-09  10:28:48 AM
 */
public class CreditCardListMenu extends com.avaya.sce.runtime.Menu {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-09  10:28:48 AM
	 */
	public CreditCardListMenu() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the links for the node, override:
	 *     void updateLinks(Collection links, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 * @return a collection of links
	 */
	public java.util.Collection getLinks(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Link link;
		java.util.List list;
		java.util.Collection grammarInfo = null;
		java.util.Collection<com.avaya.sce.runtime.CaptureExpression> captureExpr = null;
		// This item does not have any defined links
		list = new java.util.ArrayList();
		String ___tempGrammarName = null;

		return(list);
	}
	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the properties for the node, override:
	 *     void updateProperties(Collection properties, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 * @return a collection of properties
	 */
	public java.util.Collection getProperties(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Property property;
		java.util.List list;
		// This item does not have any defined properties
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the event handlers for the node, override:
	 *    void updateEvents(Collection events, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 * @return a collection of Events
	 */
	public java.util.Collection getEvents(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list;
		com.avaya.sce.runtime.Event event;
		list = new java.util.ArrayList(2);
		java.util.List eventPromptNames = null;
		String ___tempPromptName = null;

		// Item has no prompts associated
		eventPromptNames = new java.util.ArrayList();

		event = new com.avaya.sce.runtime.Event(com.avaya.sce.runtimecommon.SCERT.EVENT_NOINPUT, (com.avaya.sce.runtime.PromptRefInfo[])eventPromptNames.toArray(new com.avaya.sce.runtime.PromptRefInfo[0]), new com.avaya.sce.runtime.Goto("Retry", 0, true, ""));
		list.add(event);

		// Item has no prompts associated
		eventPromptNames = new java.util.ArrayList();

		event = new com.avaya.sce.runtime.Event(com.avaya.sce.runtimecommon.SCERT.EVENT_NOMATCH, (com.avaya.sce.runtime.PromptRefInfo[])eventPromptNames.toArray(new com.avaya.sce.runtime.PromptRefInfo[0]), new com.avaya.sce.runtime.Goto("Retry", 0, true, ""));
		list.add(event);
		return(list);
	}
	/**
	 * Builds the list of choices for the menu.  This list is built
	 * automatically by the code generator and should not be edited
	 * manually.  Future code generation may overwrite any changes
	 * to this method.<br>
	 * To modify the list of choices, override:<br>
	 *    updateChoices(Collection choices, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getChoices(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Choice choice = null;
		java.util.Collection grammarInfo = null;
		list = new java.util.ArrayList(1);
		String ___tempGrammarName = null;

		// build the list of grammar information objects for the choice
		grammarInfo = new java.util.ArrayList();


		choice = new com.avaya.sce.runtime.Choice("", "#90", true, "exact", "CreditCardListMenu", grammarInfo, true);
		list.add(choice);

		return(list);
	}
	/**
	 * Builds the list of prompts that are used by this flow item<br>
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of prompts for the flow item, override:
	 *     updatePrompts(Collection prompts, SCESession mySession)
	 * @return list of prompts for the menu
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getPrompts(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		String ___tempPromptName = null;
		// Item has no prompts associated
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * Builds the list of tracking items that are generated by this flow item<br>
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 * @return list of tracking items for the item
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getTrackingActions(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;

		// Item has no tracking items.
		list = new java.util.ArrayList();
		return(list);
	}
	
	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);
		
		
			super.requestBegin(mySession);
			String current = mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).getStringValue();
			mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).setValue(current + " | CREDITCARDLISTMENU");
			mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_EXIT_LOCATION).setValue("CREDITCARDLISTMENU");
		
			
		
		//mySession.getVariableField(IProjectVariables.VARIABLES, IProjectVariables.VARIABLES_FIELD_RETRY_COUNT).setValue(0);
		
		 String nextNode = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NODE).getStringValue();
	        
		 TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "NODEEEEEEEEE : " + nextNode, mySession);
		 
		JSONObject nodeDetails = IVRFlow.getNodeByDescription(nextNode);
		
		JSONArray Noprompts = nodeDetails.optJSONArray("menuPrompts");

		int totalPrompts = (Noprompts != null) ? Noprompts.length() : 0;
		
		
		    
		
		String Audio_Path = mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_BASE_URL).getStringValue();
        
		 TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "AUDIO PATH : " + Audio_Path, mySession);
		int count = 1;
        for (int i = 0; i < totalPrompts; i++) {

            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
                "For Loop Count : " + i, mySession);

            String prompt = Noprompts.getString(i);

            if ("NEXT_OPTIONS.wav".equalsIgnoreCase(prompt)) {

                mySession.getVariableField(
                    IProjectVariables.VARIABLES,
                    IProjectVariables.VARIABLES_FIELD_NEXT_PAGE
                ).setValue(Audio_Path + prompt);

            } else if ("REPEAT_OPTION.wav".equalsIgnoreCase(prompt)) {

                mySession.getVariableField(
                    IProjectVariables.VARIABLES,
                    IProjectVariables.VARIABLES_FIELD_REPEAT
                ).setValue(Audio_Path + prompt);

            } else if ("PREVIOUS_OPTIONS.wav".equalsIgnoreCase(prompt)) {

                mySession.getVariableField(
                    IProjectVariables.VARIABLES,
                    IProjectVariables.VARIABLES_FIELD_PREVIOUS_PAGE
                ).setValue(Audio_Path + prompt);

            } else {

                String setPrompt = "Prompt_" + (i + 1);

                mySession.getVariableField(
                    IProjectVariables.PROMPT,
                    setPrompt
                ).setValue(Audio_Path + prompt);
            }
        }

	
	}
	
	
	@Override
	public void updatePrompts(Collection prompts, SCESession mySession) {
	    super.updatePrompts(prompts, mySession);

	    
	   
	    String accNo = mySession.getVariableField(IProjectVariables.API, IProjectVariables.API_FIELD_CCNUMBER).getStringValue();
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR, "CREDIT CARD ACCOUNTNUMBER " + accNo, mySession);

	    List<String> accountList = new ArrayList<>();
	    if (accNo != null && !accNo.trim().isEmpty()) {
	        accountList = Arrays.stream(accNo.split(","))
	                .map(String::trim)
	                .filter(s -> !s.isEmpty())
	                .collect(Collectors.toList());
	    }

	    
	   
	    String ccbalance = mySession.getVariableField(IProjectVariables.API, IProjectVariables.API_FIELD_CREDITCARD_BALANCE).getStringValue();
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR, "CREDIT CARD BALANCE " + ccbalance, mySession);

	    mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_BASE_URL).setValue(Load.CONFIG.getProperty("PROMPT_ENG"));

	    String location = mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_BASE_URL).getStringValue();
	   
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR, "LOCATION" + location, mySession);
	    
	    
	    int currentPage = 0;

	    String pageStr = mySession.getVariableField(
	            IProjectVariables.VARIABLES,
	            IProjectVariables.VARIABLES_FIELD_PAGE_INDEX).getStringValue();

	    if (pageStr != null && !pageStr.trim().isEmpty()) {
	        try {
	            currentPage = Integer.parseInt(pageStr.trim());
	        } catch (Exception e) {
	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                    "Invalid PAGE_INDEX. Defaulting to 0", mySession);
	            currentPage = 0;
	        }
	    }





	    // PAGE SIZE
	    int pageSize = 4;
	    String pageSizeStr = mySession.getVariableField(IProjectVariables.VARIABLES, IProjectVariables.VARIABLES_FIELD_PAGE_SIZE).getStringValue();
	    if (pageSizeStr != null && !pageSizeStr.trim().isEmpty()) {
	        try {
	            pageSize = Integer.parseInt(pageSizeStr.trim());
	        } catch (Exception e) {
	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR, "Invalid PAGE_SIZE. Using default 4", mySession);
	        }
	    }

	    String dtmf = mySession.getVariableField(
	            IProjectVariables.CREDIT_CARD_LIST_MENU,
	            IProjectVariables.CREDIT_CARD_LIST_MENU_FIELD_VALUE).getStringValue();

	    if (dtmf == null) {
	        dtmf = "";
	    }
	    dtmf = dtmf.trim();

	    mySession.getVariableField(
	            IProjectVariables.CREDIT_CARD_LIST_MENU,
	            IProjectVariables.CREDIT_CARD_LIST_MENU_FIELD_VALUE).setValue("");

	    int totalPages = (int) Math.ceil((double) accountList.size() / pageSize);

	    switch (dtmf) {

	    case "5":
	        if (currentPage < totalPages - 1) {
	            currentPage++;
	        }
	        break;

	    case "6":
	        if (currentPage > 0) {
	            currentPage--;
	        }
	        break;

	    case "*":
	        // repeat → do nothing
	        break;

	    default:
	        // NoMatch / Invalid input
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "Invalid DTMF. Staying on same page: " + currentPage,
	                mySession);
	        break;
	}


	    // UPDATE PAGE INDEX BEFORE RESETTING DTMF
	    mySession.getVariableField(IProjectVariables.VARIABLES, IProjectVariables.VARIABLES_FIELD_PAGE_INDEX).setValue(currentPage);

	    // RESET DTMF AFTER USING IT
	    mySession.getVariableField(IProjectVariables.CREDIT_CARD_LIST_MENU, IProjectVariables.CREDIT_CARD_LIST_MENU_FIELD_VALUE).setValue("");

	    // BUILD PROMPT
	    Prompt prompt = new Prompt() {
	        @Override
	        public void buildPrompt() {}
	    };
	    prompt.setSession(mySession);
	    prompt.setOrder(Prompt.STANDARD);
	    prompt.setTimeout(1, 8000);
	    prompt.setBargin(1, true);

	    com.avaya.sce.runtime.Format format = new com.avaya.sce.runtime.Format();
	    format.add("format", "character");
	    format.add("inflection", "Cn");
	    
	    
	    
	
	    

	    // ADD ACCOUNTS TO PROMPT
	    int start = currentPage * pageSize;
	    int end = Math.min(start + pageSize, accountList.size());
	    int pressCount = 1;
	    for (int i = start; i < end; i++, pressCount++) {
	    	
	        String accData = accountList.get(i);
	        String last4 = accData.length() >= 4 ? accData.substring(accData.length() - 4) : "0000";

	        
	        String pressVarName = "presscount_" + pressCount;
	        
	       
	        mySession.getVariableField(IProjectVariables.ACCOUNT_NUMBER, pressVarName).setValue(String.valueOf(pressCount));

	        
	        
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "last 4 accNo: " + last4, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "Pressssss: " + pressVarName, mySession);
	        
	        
	        String accountVarName = "AccountNumber_" + pressCount;
	        mySession.getVariableField(IProjectVariables.ACCOUNT_NUMBER, accountVarName).setValue(last4);


	        
	        prompt.add(1, new com.avaya.sce.runtime.PhraseVariableElement("Prompt:Prompt_1", com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL));
	     
	        prompt.add(1, new PromptElement(PromptElement.VARIABLE_AUDIO, "AccountNumber:" + accountVarName, format, false));

	        prompt.add(1, new com.avaya.sce.runtime.PhraseVariableElement("Prompt:Prompt_2", com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL));
	        
	        prompt.add(1, new PromptElement(PromptElement.VARIABLE_AUDIO, "AccountNumber:" + pressVarName, format, false));
	       
	        
	    }

	    // ADD NEXT / PREVIOUS PAGE PROMPTS
	    if (currentPage > 0) {
	       
	        prompt.add(1, new PhraseVariableElement("Variables:previousPage", PhraseVariableElement.Type.AUDIO_URL));
	    }
	    if (currentPage < totalPages - 1) {
	       
	        prompt.add(1, new PhraseVariableElement("Variables:nextPage", PhraseVariableElement.Type.AUDIO_URL));
	    }


	    prompt.add(1,
	            new PhraseVariableElement(
	                    "Variables:Repeat",
	                    PhraseVariableElement.Type.AUDIO_URL));
	    prompts.add(prompt);
	}

	@Override
	public void updateChoices(Collection choices, SCESession mySession) {
	    super.updateChoices(choices, mySession);

	    List<Choice> list = new ArrayList<>();
	    Collection grammarInfo = null;

	    // GET ALL ACCOUNTS
	    String creditCc = mySession.getVariableField(IProjectVariables.API, IProjectVariables.API_FIELD_CCNUMBER).getStringValue();
	    List<String> accountList = new ArrayList<>();
	    if (creditCc != null && !creditCc.trim().isEmpty()) {
	        accountList.addAll(Arrays.asList(creditCc.split(",")));
	    }

	    // GET ALL BALANCES
	    String balanceStr = mySession.getVariableField(IProjectVariables.API, IProjectVariables.API_FIELD_CREDITCARD_BALANCE).getStringValue();
	    List<String> balanceList = new ArrayList<>();
	    if (balanceStr != null && !balanceStr.trim().isEmpty()) {
	        balanceList = Arrays.stream(balanceStr.split(","))
	                            .map(String::trim)
	                            .collect(Collectors.toList());
	    }

	    // PAGE INDEX
	    int pageIndex = 0;
	    String pageStr = mySession.getVariableField(IProjectVariables.VARIABLES, IProjectVariables.VARIABLES_FIELD_PAGE_INDEX).getStringValue();
	    if (pageStr != null && !pageStr.trim().isEmpty()) {
	        try {
	            pageIndex = Integer.parseInt(pageStr.trim());
	        } catch (NumberFormatException e) {
	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR, "Invalid PAGE_INDEX: " + e.getMessage(), mySession);
	        }
	    }

	    int pageSize = 4;
	    int start = pageIndex * pageSize;
	    int end = Math.min(start + pageSize, accountList.size());

	    // MAP DTMF TO CURRENT PAGE ACCOUNTS
	    for (int i = start, DTMF = 1; i < end; i++, DTMF++) {
	        String accNumber = accountList.get(i);
	        String accBalance = i < balanceList.size() ? balanceList.get(i) : "0";

	        mySession.getVariableField(IProjectVariables.ACCOUNT_NUMBER, "Selected_" + DTMF).setValue(accNumber);
	        mySession.getVariableField(IProjectVariables.ACCOUNT_NUMBER, "Balance_" + DTMF).setValue(accBalance);

	        
	        Choice choice = new Choice("AccNo",String.valueOf(DTMF),true,"exact","Balance",grammarInfo,true);
	        list.add(choice);

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "DTMF " + DTMF + " -> Account: " + accNumber + ", Balance: " + accBalance,
	                mySession);
	    }

	 
	    int totalPages = (int) Math.ceil((double) accountList.size() / pageSize);

	    if (pageIndex > 0) {
	        list.add(new Choice("PreviousPage", "6", true, "exact", "CreditCardListMenu", grammarInfo, true));
	    }
	    if (pageIndex < totalPages - 1) {
	        list.add(new Choice("NextPage", "5", true, "exact", "CreditCardListMenu", grammarInfo, true));
	    }
	    list.add(new Choice(
	            "RepeatPage",
	            "*",
	            true,
	            "exact",
	            "CreditCardListMenu",
	            grammarInfo,
	            true));

	    choices.addAll(list);
	}


}
