package flow;

import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

/**
 * Implements the return from an application.  A Return class allows an application
 * to do some processing.  If the application is invoked by another application,
 * then this class will define the parameters returned to the calling application.
 * Last generated by Orchestration Designer at: 2026-FEB-09  09:55:35 AM
 */
public class end extends com.avaya.sce.runtime.Return {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-09  09:55:35 AM
	 */
	public end() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Builds the list of output parameters that are returned by this application
	 * This list is built automatically by defining Output Parameter nodes in the
	 * call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Parameter</code>
	 * objects that the runtime will return to the calling application.
	 * If the node does not have any output parameters, then 
	 * this returns an empty list
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getOutputParams(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Parameter param = null;
		list = new java.util.ArrayList();

		return list;
	}
	/**
	 * Builds the list of prompts that are used by this flow item<br>
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of prompts for the flow item, override:
	 *     updatePrompts(Collection prompts, SCESession mySession)
	 * @return list of prompts for the menu
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getPrompts(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		String ___tempPromptName = null;
		// Item has no prompts associated
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * Builds the list of tracking items that are generated by this flow item<br>
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 * @return list of tracking items for the item
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public java.util.Collection getTrackingActions(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;

		// Item has no tracking items.
		list = new java.util.ArrayList();
		return(list);
	}
	@Override
	public void requestBegin(SCESession mySession) {
		// TODO Auto-generated method stub
		super.requestBegin(mySession);
		String existingDesc =mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).getStringValue();
		String dis =  mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_EXIT_LOCATION).getStringValue();
	
		
		mySession.setProperty("MENU_DESCRIPTION", existingDesc);
    	mySession.setProperty("DISPOSITION_TYPE", dis);
    	
    	String MENU_DESCRIPTION = (String) mySession.getProperty("MENU_DESCRIPTION");  
		String DISPOSITION_TYPE =	(String) mySession.getProperty("DISPOSITION_TYPE"); 
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "MENU_DESCRIPTION_CREDIT" + MENU_DESCRIPTION, mySession);
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "DISPOSITION_TYPE_CREDIT: " + DISPOSITION_TYPE, mySession);
	}
}
