package flow;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.avaya.sce.runtime.Goto;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2026-FEB-09  10:54:52 AM
 */
public class FetchJson extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-09  10:54:52 AM
	 */
	public FetchJson() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Experienve Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2026-FEB-09  10:54:52 AM
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {

		// TODO: Add your code here!

	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2026-FEB-13  08:00:21 PM
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("CreditCardListMenu", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
	@Override
	public void updateBranches(Collection branches, SCESession mySession) {
 
    	Goto aGoto = null;
		boolean error = false;

		try {
			mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NODE).setValue("CREDICARD");
			String NextNodeDescription = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NODE).getStringValue();
		    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
		            "Next Node Session : " + NextNodeDescription,
		            mySession);
		    
			IVRFlow IVR = new IVRFlow();
			JSONObject menuDetails = IVRFlow.getNodeByDescription(NextNodeDescription);
 
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
			        ": " + menuDetails.toString(),
			        mySession);
 
			
			List<String> promptsList = new ArrayList<>();
			JSONArray menuPrompts = menuDetails.getJSONArray("menuPrompts");
			 
			for (int i = 0; i < menuPrompts.length(); i++) {
			    String prompt = menuPrompts.getString(i);
			    promptsList.add(prompt);
			    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
			            "CREDITCARD LIST FLOW: " + prompt,
			            mySession);
				
			}
			mySession.getVariableField(IProjectVariables.VARIABLES,IProjectVariables.VARIABLES_FIELD_CREDIT_CARD_LIST_PROMPT).setValue(promptsList);
			
			String PromptListCredit =mySession.getVariableField(IProjectVariables.VARIABLES,IProjectVariables.VARIABLES_FIELD_CREDIT_CARD_LIST_PROMPT).getStringValue();
			//mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_NEXT_NODE).setValue(nodeType);
			String SessionNextNode = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NODE).getStringValue();
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SessionNextNode****** : "+SessionNextNode, mySession);
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"PromptListCredit : "+PromptListCredit, mySession);
 
//				aGoto = new Goto(SessionNextNode, 0);
//				branches.clear();
//				branches.add(aGoto);
 
		} catch(Exception e) {
 
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"Error on Getting Next Node", mySession);
			mySession.getVariableField("Error").setValue(true);
//			aGoto = new Goto("SetTechDiffPrompt", 0);
//			branches.clear();
//			branches.add(aGoto);
 
		}}
	
}
