package flow;

/**
 * This interface is used to define the name of variables that are 
 * declared in the call flow.  All variables are defined as 
 * <code>public static final String</code>, which allows user-defined
 * code to reference variable names by the Java variable name.
 * Last generated by Orchestration Designer at: 2026-FEB-09  09:55:35 AM
 */
public interface IProjectVariables {





	//{{START:PROJECT:VARIABLES
	/**
	 * This is a reserved block of variable name definitions.
	 * The variable names defined here can be used as the key
	 * to get the <code>com.avaya.sce.runtime.Variable</code>
	 * from the <code>SCESession</code> at runtime.<br>
	 * 
	 * For example, given a variable name <code>phoneNum</code>,
	 * user-defined code should access the variable in this format:<PRE>
	 *   Variable phNum = mySession.getVariable(IProjectVariables.PHONE_NUM);
	 *   if ( phNum != null ) {
	 *        // do something with the variable
	 *   }</PRE>
	 * 
	 * This block of code is generated automatically by Orchestration Designer and should not
	 * be manually edited as changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public static final String ACCOUNT = "Account";
	public static final String CREDIT_CARD_LIST_MENU = "CreditCardListMenu";
	public static final String CALL_HISTORY = "CallHistory";
	public static final String TRANSFER = "Transfer";
	public static final String RETRY = "Retry";
	public static final String REDIRECTINFO = "redirectinfo";
	public static final String PAISA = "Paisa";
	public static final String PROMPT = "Prompt";
	public static final String DATE = "date";
	public static final String PROMPT_URL = "PromptURL";
	public static final String FLAG = "Flag";
	public static final String BALANCE = "Balance";
	public static final String SESSION = "session";
	public static final String VARIABLES = "Variables";
	public static final String CREDIT = "Credit";
	public static final String DD_LAST_EXCEPTION = "ddLastException";
	public static final String NODE_DETAILS = "NodeDetails";
	public static final String ACCOUNT_NUMBER = "AccountNumber";
	public static final String TIME = "time";
	public static final String API = "Api";
	public static final String SHAREDUUI = "shareduui";
	//}}END:PROJECT:VARIABLES
	//{{START:PROJECT:VARIABLEFIELDS
	public static final String CREDIT_CARD_LIST_MENU_FIELD_CONFIDENCE = "confidence";
	public static final String CREDIT_CARD_LIST_MENU_FIELD_INPUTMODE = "inputmode";
	public static final String CREDIT_CARD_LIST_MENU_FIELD_INTERPRETATION = "interpretation";
	public static final String CREDIT_CARD_LIST_MENU_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String CREDIT_CARD_LIST_MENU_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String CREDIT_CARD_LIST_MENU_FIELD_UTTERANCE = "utterance";
	public static final String CREDIT_CARD_LIST_MENU_FIELD_VALUE = "value";
	public static final String CALL_HISTORY_FIELD_EXIT_LOCATION = "exitLocation";
	public static final String CALL_HISTORY_FIELD_MENU_DESCRIPTION = "menuDescription";
	public static final String RETRY_FIELD_MAX = "Max";
	public static final String RETRY_FIELD_NOINPUT = "Noinput";
	public static final String RETRY_FIELD_NOMATCH = "Nomatch";
	public static final String REDIRECTINFO_FIELD_PRESENTATIONINFO = "presentationinfo";
	public static final String REDIRECTINFO_FIELD_REASON = "reason";
	public static final String REDIRECTINFO_FIELD_SCREENINGINFO = "screeninginfo";
	public static final String REDIRECTINFO_FIELD_URI = "uri";
	public static final String PROMPT_FIELD_CREDIT_ACC = "CreditAcc";
	public static final String PROMPT_FIELD_PROMPT___1 = "Prompt_1";
	public static final String PROMPT_FIELD_PROMPT___2 = "Prompt_2";
	public static final String PROMPT_FIELD_PROMPT___3 = "Prompt_3";
	public static final String PROMPT_FIELD_PROMPT___4 = "Prompt_4";
	public static final String PROMPT_FIELD_PROMPT___5 = "Prompt_5";
	public static final String PROMPT_FIELD_PROMPT___6 = "Prompt_6";
	public static final String PROMPT_FIELD_UNTITLED_6 = "untitled6";
	public static final String DATE_FIELD_AUDIO = "audio";
	public static final String DATE_FIELD_DAYOFMONTH = "dayofmonth";
	public static final String DATE_FIELD_DAYOFWEEK = "dayofweek";
	public static final String DATE_FIELD_DAYOFWEEKNUM = "dayofweeknum";
	public static final String DATE_FIELD_DAYOFYEAR = "dayofyear";
	public static final String DATE_FIELD_MONTH = "month";
	public static final String DATE_FIELD_MONTHINYEAR = "monthinyear";
	public static final String DATE_FIELD_YEAR = "year";
	public static final String PROMPT_URL_FIELD_BASE_URL = "BaseURL";
	public static final String PROMPT_URL_FIELD_PROMPT_COUNT = "PromptCount";
	public static final String PROMPT_URL_FIELD_PROMPT_FULL_URL = "PromptFullURL";
	public static final String FLAG_FIELD_TRASNFER_VDN = "TrasnferVDN";
	public static final String SESSION_FIELD_AAI = "aai";
	public static final String SESSION_FIELD_ANI = "ani";
	public static final String SESSION_FIELD_CALLTAG = "calltag";
	public static final String SESSION_FIELD_CHANNEL = "channel";
	public static final String SESSION_FIELD_CHANNELTYPE = "channeltype";
	public static final String SESSION_FIELD_CONVERSEFIRST = "conversefirst";
	public static final String SESSION_FIELD_CONVERSESECOND = "conversesecond";
	public static final String SESSION_FIELD_CURRENTLANGUAGE = "currentlanguage";
	public static final String SESSION_FIELD_DNIS = "dnis";
	public static final String SESSION_FIELD_EXIT_CUSTOMER_ID = "exitCustomerId";
	public static final String SESSION_FIELD_EXIT_INFO_1 = "exitInfo1";
	public static final String SESSION_FIELD_EXIT_INFO_2 = "exitInfo2";
	public static final String SESSION_FIELD_EXIT_PARENT_ID = "exitParentId";
	public static final String SESSION_FIELD_EXIT_PREFERRED_PATH = "exitPreferredPath";
	public static final String SESSION_FIELD_EXIT_REASON = "exitReason";
	public static final String SESSION_FIELD_EXIT_TOPIC = "exitTopic";
	public static final String SESSION_FIELD_LASTERROR = "lasterror";
	public static final String SESSION_FIELD_MEDIATYPE = "mediatype";
	public static final String SESSION_FIELD_PROTOCOLNAME = "protocolname";
	public static final String SESSION_FIELD_PROTOCOLVERSION = "protocolversion";
	public static final String SESSION_FIELD_SESSIONID = "sessionid";
	public static final String SESSION_FIELD_SESSIONLABEL = "sessionlabel";
	public static final String SESSION_FIELD_SHAREDMODE = "sharedmode";
	public static final String SESSION_FIELD_UCID = "ucid";
	public static final String SESSION_FIELD_UUI = "uui";
	public static final String SESSION_FIELD_VIDEOBITRATE = "videobitrate";
	public static final String SESSION_FIELD_VIDEOCODEC = "videocodec";
	public static final String SESSION_FIELD_VIDEOENABLED = "videoenabled";
	public static final String SESSION_FIELD_VIDEOFARFMTP = "videofarfmtp";
	public static final String SESSION_FIELD_VIDEOFORMAT = "videoformat";
	public static final String SESSION_FIELD_VIDEOFPS = "videofps";
	public static final String SESSION_FIELD_VIDEOHEIGHT = "videoheight";
	public static final String SESSION_FIELD_VIDEONEARFMTP = "videonearfmtp";
	public static final String SESSION_FIELD_VIDEOWIDTH = "videowidth";
	public static final String SESSION_FIELD_VPCALLEDEXTENSION = "vpcalledextension";
	public static final String SESSION_FIELD_VPCONVERSEONDATA = "vpconverseondata";
	public static final String SESSION_FIELD_VPCOVERAGEREASON = "vpcoveragereason";
	public static final String SESSION_FIELD_VPCOVERAGETYPE = "vpcoveragetype";
	public static final String SESSION_FIELD_VPRDNIS = "vprdnis";
	public static final String SESSION_FIELD_VPREPORTURL = "vpreporturl";
	public static final String VARIABLES_FIELD_CREDIT_CARD_LIST = "CreditCardList";
	public static final String VARIABLES_FIELD_CREDIT_CARD_LIST_PROMPT = "CreditCardListPrompt";
	public static final String VARIABLES_FIELD_EVENT_TYPE = "eventType";
	public static final String VARIABLES_FIELD_EXCEED_COUNT = "exceedCount";
	public static final String VARIABLES_FIELD_FINAL_FLAG = "FinalFlag";
	public static final String VARIABLES_FIELD_FLAG = "Flag";
	public static final String VARIABLES_FIELD_NEXT_PAGE = "NextPage";
	public static final String VARIABLES_FIELD_NO_AGENT = "NoAgent";
	public static final String VARIABLES_FIELD_PAGE_INDEX = "PageIndex";
	public static final String VARIABLES_FIELD_PAGE_SIZE = "PageSize";
	public static final String VARIABLES_FIELD_PAISA = "Paisa";
	public static final String VARIABLES_FIELD_PRESS = "press";
	public static final String VARIABLES_FIELD_PREVIOUS_PAGE = "PreviousPage";
	public static final String VARIABLES_FIELD_REPEAT = "Repeat";
	public static final String VARIABLES_FIELD_RETRY_COUNT = "retryCount";
	public static final String VARIABLES_FIELD_TRANSFER_FLAG = "TransferFlag";
	public static final String CREDIT_FIELD_AMOUNT = "Amount";
	public static final String CREDIT_FIELD_BALANCE = "balance";
	public static final String CREDIT_FIELD_RUPEES = "Rupees";
	public static final String CREDIT_FIELD_UNTITLED_3 = "untitled3";
	public static final String DD_LAST_EXCEPTION_FIELD_ERRORCODE = "errorcode";
	public static final String DD_LAST_EXCEPTION_FIELD_MESSAGE = "message";
	public static final String DD_LAST_EXCEPTION_FIELD_OBJECT = "object";
	public static final String DD_LAST_EXCEPTION_FIELD_STACKTRACE = "stacktrace";
	public static final String DD_LAST_EXCEPTION_FIELD_TYPE = "type";
	public static final String NODE_DETAILS_FIELD_API_STATUS = "ApiStatus";
	public static final String NODE_DETAILS_FIELD_DESCRIPTION = "Description";
	public static final String NODE_DETAILS_FIELD_FETCH_NODE = "FetchNode";
	public static final String NODE_DETAILS_FIELD_PROMPT_COUNT = "PromptCount";
	public static final String ACCOUNT_NUMBER_FIELD_ACCOUNT_NUMBER___1 = "AccountNumber_1";
	public static final String ACCOUNT_NUMBER_FIELD_ACCOUNT_NUMBER___2 = "AccountNumber_2";
	public static final String ACCOUNT_NUMBER_FIELD_ACCOUNT_NUMBER___3 = "AccountNumber_3";
	public static final String ACCOUNT_NUMBER_FIELD_ACCOUNT_NUMBER___4 = "AccountNumber_4";
	public static final String ACCOUNT_NUMBER_FIELD_ACCOUNT_NUMBER___5 = "AccountNumber_5";
	public static final String ACCOUNT_NUMBER_FIELD_BALANCE___1 = "Balance_1";
	public static final String ACCOUNT_NUMBER_FIELD_BALANCE___2 = "Balance_2";
	public static final String ACCOUNT_NUMBER_FIELD_BALANCE___3 = "Balance_3";
	public static final String ACCOUNT_NUMBER_FIELD_BALANCE___4 = "Balance_4";
	public static final String ACCOUNT_NUMBER_FIELD_PRESSCOUNT___1 = "presscount_1";
	public static final String ACCOUNT_NUMBER_FIELD_PRESSCOUNT___2 = "presscount_2";
	public static final String ACCOUNT_NUMBER_FIELD_PRESSCOUNT___3 = "presscount_3";
	public static final String ACCOUNT_NUMBER_FIELD_PRESSCOUNT___4 = "presscount_4";
	public static final String ACCOUNT_NUMBER_FIELD_PRESSCOUNT___5 = "presscount_5";
	public static final String ACCOUNT_NUMBER_FIELD_SELECTED___1 = "Selected_1";
	public static final String ACCOUNT_NUMBER_FIELD_SELECTED___2 = "Selected_2";
	public static final String ACCOUNT_NUMBER_FIELD_SELECTED___3 = "Selected_3";
	public static final String ACCOUNT_NUMBER_FIELD_SELECTED___4 = "Selected_4";
	public static final String TIME_FIELD_AUDIO = "audio";
	public static final String TIME_FIELD_HOUR = "hour";
	public static final String TIME_FIELD_MILLISECOND = "millisecond";
	public static final String TIME_FIELD_MINUTE = "minute";
	public static final String TIME_FIELD_SECOND = "second";
	public static final String TIME_FIELD_TIMEZONE = "timezone";
	public static final String API_FIELD_API_FAILED = "ApiFailed";
	public static final String API_FIELD_CCNUMBER = "CCNumber";
	public static final String API_FIELD_CREDIT_ACC_FLAG = "CreditAccFlag";
	public static final String API_FIELD_CREDITCARD_BALANCE = "CreditcardBalance";
	public static final String API_FIELD_RELATIONSHIP_ID = "RelationshipID";
	public static final String API_FIELD_RESPONSE = "Response";
	public static final String SHAREDUUI_FIELD_ID = "id";
	public static final String SHAREDUUI_FIELD_VALUE = "value";
	//}}END:PROJECT:VARIABLEFIELDS
}
