/**
 * Last generated by Orchestration Designer at: 2026-FEB-14  01:03:25 PM
 */
package english.prompts;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

public class DynamicPrompt extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for DynamicPrompt.
	 */
	public DynamicPrompt() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:59 AM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("DynamicPrompt");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}
	@Override
	public void updatePrompt(SCESession mySession) {
		super.updatePrompt(mySession);
		
		boolean HasTPIN=  (boolean) mySession.getProperty("HAS_TPIN");
		
		String description = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DESCRIPTION).getStringValue();
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO , "NODE DESCRIPTION : "+description, mySession);
		JSONObject nodeDetails = IVRFlow.getNodeByDescription(description);
        JSONArray Noprompts = nodeDetails.optJSONArray("menuPrompts");
        int totalPrompts = (Noprompts != null) ? Noprompts.length() : 0;
        int PromptCount = (Noprompts != null) ? Noprompts.length() : 0;
		
		String BaseURL = mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_BASE_URL).getStringValue();
    	
    	TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"******** FETCH NODE PROMPTS LANG IDENTIFIED ********", mySession);
    	if (Noprompts != null && Noprompts.length() > 0) {
    		
    		if ("TPIN_MENU".equalsIgnoreCase(description)) {

    		    for (int i = 0; i < Noprompts.length(); i++) {

    		        String setPrompt = "Prompt_" + (i + 1);
    		        String Prompt = mySession.getVariableField(IProjectVariables.PROMPT_URL, setPrompt).getStringValue();

    		        if (!HasTPIN) {
    		            String NotHasTPIN = mySession.getVariableField(
    		                    IProjectVariables.PROMPT_URL,
    		                    IProjectVariables.PROMPT_URL_FIELD_PROMPT___1
    		            ).getStringValue();

    		            // ✅ Check if already full path
    		            String promptlocation = (NotHasTPIN != null && NotHasTPIN.startsWith("/PromptFiles/"))
    		                    ? NotHasTPIN
    		                    : BaseURL + NotHasTPIN;

    		            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "PROMPT LOCATION : " + promptlocation, mySession);
    		            mySession.getVariableField(IProjectVariables.PROMPT_URL, IProjectVariables.PROMPT_URL_FIELD_PROMPT___1)
    		                    .setValue(promptlocation);

    		            add(1, new com.avaya.sce.runtime.PhraseVariableElement(
    		                    "PromptURL:Prompt_1",
    		                    com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL
    		            ));
    		            break;

    		        } else {
    		            // ✅ Check if already full path
    		            String promptlocation = (Prompt != null && Prompt.startsWith("/PromptFiles/"))
    		                    ? Prompt
    		                    : BaseURL + Prompt;

    		            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "PROMPT LOCATION : " + promptlocation, mySession);
    		            mySession.getVariableField(IProjectVariables.PROMPT_URL, setPrompt).setValue(promptlocation);

    		            add(1, new com.avaya.sce.runtime.PhraseVariableElement(
    		                    "PromptURL:Prompt_" + (i + 1),
    		                    com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL
    		            ));
    		        }

    		    }

    		} else {
    		    for (int i = 0; i < Noprompts.length(); i++) {

    		        String setPrompt = "Prompt_" + (i + 1);
    		        String Prompt = mySession.getVariableField(IProjectVariables.PROMPT_URL, setPrompt).getStringValue();

    		        // ✅ Check if already full path
    		        String promptlocation = (Prompt != null && Prompt.startsWith("/PromptFiles/"))
    		                ? Prompt
    		                : BaseURL + Prompt;

    		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "PROMPT LOCATION : " + promptlocation, mySession);
    		        mySession.getVariableField(IProjectVariables.PROMPT_URL, setPrompt).setValue(promptlocation);

    		        add(1, new com.avaya.sce.runtime.PhraseVariableElement(
    		                "PromptURL:Prompt_" + (i + 1),
    		                com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL
    		        ));
    		    }
    		}}}
    	
}
