package flow.subflow.RMN_Identification;

import java.util.List;

import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import DTO.IdentifyCustomerResponse;
import DTO.IdentifyCustomerResponse.Product;
import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-04  12:24:30 PM
 */
public class ExitPC001 extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-04  12:24:30 PM
	 */
	public ExitPC001() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("RMN_Identification-Api", "Default");
		next.setDebugId(140);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	
	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);
		
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Identification88888888888888888888888888888)",mySession);
     
		
		String APIResponse = mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_RESPONSE).getStringValue();
		
		String Number  = mySession.getVariableField(IProjectVariables.COLLECT__CC__OR__ACC,IProjectVariables.CC__OR__ACC__MENU_FIELD_VALUE).getStringValue();
		
		int CardorAcc  = mySession.getVariableField(IProjectVariables.CC__OR__ACC__MENU,IProjectVariables.CC__OR__ACC__MENU_FIELD_VALUE).getIntValue();
		
		IdentifyCustomerResponse storedResponse = 
			    (IdentifyCustomerResponse) mySession.getProperty("RMN_IDENTIFICATION");

			if (storedResponse != null && storedResponse.getData() != null && storedResponse.getData().getProducts() != null) {
			    
			    List<Product> products = storedResponse.getData().getProducts(); // Assuming getProducts() returns List<Product>
			    
			    boolean matched = false;
			    
			    for (Product product : products) {
			        // Check type based on CardorAcc
			        if ((CardorAcc == 1 && "AC".equalsIgnoreCase(product.getType())) ||
			            (CardorAcc == 2 && "CC".equalsIgnoreCase(product.getType()))) {
			            
			        	
			        	
			            String apiNumber = product.getNumber();
			           
			            
			            if (apiNumber != null && apiNumber.length() >= 4) {
			                String apiLast4 = apiNumber.substring(apiNumber.length() - 4);
			                TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"DB Customer Acc number : "+apiLast4+" = "+Number,mySession);
					        
			                
			                if (apiLast4.equals(Number)) {
			                    mySession.getVariableField(IProjectVariables.FLAG, IProjectVariables.FLAG_FIELD_IDENTIFICATION_FLAG)
			                             .setValue(true);
			                    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "Identification Success (Last 4 digits matched)", mySession);
			                    matched = true;
			                    break;
			                }
			            }
			        }
			    }
			    
			    if (!matched) {
			        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "Identification Failed (Last 4 digits not matched)", mySession);
			    }
			    
			} else {
			    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR, "RMNIdentificationResponse or Products list is null", mySession);
			}
	}

}
