package flow.subflow.RMN_Identification;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.Goto;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-04  12:36:19 AM
 */
public class RMNLoadValues extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-04  12:36:19 AM
	 */
	public RMNLoadValues() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("RMN_Identification-Validate", "Default");
		next.setDebugId(25);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	
	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);
		
		// Get Next Node Description
					String NextNodeDescription = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
					String PreferredLanguage = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_PREFERRED_LANGUAGE).getStringValue();
				
					
					IVRFlow IVR = new IVRFlow();
					JSONObject NodeDetails = IVRFlow.getNodeByDescription(NextNodeDescription);
					
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Node Details : " + NodeDetails.toString(),mySession);
					
					// Fetch the Next node
					String nextNode;

					if (NodeDetails.get("nextNode") instanceof JSONArray) {
					    nextNode = NodeDetails.getJSONArray("nextNode").getString(0);
					} else {
					    nextNode = NodeDetails.getString("nextNode");
					}

					mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).setValue(nextNode);

					String nodeType = NodeDetails.getString("ID");	
					
					
					// Fetch Prompt name
					JSONArray menuPrompts = NodeDetails.getJSONArray("menuPrompts");

					for (int i = 0; i < menuPrompts.length(); i++) {
					    String prompt = menuPrompts.getString(i);

					    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Prompt : " + prompt, mySession);
						TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Node Type : " + nodeType,mySession);   
						
						mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_PROMPT___1).setValue(prompt);
						
					}
					
					// Fetch Number of Options For Menu 
					if (nodeType.toUpperCase().startsWith("MEN")) {
						JSONArray menuDTMFArray = NodeDetails.getJSONArray("menuDTMF");

						int largestDTMF = 0;
						for (int i1 = 0; i1 < menuDTMFArray.length(); i1++) {
						    int value = Integer.parseInt(menuDTMFArray.getString(i1));
						    largestDTMF = Math.max(largestDTMF, value);
						}
						
						mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_NEXT_NODE).setValue(nodeType);
						TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,NextNodeDescription+" DTMF : " + largestDTMF,mySession);
						
						mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_DTMF).setValue(largestDTMF);
					}else {
						mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_NEXT_NODE).setValue(nodeType);
					}
						
				    mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_NEXT_NODE).setValue(nodeType);
					
					String SessionNextNode = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_NEXT_NODE).getStringValue();
					
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SessionNextNode : "+nodeType, mySession);

	}
}
