package flow.subflow.Identification;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-06  12:05:33 AM
 */
public class LoadValues extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-06  12:05:33 AM
	 */
	public LoadValues() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("Identification-Api", "Default");
		next.setDebugId(45);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);	
					String NextNodeDescription = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
				
					
					IVRFlow IVR = new IVRFlow();
					JSONObject NodeDetails = IVRFlow.getNodeByDescription(NextNodeDescription);
					
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Node Details : " + NodeDetails.toString(),mySession);
					
					boolean RMNFlag = mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_RMNFLAG).getBooleanValue();
					
					// Fetch the Next node
					String nextNode = null;

					if (NodeDetails.has("nextNode") && NodeDetails.get("nextNode") instanceof JSONArray) {

					    JSONArray nextNodeArray = NodeDetails.getJSONArray("nextNode");

					    if (nextNodeArray.length() == 1) {
					        nextNode = nextNodeArray.getString(0);
					        mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).setValue(nextNode);
					    } else if (nextNodeArray.length() >= 2) {
					        nextNode = RMNFlag ? nextNodeArray.getString(0) : nextNodeArray.getString(1);
					        mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).setValue(nextNode);
					    } else {
					    nextNode = NodeDetails.getString("nextNode");
						mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).setValue(nextNode);
					}



					String nodeType = NodeDetails.getString("ID");	
					
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Next Node : " + nextNode, mySession);	
									
					
				    mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_NEXT_NODE).setValue(nodeType);
				    
				    mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_NEXT_NODE).setValue(nodeType);
				    
				    String AuthFlag1 = mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_AUTHENTICATION_FLAG___1).getStringValue();
				    
				    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"AuthFlag1 : "+AuthFlag1, mySession);
				    
					String SessionNextNode = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_NEXT_NODE).getStringValue();
					
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SessionNextNode : "+nodeType, mySession);

	}
  }
}
