<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<module category="" descriptorversion="1.0" entrypoint="BankingApplication/Start" forcesubdialogcall="false" frameworkversion="08.12.11.01" iconlarge="icons/defaultapplicationlg.gif" iconsmall="icons/defaultapplicationsm.gif" modifyInputs="false" modifyOutputs="false" nature="com.avaya.sce.core.speechnature" outputmultipart="false" paramasnamelist="false" provider="" submitmethod="get" version="1.0.0" webname="BankingApplication">
    <description/>
    <language name="english" root="en-us"/>
    <dependencies>
        <moduleref frameworkversion="08.12.11.01" name="CreditCard" private="false" version="1.0.0">
            <meta callflow-references="main"/>
        </moduleref>
        <moduleref frameworkversion="08.12.11.01" name="BankingServices" private="false" version="1.0.0">
            <meta callflow-references="main"/>
        </moduleref>
        <moduleref frameworkversion="08.12.11.01" name="TPIN" private="false" version="1.0.0">
            <meta callflow-references="main"/>
        </moduleref>
    </dependencies>
</module>
