package flow.subflow.TPIN_Authentication;

/**
 * This servlet is used to forward the request to the entry point of a
 * project callflow (subflow).
 * Last generated by Orchestration Designer at: 2026-FEB-04  06:06:25 PM
 */
public class ApiRetryExcees extends com.avaya.sce.runtime.Subflow {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-04  06:06:25 PM
	 */
	public ApiRetryExcees() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the name of the subflow that is being invoked.  This name is used for
	 * determining the URL mapping for the the entry point of the subflow..
	 *
	 * @return the name of the subflow
	 * Last generated by Orchestration Designer at: 2026-FEB-18  12:55:49 AM
	 */
	protected String getSubflowName() {
		return("NIMM_API");
	}
	/**
	 * Returns the name of the mapping of sub flow exit points to the URL mappings
	 * of the servlets to return back to in the calling flow.
	 *
	 * @return map of sub flow exit points to servlets in the calling flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-18  12:55:49 AM
	 */
	protected java.util.Map<String,String> getExitPoints() {
		java.util.Map<String, String> exitPoints;
		exitPoints = new java.util.HashMap<String, String>();
		exitPoints.put("NIMM_API-max", "TPIN_Authentication-Maxtries");
		exitPoints.put("NIMM_API-repeat", "TPIN_Authentication-TPIN_AUTHENTICATION");
		return exitPoints;
	}
}
