package flow.subflow.TPIN_Authentication;

import java.util.ArrayList;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2026-FEB-05  01:59:21 AM
 */
public class FetchNodeForTpin extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-05  01:59:21 AM
	 */
	public FetchNodeForTpin() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Experienve Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2026-FEB-05  01:59:21 AM
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {

		// TODO: Add your code here!

	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("TPIN_Authentication-CheckNextNode", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
	private JSONArray safeArray(JSONObject obj, String key){

	    Object value = obj.opt(key);

	    if(value instanceof JSONArray){
	        return (JSONArray) value;
	    }

	    if(value instanceof String){

	        JSONArray arr = new JSONArray();

	        String str = (String)value;

	        if(str != null && !str.trim().isEmpty()){
	            arr.put(str);
	        }

	        return arr;
	    }

	    return new JSONArray(); // never return null
	}

	@Override
	public void requestBegin(SCESession mySession) {

	    super.requestBegin(mySession);

	    mySession.getVariableField(IProjectVariables.VARIABELS, IProjectVariables.VARIABELS_FIELD_RETRY_COUNT).setValue(0);
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	            "MAIN MENU FETCH FLOW", mySession);

	    try{
		    String OneFA = mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_ONE_FANAME).getStringValue();
		    boolean flag = mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_AUTHENTICATION_FLAG___1).getBooleanValue();
		    
		    
			if((OneFA.equalsIgnoreCase("OTP") || OneFA.equalsIgnoreCase("TPIN")) && flag) {
				mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_AUTHENTICATION_FLAG___2).setValue(true);	
		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"2FA IS DONE WITH : TPIN", mySession);
			}
			boolean TwoFA_Flag = mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_AUTHENTICATION_FLAG___2).getBooleanValue();
			mySession.setProperty("2FA_FLAG", TwoFA_Flag);
			
			mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_AUTHENTICATION_FLAG___1).setValue(true);
			mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_ONE_FANAME).setValue("TPIN");
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"1FA IS DONE WITH : TPIN", mySession);

	    }
	    catch(Exception e){

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                "ERROR IN FETCH NODE : " + e.getMessage(),
	                mySession);

	        e.printStackTrace();
	    }
	}

}
