package flow.subflow.TPIN_Authentication;

import java.io.PrintWriter;
import java.io.StringWriter;



import com.HostJar.API.api;
import com.HostJar.Flow.IVRFlow;
import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import DTO.TpinResponse;
import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-04  01:51:07 PM
 */
public class TpinAPI extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-04  01:51:07 PM
	 */
	public TpinAPI() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("TPIN_Authentication-Api", "Default");
		next.setDebugId(43);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	
	@Override
	public void requestBegin(SCESession mySession) {
	    super.requestBegin(mySession);
	    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "TPIN 5555555555555555: ", mySession);
	    String isEncrypted = Load.getInstance().getProperty("ENCRYPT_STATUS");
 
	    try {
                  
                 
       	        String token = mySession.getVariableField(IProjectVariables.OAUTH,IProjectVariables.OAUTH_FIELD_TOKEN).getStringValue();

	        String TPIN = mySession
	                .getVariableField(IProjectVariables.TPIN__AUTHENTICATION,
	                        IProjectVariables.TPIN__AUTHENTICATION_FIELD_VALUE)
	                .getStringValue();
 
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "TPIN : " + TPIN, mySession);
	        
	        
 
	        String RelationshipIDNRMN = mySession.getVariableField(IProjectVariables.API,IProjectVariables.API_FIELD_RELATIONSHIP_ID).getStringValue();
	        String RelationshipIDRMN = mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_RELATION_SHIP_ID).getStringValue();
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, " RMN: " + RelationshipIDRMN, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "NRMN: " + RelationshipIDNRMN, mySession);
	        
	        String relationshipIdValue = null;

	        if (RelationshipIDNRMN != null && !RelationshipIDNRMN.trim().isEmpty()) {
	            relationshipIdValue = RelationshipIDNRMN;
	        } else if (RelationshipIDRMN != null && !RelationshipIDRMN.trim().isEmpty()) {
	            relationshipIdValue = RelationshipIDRMN;
	        }
	        
	        
	        String requestTime = java.time.Instant.now().toString();
	        String ucid = mySession.getVariableField(IProjectVariables.SESSION,IProjectVariables.SESSION_FIELD_UCID).getStringValue();
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "TOKEN : " + token, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "IS_ENCRYPTED: " + isEncrypted, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "TPIN : " + TPIN, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "UCID : " + ucid, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "REQ TIME : " + requestTime, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "REL_ID: " + relationshipIdValue, mySession);
	        
	        TpinResponse response = api.ValidateTPIN(isEncrypted, TPIN, ucid, relationshipIdValue, requestTime);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "API Response : " + response, mySession);


	            String responseCode = response.getResponseCode();
	            mySession.getVariableField(IProjectVariables.API,IProjectVariables.API_FIELD_RESPONSE).setValue(responseCode);
	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "Response Code : " + responseCode, mySession);
	            String Res = mySession.getVariableField(IProjectVariables.API,IProjectVariables.API_FIELD_RESPONSE).getStringValue();
	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "Response Code session : " + Res, mySession);

	            
	            
 
	    } catch (Exception e) {
 
	        TraceInfo.trace(
	            ITraceInfo.TRACE_LEVEL_ERROR,
	            "API CALL FAILED"+e.getMessage(), mySession
	        );
	        String URL = mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_BASE_URL).getStringValue();
			 TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"URL : "+URL,mySession);
			 mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_API__STATUS).setValue(true);
				
				if (URL.equalsIgnoreCase("/Prompts/ENGLISH/")) {
					String VDN = IVRFlow.getTransferVDN("ENGLISH","VALIDATE_OTP");
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS ENGLISH VDN : "+VDN,mySession);
					mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRANSFER_VDN).setValue(VDN);
				}else if (URL.equalsIgnoreCase("/Prompts/HINDI/")) {
					String VDN = IVRFlow.getTransferVDN("HINDI","VALIDATE_OTP");
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS HINDI VDN : "+VDN,mySession);
					mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRANSFER_VDN).setValue(VDN);
				}else {
					String VDN = IVRFlow.getTransferVDN("DEFAULT","VALIDATE_OTP");
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS DEFAULT VDN : "+VDN,mySession);
					mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRANSFER_VDN).setValue(VDN);
				}
	    }}
	
}
