package flow;

import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-06  07:35:26 PM
 */
public class CheckNode extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-06  07:35:26 PM
	 */
	public CheckNode() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("Validate", "Default");
		next.setDebugId(399);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
		super.requestBegin(mySession);
		String menu = mySession.getVariableField(IProjectVariables.CALL_HISTORY, IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).getStringValue();
		String MENU_DESCRIPTION = (String) mySession.getProperty("MENU_DESCRIPTION");  
		String DISPOSITION_TYPE =	(String) mySession.getProperty("DISPOSITION_TYPE"); 
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "MENU_DESCRIPTION" + MENU_DESCRIPTION, mySession);
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "DISPOSITION_TYPE : " + DISPOSITION_TYPE, mySession);

		mySession.getVariableField(IProjectVariables.CALL_HISTORY, IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).setValue(menu+MENU_DESCRIPTION);
		
		String FullDescription = mySession.getVariableField(IProjectVariables.CALL_HISTORY, IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION).getStringValue();
		
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "FULL_MENU_DESCRIPTION" + FullDescription, mySession);
		
		boolean TwoFA = (boolean) mySession.getProperty("2FA_FLAG");
		
		String NextNode = (String) mySession.getProperty("JSON");
		
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "2FA_FLAG : " + TwoFA, mySession);
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "NEXT NODE : " + NextNode, mySession);
		mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).setValue(NextNode);
		
		if(!TwoFA) {
			mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).setValue("AUTHENTICATION");
		}
		
		String NextNodeName = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "NEXT_NODE_NAME : " + NextNodeName, mySession);  
		
		mySession.getVariableField(IProjectVariables.TPIN___2FA,IProjectVariables.TPIN___2FA_FIELD_STATUS).setValue(TwoFA);

		
	}
}
