package flow;

import java.util.Collection;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.Flow.IVRFlow;
import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.Goto;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2026-FEB-01  08:07:10 PM
 */
public class FetchNode extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-01  08:07:10 PM
	 */
	public FetchNode() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Experienve Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2026-FEB-01  08:07:10 PM
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {

		// TODO: Add your code here!

	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2026-FEB-12  08:20:37 PM
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("End", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
	@Override
	public void updateBranches(Collection branches, SCESession mySession) {

    	Goto aGoto = null;
		boolean error = false;		
		try {
			// Get Node Details 
			String nodeType = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_ID).getStringValue();
			String NextNode = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE).getStringValue();
			String preferredLanguage =mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_PREFERRED_LANGUAGE).getStringValue();
			
			
			
			//Check Preferred Language
			if(preferredLanguage != null && !NextNode.equalsIgnoreCase("LANGUAGE_MENU")) {
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"*******Has Preferred Language Goto GENERAL_MSG*******",mySession);
				
				aGoto = new Goto("GENERAL_MSG", 0); // If the customer has preferred language Routing the call to GENERAL_MSG
				branches.clear();
				branches.add(aGoto);
				super.updateBranches(branches, mySession);
				return;
			}
			
			
			
			// Routing Logics
			if (nodeType.toUpperCase().startsWith("ANN")) {
				aGoto = new Goto("ANN", 0);
				branches.clear();
				branches.add(aGoto);
				super.updateBranches(branches, mySession);
				return;
			}else if(nodeType.toUpperCase().startsWith("MEN")) {
				aGoto = new Goto("MEN", 0);
				branches.clear();
				branches.add(aGoto);
				super.updateBranches(branches, mySession);
				return;
			}else if(nodeType.toUpperCase().startsWith("PC")) {
				aGoto = new Goto("PC", 0);
				branches.clear();
				branches.add(aGoto);
				super.updateBranches(branches, mySession);
				return;
			}

		} catch(Exception e) {

			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"Error on Getting Next Node", mySession);
			mySession.getVariableField("Error").setValue(true);
			aGoto = new Goto("SetTechDiffPrompt", 0);
			branches.clear();
			branches.add(aGoto);
			
		}

		super.updateBranches(branches, mySession);
	}
}
