package flow;


import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import DTO.CallHistoryDao;



/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-18  12:09:38 AM
 */
public class InsertCallHistory extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-18  12:09:38 AM
	 */
	public InsertCallHistory() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("End", "Default");
		next.setDebugId(422);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {

		TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "DISCONNECTTTTTTTT ", mySession);
	    super.requestBegin(mySession);

	    
	    // Formatter must match Timestamp.valueOf()
	    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

	    // Set end time
	    String callEndTime = sdf.format(new Date());
	    mySession.getVariableField(
	            IProjectVariables.CALL_HISTORY,
	            IProjectVariables.CALL_HISTORY_FIELD_END_DATE
	    ).setValue(callEndTime);

	    try {

	        String ucid = mySession.getVariableField(
	                IProjectVariables.SESSION,
	                IProjectVariables.SESSION_FIELD_UCID
	        ).getStringValue();

	        String clid = mySession.getVariableField(
	                IProjectVariables.SESSION,
	                IProjectVariables.SESSION_FIELD_ANI
	        ).getStringValue();

	        String dnis = mySession.getVariableField(
	                IProjectVariables.SESSION,
	                IProjectVariables.SESSION_FIELD_DNIS
	        ).getStringValue();

	        String startDate = mySession.getVariableField(
	                IProjectVariables.CALL_HISTORY,
	                IProjectVariables.CALL_HISTORY_FIELD_START_DATE
	        ).getStringValue();

	        String endDate = mySession.getVariableField(
	                IProjectVariables.CALL_HISTORY,
	                IProjectVariables.CALL_HISTORY_FIELD_END_DATE
	        ).getStringValue();

	        if (startDate == null || startDate.isEmpty()
	                || endDate == null || endDate.isEmpty()) {

	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                    "StartDate or EndDate is NULL/EMPTY", mySession);
	            return;
	        }

	        // ✅ Convert String → Timestamp (FIX)
	        Timestamp startTimestamp = Timestamp.valueOf(startDate);
	        Timestamp endTimestamp   = Timestamp.valueOf(endDate);

	        // ✅ Safe initialization
	        int callDuration = 0;

	        try {
	            callDuration = (int)
	                    ((endTimestamp.getTime() - startTimestamp.getTime()) / 1000);

	            mySession.getVariableField(
	                    IProjectVariables.CALL_HISTORY,
	                    IProjectVariables.CALL_HISTORY_FIELD_CALL_DURATION
	            ).setValue(callDuration);

	        } catch (Exception e) {
	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                    "CALL DURATION ERROR : " + e.getMessage(), mySession);
	        }

	        String dispositionType = mySession.getVariableField(
	                IProjectVariables.CALL_HISTORY,
	                IProjectVariables.CALL_HISTORY_FIELD_DISPOSITION_TYPE
	        ).getStringValue();

	        String menuDescription = mySession.getVariableField(
	                IProjectVariables.CALL_HISTORY,
	                IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION
	        ).getStringValue();

	        String exitLocation = mySession.getVariableField(
	                IProjectVariables.CALL_HISTORY,
	                IProjectVariables.CALL_HISTORY_FIELD_EXIT_LOCATION
	        ).getStringValue();

	        String sessionId = mySession.getVariableField(
	                IProjectVariables.SESSION,
	                IProjectVariables.SESSION_FIELD_SESSIONID
	        ).getStringValue();

	        String ip = mySession.getVariableField(IProjectVariables.CALL_HISTORY, IProjectVariables.CALL_HISTORY_FIELD_IP).getStringValue();
	        boolean rmnFlag = mySession.getVariableField(
	                IProjectVariables.RMNIDENTIFICATION,
	                IProjectVariables.RMNIDENTIFICATION_FIELD_RMNFLAG
	        ).getBooleanValue();

	        String language = mySession.getVariableField(
	                IProjectVariables.CALL_HISTORY,
	                IProjectVariables.CALL_HISTORY_FIELD_LANGUAGE
	        ).getStringValue();

	        String transferVDN = mySession.getVariableField(
	                IProjectVariables.CALL_HISTORY,
	                IProjectVariables.CALL_HISTORY_FIELD_TRANSFER_VDN).getStringValue();

	        menuDescription = menuDescription + "| END";

	        mySession.getVariableField(
	                IProjectVariables.CALL_HISTORY,
	                IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION
	        ).setValue(menuDescription);

	        // -------- DAO INSERT --------
	        CallHistoryDao dao = new CallHistoryDao();

	        boolean callHistoryInserted = dao.insertCallHistory(
	                ucid,
	                clid,
	                dnis,
	                language,
	                startTimestamp,   // ✅ FIXED
	                endTimestamp,     // ✅ FIXED
	                callDuration,
	                menuDescription,
	                exitLocation,
	                ip,
	                sessionId,
	                rmnFlag,
	                transferVDN,
	                dispositionType
	        );

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "CALL HISTORY INSERTED : " + callHistoryInserted,
	                mySession);

	  
	

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "UCID: " + ucid, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "CLID: " + clid, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "DNIS: " + dnis, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "STARTDATE: " + startDate, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "ENDDATE: " + endDate, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "CALLDURATION: " + callDuration, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "MENUD: " + menuDescription, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "EXITLOCATION: " + exitLocation, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "IP: " + ip, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "SESSIONID: " + sessionId, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "ENDREASON: " + dispositionType, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "RMNFLAG: " + rmnFlag, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "DATA INSERTED", mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "Call end: " + callEndTime, mySession);
	       	        

	    } catch (Exception e) {
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR, "DB Error: " + e.toString(), mySession);
	       
	    }
	}
}
