package flow;

/**
 * This interface is used to define the name of variables that are 
 * declared in the call flow.  All variables are defined as 
 * <code>public static final String</code>, which allows user-defined
 * code to reference variable names by the Java variable name.
 * Last generated by Orchestration Designer at: 2026-FEB-01  06:53:38 PM
 */
public interface IProjectVariables {





	//{{START:PROJECT:VARIABLES
	/**
	 * This is a reserved block of variable name definitions.
	 * The variable names defined here can be used as the key
	 * to get the <code>com.avaya.sce.runtime.Variable</code>
	 * from the <code>SCESession</code> at runtime.<br>
	 * 
	 * For example, given a variable name <code>phoneNum</code>,
	 * user-defined code should access the variable in this format:<PRE>
	 *   Variable phNum = mySession.getVariable(IProjectVariables.PHONE_NUM);
	 *   if ( phNum != null ) {
	 *        // do something with the variable
	 *   }</PRE>
	 * 
	 * This block of code is generated automatically by Orchestration Designer and should not
	 * be manually edited as changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public static final String TPIN___2FA = "TPIN_2FA";
	public static final String GENERATE_OTP = "GenerateOTP";
	public static final String CC__OR__ACC__MENU = "CC_OR_ACC_MENU";
	public static final String PRODUCT_CODE = "ProductCode";
	public static final String RMNIDENTIFICATION = "RMNIdentification";
	public static final String CALL_HISTORY = "CallHistory";
	public static final String TRANSFER = "Transfer";
	public static final String RETRY = "Retry";
	public static final String COLLECT__CC__OR__ACC = "Collect_cc_or_Acc";
	public static final String REDIRECTINFO = "redirectinfo";
	public static final String PROMPT_HIN_URL = "PromptHinURL";
	public static final String VARIABELS = "Variabels";
	public static final String PROMPT = "Prompt";
	public static final String DATE = "date";
	public static final String TPIN = "TPIN";
	public static final String PRESS_3 = "Press3";
	public static final String COLLECT__OTP = "COLLECT_OTP";
	public static final String PROMPT_URL = "PromptURL";
	public static final String PRESS_1 = "Press1";
	public static final String FLAG = "Flag";
	public static final String TPIN__AUTHENTICATION = "TPIN_AUTHENTICATION";
	public static final String NRMN__IDENTIFICATIONCOPY = "NRMN_IDENTIFICATIONCopy";
	public static final String DYNAMIC = "Dynamic";
	public static final String SESSION = "session";
	public static final String PRESS_2 = "press2";
	public static final String NODE_DETAILS = "NodeDetails";
	public static final String DD_LAST_EXCEPTION = "ddLastException";
	public static final String OAUTH = "OAuth";
	public static final String TIME = "time";
	public static final String API = "Api";
	public static final String SHAREDUUI = "shareduui";
	//}}END:PROJECT:VARIABLES

	//{{START:PROJECT:VARIABLEFIELDS
	public static final String TPIN___2FA_FIELD_STATUS = "Status";
	public static final String GENERATE_OTP_FIELD_COUNT = "Count";
	public static final String GENERATE_OTP_FIELD_OTP = "OTP";
	public static final String GENERATE_OTP_FIELD_OTPREFERENCE = "OTPReference";
	public static final String CC__OR__ACC__MENU_FIELD_CONFIDENCE = "confidence";
	public static final String CC__OR__ACC__MENU_FIELD_INPUTMODE = "inputmode";
	public static final String CC__OR__ACC__MENU_FIELD_INTERPRETATION = "interpretation";
	public static final String CC__OR__ACC__MENU_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String CC__OR__ACC__MENU_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String CC__OR__ACC__MENU_FIELD_UTTERANCE = "utterance";
	public static final String CC__OR__ACC__MENU_FIELD_VALUE = "value";
	public static final String PRODUCT_CODE_FIELD_ACCOUNT = "Account";
	public static final String PRODUCT_CODE_FIELD_CREDIT_CARD = "CreditCard";
	public static final String PRODUCT_CODE_FIELD_MENU_SERVICE = "MenuService";
	public static final String RMNIDENTIFICATION_FIELD_HAS_TPIN = "HasTPIN";
	public static final String RMNIDENTIFICATION_FIELD_MOBILE_NUMBER = "MobileNumber";
	public static final String RMNIDENTIFICATION_FIELD_RELATION_SHIP_ID = "RelationShipID";
	public static final String RMNIDENTIFICATION_FIELD_RESPONSE = "Response";
	public static final String RMNIDENTIFICATION_FIELD_RMNFLAG = "RMNFlag";
	public static final String CALL_HISTORY_FIELD_CALL_DURATION = "callDuration";
	public static final String CALL_HISTORY_FIELD_DISPOSITION_TYPE = "dispositionType";
	public static final String CALL_HISTORY_FIELD_END_DATE = "endDate";
	public static final String CALL_HISTORY_FIELD_END_REASON = "endReason";
	public static final String CALL_HISTORY_FIELD_EXIT_LOCATION = "exitLocation";
	public static final String CALL_HISTORY_FIELD_IP = "ip";
	public static final String CALL_HISTORY_FIELD_LANGUAGE = "language";
	public static final String CALL_HISTORY_FIELD_MENU_DESCRIPTION = "menuDescription";
	public static final String CALL_HISTORY_FIELD_START_DATE = "startDate";
	public static final String CALL_HISTORY_FIELD_TRANSFER_VDN = "transferVdn";
	public static final String RETRY_FIELD_INVALID_NUMBER = "invalidNumber";
	public static final String RETRY_FIELD_MAX = "max";
	public static final String RETRY_FIELD_NOINPUT = "Noinput";
	public static final String RETRY_FIELD_NOMATCH = "Nomatch";
	public static final String COLLECT__CC__OR__ACC_FIELD_CONFIDENCE = "confidence";
	public static final String COLLECT__CC__OR__ACC_FIELD_INPUTMODE = "inputmode";
	public static final String COLLECT__CC__OR__ACC_FIELD_INTERPRETATION = "interpretation";
	public static final String COLLECT__CC__OR__ACC_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String COLLECT__CC__OR__ACC_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String COLLECT__CC__OR__ACC_FIELD_UTTERANCE = "utterance";
	public static final String COLLECT__CC__OR__ACC_FIELD_VALUE = "value";
	public static final String REDIRECTINFO_FIELD_PRESENTATIONINFO = "presentationinfo";
	public static final String REDIRECTINFO_FIELD_REASON = "reason";
	public static final String REDIRECTINFO_FIELD_SCREENINGINFO = "screeninginfo";
	public static final String REDIRECTINFO_FIELD_URI = "uri";
	public static final String PROMPT_HIN_URL_FIELD_PROMPT___1 = "Prompt_1";
	public static final String PROMPT_HIN_URL_FIELD_PROMPT___1_0 = "Prompt_10";
	public static final String PROMPT_HIN_URL_FIELD_PROMPT___2 = "Prompt_2";
	public static final String PROMPT_HIN_URL_FIELD_PROMPT___3 = "Prompt_3";
	public static final String PROMPT_HIN_URL_FIELD_PROMPT___4 = "Prompt_4";
	public static final String PROMPT_HIN_URL_FIELD_PROMPT___5 = "Prompt_5";
	public static final String PROMPT_HIN_URL_FIELD_PROMPT___6 = "Prompt_6";
	public static final String PROMPT_HIN_URL_FIELD_PROMPT___7 = "Prompt_7";
	public static final String PROMPT_HIN_URL_FIELD_PROMPT___8 = "Prompt_8";
	public static final String PROMPT_HIN_URL_FIELD_PROMPT___9 = "Prompt_9";
	public static final String VARIABELS_FIELD_EMG_FLAG = "emgFlag";
	public static final String VARIABELS_FIELD_EVENT_TYPE = "eventType";
	public static final String VARIABELS_FIELD_EXCEED_COUNT = "exceedCount";
	public static final String VARIABELS_FIELD_EXCEED_MAX = "exceedMax";
	public static final String VARIABELS_FIELD_FINAL_FLAG = "finalFlag";
	public static final String VARIABELS_FIELD_MAIN_MENU_OPTIONS = "MainMenuOptions";
	public static final String VARIABELS_FIELD_NO_AGENT = "NoAgent";
	public static final String VARIABELS_FIELD_RETRY_COUNT = "retryCount";
	public static final String VARIABELS_FIELD_RETRY_COUNT__API = "retryCount_api";
	public static final String VARIABELS_FIELD_TPIN = "TPIN";
	public static final String VARIABELS_FIELD_TRANSFER_FLAG = "TransferFlag";
	public static final String PROMPT_FIELD_PROMPT___1 = "Prompt_1";
	public static final String PROMPT_FIELD_PROMPT___2 = "Prompt_2";
	public static final String PROMPT_FIELD_PROMPT___3 = "Prompt_3";
	public static final String PROMPT_FIELD_PROMPT___4 = "Prompt_4";
	public static final String PROMPT_FIELD_PROMPT___5 = "Prompt_5";
	public static final String DATE_FIELD_AUDIO = "audio";
	public static final String DATE_FIELD_DAYOFMONTH = "dayofmonth";
	public static final String DATE_FIELD_DAYOFWEEK = "dayofweek";
	public static final String DATE_FIELD_DAYOFWEEKNUM = "dayofweeknum";
	public static final String DATE_FIELD_DAYOFYEAR = "dayofyear";
	public static final String DATE_FIELD_MONTH = "month";
	public static final String DATE_FIELD_MONTHINYEAR = "monthinyear";
	public static final String DATE_FIELD_YEAR = "year";
	public static final String TPIN_FIELD_GOTO_TPIN = "GotoTPIN";
	public static final String COLLECT__OTP_FIELD_CONFIDENCE = "confidence";
	public static final String COLLECT__OTP_FIELD_INPUTMODE = "inputmode";
	public static final String COLLECT__OTP_FIELD_INTERPRETATION = "interpretation";
	public static final String COLLECT__OTP_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String COLLECT__OTP_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String COLLECT__OTP_FIELD_UTTERANCE = "utterance";
	public static final String COLLECT__OTP_FIELD_VALUE = "value";
	public static final String PROMPT_URL_FIELD_BASE_URL = "BaseURL";
	public static final String PROMPT_URL_FIELD_ENG_BASE_URL = "EngBaseURL";
	public static final String PROMPT_URL_FIELD_HINDI_BASE_URL = "HindiBaseURL";
	public static final String PROMPT_URL_FIELD_PROMPT___1 = "Prompt_1";
	public static final String PROMPT_URL_FIELD_PROMPT___1_0 = "Prompt_10";
	public static final String PROMPT_URL_FIELD_PROMPT___2 = "Prompt_2";
	public static final String PROMPT_URL_FIELD_PROMPT___3 = "Prompt_3";
	public static final String PROMPT_URL_FIELD_PROMPT___4 = "Prompt_4";
	public static final String PROMPT_URL_FIELD_PROMPT___5 = "Prompt_5";
	public static final String PROMPT_URL_FIELD_PROMPT___6 = "Prompt_6";
	public static final String PROMPT_URL_FIELD_PROMPT___7 = "Prompt_7";
	public static final String PROMPT_URL_FIELD_PROMPT___8 = "Prompt_8";
	public static final String PROMPT_URL_FIELD_PROMPT___9 = "Prompt_9";
	public static final String PROMPT_URL_FIELD_PROMPT_COUNT = "PromptCount";
	public static final String PROMPT_URL_FIELD_PROMPT_FULL_URL = "PromptFullURL";
	public static final String FLAG_FIELD_AUTHENTICATION_FLAG___1 = "AuthenticationFlag_1";
	public static final String FLAG_FIELD_AUTHENTICATION_FLAG___2 = "AuthenticationFlag_2";
	public static final String FLAG_FIELD_COUNT = "Count";
	public static final String FLAG_FIELD_HAS_BANKING = "hasBanking";
	public static final String FLAG_FIELD_HAS_CREDIT = "hasCredit";
	public static final String FLAG_FIELD_IDENTIFICATION_FLAG = "IdentificationFlag";
	public static final String FLAG_FIELD_NEXT_NODE = "NextNode";
	public static final String FLAG_FIELD_ONE_FANAME = "OneFAName";
	public static final String FLAG_FIELD_OTPFLAG = "OTPFlag";
	public static final String FLAG_FIELD_RETRY_FLAG = "RetryFlag";
	public static final String FLAG_FIELD_TRANSFER_VDN = "TransferVDN";
	public static final String TPIN__AUTHENTICATION_FIELD_CONFIDENCE = "confidence";
	public static final String TPIN__AUTHENTICATION_FIELD_INPUTMODE = "inputmode";
	public static final String TPIN__AUTHENTICATION_FIELD_INTERPRETATION = "interpretation";
	public static final String TPIN__AUTHENTICATION_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String TPIN__AUTHENTICATION_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String TPIN__AUTHENTICATION_FIELD_UTTERANCE = "utterance";
	public static final String TPIN__AUTHENTICATION_FIELD_VALUE = "value";
	public static final String NRMN__IDENTIFICATIONCOPY_FIELD_CONFIDENCE = "confidence";
	public static final String NRMN__IDENTIFICATIONCOPY_FIELD_INPUTMODE = "inputmode";
	public static final String NRMN__IDENTIFICATIONCOPY_FIELD_INTERPRETATION = "interpretation";
	public static final String NRMN__IDENTIFICATIONCOPY_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String NRMN__IDENTIFICATIONCOPY_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String NRMN__IDENTIFICATIONCOPY_FIELD_UTTERANCE = "utterance";
	public static final String NRMN__IDENTIFICATIONCOPY_FIELD_VALUE = "value";
	public static final String DYNAMIC_FIELD_CONFIDENCE = "confidence";
	public static final String DYNAMIC_FIELD_INPUTMODE = "inputmode";
	public static final String DYNAMIC_FIELD_INTERPRETATION = "interpretation";
	public static final String DYNAMIC_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String DYNAMIC_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String DYNAMIC_FIELD_UTTERANCE = "utterance";
	public static final String DYNAMIC_FIELD_VALUE = "value";
	public static final String SESSION_FIELD_AAI = "aai";
	public static final String SESSION_FIELD_ANI = "ani";
	public static final String SESSION_FIELD_CALLTAG = "calltag";
	public static final String SESSION_FIELD_CHANNEL = "channel";
	public static final String SESSION_FIELD_CHANNELTYPE = "channeltype";
	public static final String SESSION_FIELD_CONVERSEFIRST = "conversefirst";
	public static final String SESSION_FIELD_CONVERSESECOND = "conversesecond";
	public static final String SESSION_FIELD_CURRENTLANGUAGE = "currentlanguage";
	public static final String SESSION_FIELD_DNIS = "dnis";
	public static final String SESSION_FIELD_EXIT_CUSTOMER_ID = "exitCustomerId";
	public static final String SESSION_FIELD_EXIT_INFO_1 = "exitInfo1";
	public static final String SESSION_FIELD_EXIT_INFO_2 = "exitInfo2";
	public static final String SESSION_FIELD_EXIT_PARENT_ID = "exitParentId";
	public static final String SESSION_FIELD_EXIT_PREFERRED_PATH = "exitPreferredPath";
	public static final String SESSION_FIELD_EXIT_REASON = "exitReason";
	public static final String SESSION_FIELD_EXIT_TOPIC = "exitTopic";
	public static final String SESSION_FIELD_LASTERROR = "lasterror";
	public static final String SESSION_FIELD_MEDIATYPE = "mediatype";
	public static final String SESSION_FIELD_PROTOCOLNAME = "protocolname";
	public static final String SESSION_FIELD_PROTOCOLVERSION = "protocolversion";
	public static final String SESSION_FIELD_SESSIONID = "sessionid";
	public static final String SESSION_FIELD_SESSIONLABEL = "sessionlabel";
	public static final String SESSION_FIELD_SHAREDMODE = "sharedmode";
	public static final String SESSION_FIELD_UCID = "ucid";
	public static final String SESSION_FIELD_UUI = "uui";
	public static final String SESSION_FIELD_VIDEOBITRATE = "videobitrate";
	public static final String SESSION_FIELD_VIDEOCODEC = "videocodec";
	public static final String SESSION_FIELD_VIDEOENABLED = "videoenabled";
	public static final String SESSION_FIELD_VIDEOFARFMTP = "videofarfmtp";
	public static final String SESSION_FIELD_VIDEOFORMAT = "videoformat";
	public static final String SESSION_FIELD_VIDEOFPS = "videofps";
	public static final String SESSION_FIELD_VIDEOHEIGHT = "videoheight";
	public static final String SESSION_FIELD_VIDEONEARFMTP = "videonearfmtp";
	public static final String SESSION_FIELD_VIDEOWIDTH = "videowidth";
	public static final String SESSION_FIELD_VPCALLEDEXTENSION = "vpcalledextension";
	public static final String SESSION_FIELD_VPCONVERSEONDATA = "vpconverseondata";
	public static final String SESSION_FIELD_VPCOVERAGEREASON = "vpcoveragereason";
	public static final String SESSION_FIELD_VPCOVERAGETYPE = "vpcoveragetype";
	public static final String SESSION_FIELD_VPRDNIS = "vprdnis";
	public static final String SESSION_FIELD_VPREPORTURL = "vpreporturl";
	public static final String NODE_DETAILS_FIELD_API__STATUS = "API_Status";
	public static final String NODE_DETAILS_FIELD_DESCRIPTION = "Description";
	public static final String NODE_DETAILS_FIELD_DTMF = "DTMF";
	public static final String NODE_DETAILS_FIELD_FETCH_NEXTNODE = "FetchNextnode";
	public static final String NODE_DETAILS_FIELD_ID = "ID";
	public static final String NODE_DETAILS_FIELD_LANGUAGE = "Language";
	public static final String NODE_DETAILS_FIELD_NEXT_NODE = "NextNode";
	public static final String NODE_DETAILS_FIELD_PREFERRED_LANGUAGE = "PreferredLanguage";
	public static final String DD_LAST_EXCEPTION_FIELD_ERRORCODE = "errorcode";
	public static final String DD_LAST_EXCEPTION_FIELD_MESSAGE = "message";
	public static final String DD_LAST_EXCEPTION_FIELD_OBJECT = "object";
	public static final String DD_LAST_EXCEPTION_FIELD_STACKTRACE = "stacktrace";
	public static final String DD_LAST_EXCEPTION_FIELD_TYPE = "type";
	public static final String OAUTH_FIELD_TOKEN = "token";
	public static final String TIME_FIELD_AUDIO = "audio";
	public static final String TIME_FIELD_HOUR = "hour";
	public static final String TIME_FIELD_MILLISECOND = "millisecond";
	public static final String TIME_FIELD_MINUTE = "minute";
	public static final String TIME_FIELD_SECOND = "second";
	public static final String TIME_FIELD_TIMEZONE = "timezone";
	public static final String API_FIELD_API_FAILED = "ApiFailed";
	public static final String API_FIELD_RELATIONSHIP_ID = "RelationshipID";
	public static final String API_FIELD_RESPONSE = "Response";
	public static final String SHAREDUUI_FIELD_ID = "id";
	public static final String SHAREDUUI_FIELD_VALUE = "value";
	//}}END:PROJECT:VARIABLEFIELDS

}
