package flow;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;

import javax.servlet.ServletContext;

import org.apache.logging.log4j.core.Logger;

import com.HostJar.API.api;
import com.HostJar.LoadValues.Load;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import DTO.IdentifyCustomerResponse;
import DTO.IdentifyCustomerResponse.Product;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-06  04:15:37 PM
 */
public class LoadValues extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-06  04:15:37 PM
	 */
	public LoadValues() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("DynamicNextNode", "Default");
		next.setDebugId(385);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {
		// TODO Auto-generated method stub
		super.requestBegin(mySession);
		
		try {
			
				SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
				String callStartTime = sdf.format(new Date());
				 
				mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_START_DATE).setValue(callStartTime);
				InetAddress ip = null;
				try {
					ip = InetAddress.getLocalHost();
				} catch (UnknownHostException e) {
					e.printStackTrace();
				}
			    String servip = ip.getHostAddress();
			    mySession.getVariableField(IProjectVariables.CALL_HISTORY,IProjectVariables.CALL_HISTORY_FIELD_IP).setValue(servip);
			    TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "ip is" +servip, mySession);
			try {
			       
				
		        ServletContext context = mySession.getServlet().getServletContext();

		        // Fetch the context-param value
		        String propertyFilePath = context.getInitParameter("PropertyFile");

		        // Log it
		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "Property File Path: " + propertyFilePath, mySession);
		        Load.getInstance().loadConfig(propertyFilePath);

		    } catch (Exception e) {
		        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR, "Error fetching Property File Path: " + e, mySession);
		    }
			
			
		mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_ENG_BASE_URL).setValue(Load.getInstance().getProperty("PROMPT_ENG"));
		mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_HINDI_BASE_URL).setValue(Load.getInstance().getProperty("PROMPT_HIN"));
		
		String Ani_Number = mySession.getVariableField(IProjectVariables.SESSION,IProjectVariables.SESSION_FIELD_ANI).getStringValue();
		String MobileNumber = "";
		
		if(Ani_Number.equalsIgnoreCase("1201")) {
			MobileNumber = Load.getInstance().getProperty("1201");
		}else if(Ani_Number.equalsIgnoreCase("1202")) {
			MobileNumber = Load.getInstance().getProperty("1202");
		}else {
			MobileNumber = Ani_Number;
		}
			
//		 api.createSecureHttpClient();
//		 

		    
	        LocalDateTime currentTime = LocalDateTime.now();
	        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
	        String requesttime = currentTime.format(formatter);
	        
	        String UCID = mySession.getVariableField(IProjectVariables.SESSION,IProjectVariables.SESSION_FIELD_UCID).getStringValue();
		    
			IdentifyCustomerResponse Response = api.RMNIdentificationAPI( UCID, MobileNumber, requesttime);

			
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"RMNIdentification API Response : " + Response,mySession);
			
			mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_RESPONSE).setValue(Response);

		
		    String ApiSessionResponse = mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_RESPONSE).getStringValue();

			//JSONObject json = new JSONObject(Response);
			
			String responseCode = Response.getResponseCode();
			mySession.setProperty("RMN_IDENTIFICATION", Response);
			if(responseCode.equalsIgnoreCase("0000")) {
				
			//JSONObject data = json.optJSONObject("data");
			
			String ResponseMobileNumber =Response.getData().getMobileNumber();
			
			boolean isRMN = Response.getData().isRMN();
			boolean hasTPIN = Response.getData().getHasTPIN();
			 String token = Response.getToken();
			
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"token" + token,mySession);
				
			  mySession.getVariableField(IProjectVariables.OAUTH,IProjectVariables.OAUTH_FIELD_TOKEN).setValue(token);

			
			//String preferredLanguage = data != null ? data.optString("preferredLanguage", null): null;

			String preferredLanguage =Response.getData().getPreferredLanguage();
			//String relationshipID = data != null ? data.optString("RelationshipID", null): null;
			String relationshipID = Response.getData().getRelationshipID();
			mySession.setProperty("RelationshipID",relationshipID);
			
			boolean hasBanking = false;
			boolean hasCredit = false;
			
			mySession.setProperty("HAS_TPIN", hasTPIN);
			
			if (Response.getData().getProducts() != null) {

			    for (Product product : Response.getData().getProducts()) {

			        String type = product.getType();
			        String status = product.getIsActive();
			        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"type : " + type+"status : "+status,mySession);

			        // Banking Account
			        if ("AC".equalsIgnoreCase(type) && "Y".equalsIgnoreCase(status) ) {
			        	hasBanking = true;
			        }

			        // Credit Card
			        if ("CC".equalsIgnoreCase(type) && "Y".equalsIgnoreCase(status) ) {
			            hasCredit = true;
			        }
			    }
			}
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Has_Banking : " + hasBanking,mySession);
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Has_Credit : " + hasCredit,mySession);
			
			mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_HAS_BANKING).setValue(hasBanking);
			mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_HAS_CREDIT).setValue(hasCredit);
			mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_RELATION_SHIP_ID).setValue(relationshipID);
			mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_RESPONSE).setValue(Response);
			mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_MOBILE_NUMBER).setValue(ResponseMobileNumber);
			mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_RMNFLAG).setValue(isRMN);
			mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_HAS_TPIN).setValue(hasTPIN);
			
			mySession.setProperty("relID", relationshipID);
			
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"isRMN : " + isRMN,mySession);
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Preferred Language : " + preferredLanguage,mySession);
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Response MobileNumber : " + ResponseMobileNumber,mySession);
			
			if(preferredLanguage != null) {				
				mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_PREFERRED_LANGUAGE).setValue(preferredLanguage);
				
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"Preferred Language is Not Null",mySession);
			}else {
				mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_PREFERRED_LANGUAGE).setValue(null);			
			}
		}else {
			
			mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_RMNFLAG).setValue(false);
		}
			String PreferredLanguage = mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_PREFERRED_LANGUAGE).getStringValue();
		} catch (Exception e) {
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"ERROR : "+e.getMessage(),mySession);
			e.printStackTrace();
			mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_API__STATUS).setValue(true);
			mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_RMNFLAG).setValue(false);
			e.printStackTrace();
		}
	
	}
}
