package flow;

/**
 * This is a special reserved class that is repsonsible for loading application 
 * variables as well as the forward to the actual first form of the application.<br>
 * This class should not be manually edited as changes may be overridden by the 
 * code generator.<br>
 * Last generated by Orchestration Designer at: 2026-FEB-01  06:53:38 PM
 */
public class Start extends com.avaya.sce.runtime.Entry {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-01  06:53:38 PM
	 */
	public Start() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method is generated automatically.  Any changes may be overwritten.
	 * Returns the submit object that will redirect application flow to the first
	 * form in the application.  This also adds various standard variables to the
	 * list of data to be submitted to the runtime variable table.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 * @return the Submit object that contains the standard variables and the first form
	 */
	public com.avaya.sce.runtime.Submit getSubmit(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Submit submit = new com.avaya.sce.runtime.Submit("LoadValues");
		return ( submit );
	}
	/**
	 * This method initializes the SCE session with the variables that
	 * are defined in the application.<BR>
	 * 
	 * This method is generated automatically and should not be manually
	 * edited because changes may be overwritten by future code 
	 * generation.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public void initializeVariables(com.avaya.sce.runtimecommon.SCESession session) {
		com.avaya.sce.runtimecommon.IVariable variable = null;
		String[] variableFields = null;

		variableFields = new String[] {
			IProjectVariables.TPIN___2FA_FIELD_STATUS };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TPIN___2FA, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.GENERATE_OTP_FIELD_COUNT,
			IProjectVariables.GENERATE_OTP_FIELD_OTP,
			IProjectVariables.GENERATE_OTP_FIELD_OTPREFERENCE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.GENERATE_OTP, variableFields, new String[] {"0", "", ""}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CC__OR__ACC__MENU_FIELD_CONFIDENCE,
			IProjectVariables.CC__OR__ACC__MENU_FIELD_INPUTMODE,
			IProjectVariables.CC__OR__ACC__MENU_FIELD_INTERPRETATION,
			IProjectVariables.CC__OR__ACC__MENU_FIELD_NOINPUTCOUNT,
			IProjectVariables.CC__OR__ACC__MENU_FIELD_NOMATCHCOUNT,
			IProjectVariables.CC__OR__ACC__MENU_FIELD_UTTERANCE,
			IProjectVariables.CC__OR__ACC__MENU_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CC__OR__ACC__MENU, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.PRODUCT_CODE_FIELD_ACCOUNT,
			IProjectVariables.PRODUCT_CODE_FIELD_CREDIT_CARD,
			IProjectVariables.PRODUCT_CODE_FIELD_MENU_SERVICE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.PRODUCT_CODE, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.RMNIDENTIFICATION_FIELD_HAS_TPIN,
			IProjectVariables.RMNIDENTIFICATION_FIELD_MOBILE_NUMBER,
			IProjectVariables.RMNIDENTIFICATION_FIELD_RELATION_SHIP_ID,
			IProjectVariables.RMNIDENTIFICATION_FIELD_RESPONSE,
			IProjectVariables.RMNIDENTIFICATION_FIELD_RMNFLAG };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.RMNIDENTIFICATION, variableFields, new String[] {"", "", "", "", "false"}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CALL_HISTORY_FIELD_CALL_DURATION,
			IProjectVariables.CALL_HISTORY_FIELD_DISPOSITION_TYPE,
			IProjectVariables.CALL_HISTORY_FIELD_END_DATE,
			IProjectVariables.CALL_HISTORY_FIELD_END_REASON,
			IProjectVariables.CALL_HISTORY_FIELD_EXIT_LOCATION,
			IProjectVariables.CALL_HISTORY_FIELD_IP,
			IProjectVariables.CALL_HISTORY_FIELD_LANGUAGE,
			IProjectVariables.CALL_HISTORY_FIELD_MENU_DESCRIPTION,
			IProjectVariables.CALL_HISTORY_FIELD_START_DATE,
			IProjectVariables.CALL_HISTORY_FIELD_TRANSFER_VDN };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CALL_HISTORY, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.TRANSFER, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.RETRY_FIELD_INVALID_NUMBER,
			IProjectVariables.RETRY_FIELD_MAX,
			IProjectVariables.RETRY_FIELD_NOINPUT,
			IProjectVariables.RETRY_FIELD_NOMATCH };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.RETRY, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.COLLECT__CC__OR__ACC_FIELD_CONFIDENCE,
			IProjectVariables.COLLECT__CC__OR__ACC_FIELD_INPUTMODE,
			IProjectVariables.COLLECT__CC__OR__ACC_FIELD_INTERPRETATION,
			IProjectVariables.COLLECT__CC__OR__ACC_FIELD_NOINPUTCOUNT,
			IProjectVariables.COLLECT__CC__OR__ACC_FIELD_NOMATCHCOUNT,
			IProjectVariables.COLLECT__CC__OR__ACC_FIELD_UTTERANCE,
			IProjectVariables.COLLECT__CC__OR__ACC_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.COLLECT__CC__OR__ACC, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.REDIRECTINFO_FIELD_PRESENTATIONINFO,
			IProjectVariables.REDIRECTINFO_FIELD_REASON,
			IProjectVariables.REDIRECTINFO_FIELD_SCREENINGINFO,
			IProjectVariables.REDIRECTINFO_FIELD_URI };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.REDIRECTINFO, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.PROMPT_HIN_URL_FIELD_PROMPT___1,
			IProjectVariables.PROMPT_HIN_URL_FIELD_PROMPT___1_0,
			IProjectVariables.PROMPT_HIN_URL_FIELD_PROMPT___2,
			IProjectVariables.PROMPT_HIN_URL_FIELD_PROMPT___3,
			IProjectVariables.PROMPT_HIN_URL_FIELD_PROMPT___4,
			IProjectVariables.PROMPT_HIN_URL_FIELD_PROMPT___5,
			IProjectVariables.PROMPT_HIN_URL_FIELD_PROMPT___6,
			IProjectVariables.PROMPT_HIN_URL_FIELD_PROMPT___7,
			IProjectVariables.PROMPT_HIN_URL_FIELD_PROMPT___8,
			IProjectVariables.PROMPT_HIN_URL_FIELD_PROMPT___9 };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.PROMPT_HIN_URL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.VARIABELS_FIELD_EMG_FLAG,
			IProjectVariables.VARIABELS_FIELD_EVENT_TYPE,
			IProjectVariables.VARIABELS_FIELD_EXCEED_COUNT,
			IProjectVariables.VARIABELS_FIELD_EXCEED_MAX,
			IProjectVariables.VARIABELS_FIELD_FINAL_FLAG,
			IProjectVariables.VARIABELS_FIELD_MAIN_MENU_OPTIONS,
			IProjectVariables.VARIABELS_FIELD_NO_AGENT,
			IProjectVariables.VARIABELS_FIELD_RETRY_COUNT,
			IProjectVariables.VARIABELS_FIELD_RETRY_COUNT__API,
			IProjectVariables.VARIABELS_FIELD_TPIN,
			IProjectVariables.VARIABELS_FIELD_TRANSFER_FLAG };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.VARIABELS, variableFields, new String[] {"", "", "3", "3", "", "", "", "0", "0", "", ""}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.PROMPT_FIELD_PROMPT___1,
			IProjectVariables.PROMPT_FIELD_PROMPT___2,
			IProjectVariables.PROMPT_FIELD_PROMPT___3,
			IProjectVariables.PROMPT_FIELD_PROMPT___4,
			IProjectVariables.PROMPT_FIELD_PROMPT___5 };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.PROMPT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DATE_FIELD_AUDIO,
			IProjectVariables.DATE_FIELD_DAYOFMONTH,
			IProjectVariables.DATE_FIELD_DAYOFWEEK,
			IProjectVariables.DATE_FIELD_DAYOFWEEKNUM,
			IProjectVariables.DATE_FIELD_DAYOFYEAR,
			IProjectVariables.DATE_FIELD_MONTH,
			IProjectVariables.DATE_FIELD_MONTHINYEAR,
			IProjectVariables.DATE_FIELD_YEAR };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DATE, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TPIN_FIELD_GOTO_TPIN };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TPIN, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.PRESS_3, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.COLLECT__OTP_FIELD_CONFIDENCE,
			IProjectVariables.COLLECT__OTP_FIELD_INPUTMODE,
			IProjectVariables.COLLECT__OTP_FIELD_INTERPRETATION,
			IProjectVariables.COLLECT__OTP_FIELD_NOINPUTCOUNT,
			IProjectVariables.COLLECT__OTP_FIELD_NOMATCHCOUNT,
			IProjectVariables.COLLECT__OTP_FIELD_UTTERANCE,
			IProjectVariables.COLLECT__OTP_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.COLLECT__OTP, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.PROMPT_URL_FIELD_BASE_URL,
			IProjectVariables.PROMPT_URL_FIELD_ENG_BASE_URL,
			IProjectVariables.PROMPT_URL_FIELD_HINDI_BASE_URL,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___1,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___1_0,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___2,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___3,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___4,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___5,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___6,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___7,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___8,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT___9,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT_COUNT,
			IProjectVariables.PROMPT_URL_FIELD_PROMPT_FULL_URL };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.PROMPT_URL, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.PRESS_1, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.FLAG_FIELD_AUTHENTICATION_FLAG___1,
			IProjectVariables.FLAG_FIELD_AUTHENTICATION_FLAG___2,
			IProjectVariables.FLAG_FIELD_COUNT,
			IProjectVariables.FLAG_FIELD_HAS_BANKING,
			IProjectVariables.FLAG_FIELD_HAS_CREDIT,
			IProjectVariables.FLAG_FIELD_IDENTIFICATION_FLAG,
			IProjectVariables.FLAG_FIELD_NEXT_NODE,
			IProjectVariables.FLAG_FIELD_ONE_FANAME,
			IProjectVariables.FLAG_FIELD_OTPFLAG,
			IProjectVariables.FLAG_FIELD_RETRY_FLAG,
			IProjectVariables.FLAG_FIELD_TRANSFER_VDN };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.FLAG, variableFields, new String[] {"false", "false", "0", "", "", "false", "", "", "", "", ""}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TPIN__AUTHENTICATION_FIELD_CONFIDENCE,
			IProjectVariables.TPIN__AUTHENTICATION_FIELD_INPUTMODE,
			IProjectVariables.TPIN__AUTHENTICATION_FIELD_INTERPRETATION,
			IProjectVariables.TPIN__AUTHENTICATION_FIELD_NOINPUTCOUNT,
			IProjectVariables.TPIN__AUTHENTICATION_FIELD_NOMATCHCOUNT,
			IProjectVariables.TPIN__AUTHENTICATION_FIELD_UTTERANCE,
			IProjectVariables.TPIN__AUTHENTICATION_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TPIN__AUTHENTICATION, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.NRMN__IDENTIFICATIONCOPY_FIELD_CONFIDENCE,
			IProjectVariables.NRMN__IDENTIFICATIONCOPY_FIELD_INPUTMODE,
			IProjectVariables.NRMN__IDENTIFICATIONCOPY_FIELD_INTERPRETATION,
			IProjectVariables.NRMN__IDENTIFICATIONCOPY_FIELD_NOINPUTCOUNT,
			IProjectVariables.NRMN__IDENTIFICATIONCOPY_FIELD_NOMATCHCOUNT,
			IProjectVariables.NRMN__IDENTIFICATIONCOPY_FIELD_UTTERANCE,
			IProjectVariables.NRMN__IDENTIFICATIONCOPY_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.NRMN__IDENTIFICATIONCOPY, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DYNAMIC_FIELD_CONFIDENCE,
			IProjectVariables.DYNAMIC_FIELD_INPUTMODE,
			IProjectVariables.DYNAMIC_FIELD_INTERPRETATION,
			IProjectVariables.DYNAMIC_FIELD_NOINPUTCOUNT,
			IProjectVariables.DYNAMIC_FIELD_NOMATCHCOUNT,
			IProjectVariables.DYNAMIC_FIELD_UTTERANCE,
			IProjectVariables.DYNAMIC_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DYNAMIC, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SESSION_FIELD_AAI,
			IProjectVariables.SESSION_FIELD_ANI,
			IProjectVariables.SESSION_FIELD_CALLTAG,
			IProjectVariables.SESSION_FIELD_CHANNEL,
			IProjectVariables.SESSION_FIELD_CHANNELTYPE,
			IProjectVariables.SESSION_FIELD_CONVERSEFIRST,
			IProjectVariables.SESSION_FIELD_CONVERSESECOND,
			IProjectVariables.SESSION_FIELD_CURRENTLANGUAGE,
			IProjectVariables.SESSION_FIELD_DNIS,
			IProjectVariables.SESSION_FIELD_EXIT_CUSTOMER_ID,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_1,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_2,
			IProjectVariables.SESSION_FIELD_EXIT_PARENT_ID,
			IProjectVariables.SESSION_FIELD_EXIT_PREFERRED_PATH,
			IProjectVariables.SESSION_FIELD_EXIT_REASON,
			IProjectVariables.SESSION_FIELD_EXIT_TOPIC,
			IProjectVariables.SESSION_FIELD_LASTERROR,
			IProjectVariables.SESSION_FIELD_MEDIATYPE,
			IProjectVariables.SESSION_FIELD_PROTOCOLNAME,
			IProjectVariables.SESSION_FIELD_PROTOCOLVERSION,
			IProjectVariables.SESSION_FIELD_SESSIONID,
			IProjectVariables.SESSION_FIELD_SESSIONLABEL,
			IProjectVariables.SESSION_FIELD_SHAREDMODE,
			IProjectVariables.SESSION_FIELD_UCID,
			IProjectVariables.SESSION_FIELD_UUI,
			IProjectVariables.SESSION_FIELD_VIDEOBITRATE,
			IProjectVariables.SESSION_FIELD_VIDEOCODEC,
			IProjectVariables.SESSION_FIELD_VIDEOENABLED,
			IProjectVariables.SESSION_FIELD_VIDEOFARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOFORMAT,
			IProjectVariables.SESSION_FIELD_VIDEOFPS,
			IProjectVariables.SESSION_FIELD_VIDEOHEIGHT,
			IProjectVariables.SESSION_FIELD_VIDEONEARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOWIDTH,
			IProjectVariables.SESSION_FIELD_VPCALLEDEXTENSION,
			IProjectVariables.SESSION_FIELD_VPCONVERSEONDATA,
			IProjectVariables.SESSION_FIELD_VPCOVERAGEREASON,
			IProjectVariables.SESSION_FIELD_VPCOVERAGETYPE,
			IProjectVariables.SESSION_FIELD_VPRDNIS,
			IProjectVariables.SESSION_FIELD_VPREPORTURL };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SESSION, variableFields, null, session, false, true );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.PRESS_2, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.NODE_DETAILS_FIELD_API__STATUS,
			IProjectVariables.NODE_DETAILS_FIELD_DESCRIPTION,
			IProjectVariables.NODE_DETAILS_FIELD_DTMF,
			IProjectVariables.NODE_DETAILS_FIELD_FETCH_NEXTNODE,
			IProjectVariables.NODE_DETAILS_FIELD_ID,
			IProjectVariables.NODE_DETAILS_FIELD_LANGUAGE,
			IProjectVariables.NODE_DETAILS_FIELD_NEXT_NODE,
			IProjectVariables.NODE_DETAILS_FIELD_PREFERRED_LANGUAGE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.NODE_DETAILS, variableFields, new String[] {"", "WELCOME", "", "WELCOME", "", "", "", ""}, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_ERRORCODE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_MESSAGE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_OBJECT,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_STACKTRACE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_TYPE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DD_LAST_EXCEPTION, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.OAUTH_FIELD_TOKEN };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.OAUTH, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TIME_FIELD_AUDIO,
			IProjectVariables.TIME_FIELD_HOUR,
			IProjectVariables.TIME_FIELD_MILLISECOND,
			IProjectVariables.TIME_FIELD_MINUTE,
			IProjectVariables.TIME_FIELD_SECOND,
			IProjectVariables.TIME_FIELD_TIMEZONE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TIME, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.API_FIELD_API_FAILED,
			IProjectVariables.API_FIELD_RELATIONSHIP_ID,
			IProjectVariables.API_FIELD_RESPONSE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.API, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SHAREDUUI_FIELD_ID,
			IProjectVariables.SHAREDUUI_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SHAREDUUI, variableFields, null, session, false, false );
		session.putVariable(variable);
	}
	/**
	 * This method returns the name of the application.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public String getEntryName() {
		return("BankingApplication");
	}
	/**
	 * This method returns a list of life cycle classes for Pluggable Connectors.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection getPluggableLifeCycle() {
		java.util.ArrayList result = new java.util.ArrayList();
		return(result);
	}
	/**
	 * This method returns a list of VXML contributor classes for Pluggable Connectors.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection getPluggableVXMLContrib() {
		java.util.ArrayList result = new java.util.ArrayList();
		return(result);
	}
	/**
	 * This method returns the root document for the application.
	 * This method is generated automatically and should not be modified
	 * because changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public String getRootDoc() {
		return("AppRoot");
	}
	/**
	 * This method returns a boolean to indicate if the approot node has a web page to show.
	 * This method is generated automatically and should not be modified
	 * because changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean hasWebPage(com.avaya.sce.runtimecommon.SCESession mySession) {
		return false;
	}
	/**
	 * Builds the list of input parameters that are defined for this application 
	 * entry.  This list is built automatically by adding Input Parameter
	 * nodes to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>java.lang.String</code> objects that
	 * are the names of parameters the application is expecting.
	 * If the AppRoot node does not have any input parameters, then 
	 * this returns an empty list
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection getInputParams(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
	/**
	 * Builds the list of capture expression that are defined for this application 
	 * entry.  This list is built automatically by adding Capture Expression
	 * items to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>CaptureExpression</code> objects that
	 * specify the ECMA script expression and the Orchestration Designer 
	 * session variable that will store the captured result.
	 * If the AppRoot node does not have any capture expression items, then 
	 * this returns an empty list
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection getCaptureExpressions(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
}
