package flow;

/**
 * Class that represents a call to a reusable application.
 * Last generated by Orchestration Designer at: 2026-FEB-13  11:51:00 AM
 */
public class TPIN1 extends com.avaya.sce.runtime.Invoke {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-13  11:51:00 AM
	 */
	public TPIN1() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		setNeedsDefaultDisconnectHandler(false);
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns a collection of Parameters that has information about the
	 * parameters to pass to the reusable module.  If it has
	 * no inputs, then an empty list is returned
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection getInputParams(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Parameter param = null;
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * Returns a collection of strings that are the names of the output parameters
	 * of the reusable application being invoked.  If it has no outputs, then an
	 * empty list is returned
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection getOutputParams(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * Returns the name of the next form in the application
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public String getNext() {
		return("CheckNode");
	}
	/**
	 * Returns the entry point URL to the application being invoked.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public String getWebAppEntryPoint(com.avaya.sce.runtimecommon.SCESession mySession) {
		String entryPoint = mySession.getParameter("module.TPIN.entrypoint");
		if (entryPoint != null)
			return checkEntryPoint(entryPoint, mySession);
		return(checkEntryPoint("TPIN/Start", mySession));
	}
	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the event handlers for the node, override:
	 *    void updateEvents(Collection events, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 * @return a collection of Events
	 */
	public java.util.Collection getEvents(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list;
		com.avaya.sce.runtime.Event event;
		list = new java.util.ArrayList();
		java.util.List eventPromptNames = null;
		String ___tempPromptName = null;
		return(list);
	}
	
	
	
	
	
	
	/**
	 * Returns the submit method.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public String getSubmitMethod() {
		return("get");
	}
	/**
	 * Returns the flag to indicate whether to use namelist.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean passParamsAsNameList() {
		return(false);
	}
	/**
	 * Returns the flag to indicate whether output data contains multipart.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean outputMultipart() {
		return(false);
	}
}
