package flow.subflow.NRMN_Identification;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.Collection;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;

import com.HostJar.API.api;
import com.HostJar.Flow.IVRFlow;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import DTO.NrmnValidationResponse;
import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2026-FEB-03  12:22:50 PM
 */
public class ValidateAccountNumber extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026-FEB-03  12:22:50 PM
	 */
	public ValidateAccountNumber() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("NRMN_Identification-Api", "Default");
		next.setDebugId(184);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026-FEB-20  11:52:55 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	@Override
	public void requestBegin(SCESession mySession) {

	    super.requestBegin(mySession);

	    try {

	        api.createSecureHttpClient();

	        String token = mySession.getVariableField(
	                IProjectVariables.OAUTH,
	                IProjectVariables.OAUTH_FIELD_TOKEN)
	                .getStringValue();

	        String accNum = mySession.getVariableField(
	                IProjectVariables.NRMN__IDENTIFICATIONCOPY,
	                IProjectVariables.NRMN__IDENTIFICATIONCOPY_FIELD_VALUE)
	                .getStringValue();

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "ACC NUM : " + accNum, mySession);

	        // ✅ Decide Account Type
	        String accType = (accNum != null && accNum.length() == 11) ? "ACCNO" : "CC";

	        String requestTime = java.time.Instant.now().toString();

	        String ucid = mySession.getVariableField(
	                IProjectVariables.SESSION,
	                IProjectVariables.SESSION_FIELD_UCID)
	                .getStringValue();

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "ACC TYPE : " + accType, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "UCID : " + ucid, mySession);
	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "REQ TIME : " + requestTime, mySession);

	        // ✅ API CALL
	        NrmnValidationResponse response =
	                api.NRMNidentificationAPI(ucid, accNum, accType, requestTime);

	        if (response == null) {

	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                    "NRMN API returned NULL response", mySession);
	            return;
	        }

	        
	        
	        boolean isRMN = response.getData().getIsRMN();
			boolean hasTPIN = response.getData().getHasTPIN();
			mySession.getVariableField(IProjectVariables.RMNIDENTIFICATION,IProjectVariables.RMNIDENTIFICATION_FIELD_HAS_TPIN).setValue(hasTPIN);
			
			
			//TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"token" + token,mySession);
				
			  mySession.getVariableField(IProjectVariables.OAUTH,IProjectVariables.OAUTH_FIELD_TOKEN).setValue(token);

			String relationshipID = response.getData().getRelationshipID();
			mySession.setProperty("RelationshipID",relationshipID);
			
			mySession.setProperty("HAS_TPIN", hasTPIN);
			
	  
	        String responseCode = response.getResponseCode();

	        mySession.getVariableField(
	                IProjectVariables.API,
	                IProjectVariables.API_FIELD_RESPONSE)
	                .setValue(responseCode);

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "Response Code : " + responseCode, mySession);

	       

	        NrmnValidationResponse.Data data = response.getData();

	        if (data == null) {

	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,
	                    "NRMN API DATA is NULL", mySession);
	            return;
	        }

	        
	        String mobileNumber = data.getMobileNumber();

	        mySession.getVariableField(
	                IProjectVariables.API,
	                IProjectVariables.API_FIELD_RELATIONSHIP_ID)
	                .setValue(relationshipID);

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "RelationshipID : " + relationshipID, mySession);

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "MobileNumber : " + mobileNumber, mySession);

	        

	        List<NrmnValidationResponse.Product> products = data.getProducts();

	        boolean hasAccount = false;
	        boolean hasCreditCard = false;

	        if (products != null && !products.isEmpty()) {

	            for (NrmnValidationResponse.Product product : products) {

	                if (product == null) continue;

	                String isActive = product.getIsActive();
	                String type = product.getType();
	                String productCode = product.getProductCode();

	                // ✅ Skip inactive
	                if (!"Y".equalsIgnoreCase(isActive) &&
	                    !"ACTIVE".equalsIgnoreCase(isActive)) {
	                    continue;
	                }

	                if ("AC".equalsIgnoreCase(type)) {

	                    hasAccount = true;

	                    mySession.getVariableField(
	                            IProjectVariables.PRODUCT_CODE,
	                            IProjectVariables.PRODUCT_CODE_FIELD_ACCOUNT)
	                            .setValue(productCode);

	                } else if ("CC".equalsIgnoreCase(type)) {

	                    hasCreditCard = true;

	                    mySession.getVariableField(
	                            IProjectVariables.PRODUCT_CODE,
	                            IProjectVariables.PRODUCT_CODE_FIELD_CREDIT_CARD)
	                            .setValue(productCode);
	                }
	            }
	        }
	        mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_HAS_BANKING).setValue(hasAccount);
			mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_HAS_CREDIT).setValue(hasCreditCard);
	        //---------------- MENU DECISION ----------------//

	        String serviceType;

	        if (hasAccount && hasCreditCard) {
	            serviceType = "BOTH";
	        }
	        else if (hasAccount) {
	            serviceType = "ACCOUNT";
	        }
	        else if (hasCreditCard) {
	            serviceType = "CARD";
	        }
	        else {
	            serviceType = "NONE";
	        }

	        mySession.getVariableField(
	                IProjectVariables.PRODUCT_CODE,
	                IProjectVariables.PRODUCT_CODE_FIELD_MENU_SERVICE)
	                .setValue(serviceType);

	        TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,
	                "Menu Service Set To: " + serviceType, mySession);

	    }
	    catch (Exception e) {

	        TraceInfo.trace(
	                ITraceInfo.TRACE_LEVEL_ERROR,
	                "NRMN API CALL FAILED",
	                mySession);
	        
	        String URL = mySession.getVariableField(IProjectVariables.PROMPT_URL,IProjectVariables.PROMPT_URL_FIELD_BASE_URL).getStringValue();
			 TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"URL : "+URL,mySession);
				if (URL.equalsIgnoreCase("/Prompts/ENGLISH/")) {
					String VDN = IVRFlow.getTransferVDN("ENGLISH","NRMN_IDENTIFICATION");
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS ENGLISH VDN : "+VDN,mySession);
					mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRANSFER_VDN).setValue(VDN);
				}else if (URL.equalsIgnoreCase("/Prompts/HINDI/")) {
					String VDN = IVRFlow.getTransferVDN("HINDI","NRMN_IDENTIFICATION");
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS HINDI VDN : "+VDN,mySession);
					mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRANSFER_VDN).setValue(VDN);
				}else {
					String VDN = IVRFlow.getTransferVDN("DEFAULT","NRMN_IDENTIFICATION");
					TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"SET AS DEFAULT VDN : "+VDN,mySession);
					mySession.getVariableField(IProjectVariables.FLAG,IProjectVariables.FLAG_FIELD_TRANSFER_VDN).setValue(VDN);
				}
				mySession.getVariableField(IProjectVariables.NODE_DETAILS,IProjectVariables.NODE_DETAILS_FIELD_API__STATUS).setValue(true);
				
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR,"ERROR : " + e.getMessage(),mySession);	
	    }
	}

}
